### ISSUE TITLE
SVG is not loaded properly.

### ISSUE THREAD

**Issue by JugnuPathak** [kangax/fabric.js#4685] opened 2018-02-07 09:37 UTC
## Version
1.7.21

## Test Case
http://jsfiddle.net/j57euLLr/

## Steps to reproduce
Open fiddle and click on load svg.

## Expected Behavior
SVG is not loaded properly. As you can see in fiddle. 

## Actual Behavior
This is the original [svg.](https://svgshare.com/i/5Q5.svg)

**Comment by asturur** [comment] 2018-02-07 09:47
duplicate of #1454

**Closed by asturur** 2018-02-07 09:47 UTC

**Comment by JugnuPathak** [comment] 2018-02-07 09:57
@asturur So no solution right now?
