### ISSUE TITLE
SVG Ungroup Import

### ISSUE THREAD

**Issue by mariusturcu1** [kangax/fabric.js#2467] opened 2015-09-03 07:39 UTC
Hi 
I use the svg from here: http://fabricjs.com/assets/172.svg and i imported  here: http://fabricjs.com/kitchensink/  as 'load without grouping'.

I saw there are some problemens parsing the svg. The imported svg doesn't look good on canvas.

I really need this feature in my project. If I imported the svg as grouped and call getActiveGroup() the result is null, i can't ungroup those object.
Please help!
Cheers!

**Comment by asturur** [comment] 2015-09-03 08:09
duplicate of #1520.

not supported yet.
stay tuned because it will soon.

**Closed by asturur** 2015-09-03 08:09 UTC

**Comment by mariusturcu1** [comment] 2015-09-03 08:15
thank you!
If the svg have only with paths everything is ok. The problems appear if svg have anothers type of objects.

**Comment by asturur** [comment] 2015-09-03 08:22
No, if the svg has no transformation, everything is ok. otherways no.
