### ISSUE TITLE
Exporting to SVG generate a diff image

### ISSUE THREAD

**Issue by marcelo3macedo** [kangax/fabric.js#3219] opened 2016-08-31 14:53 UTC
Hi FabricJS Team!

I m using a svg object file, combine with a image patternify.
When i try to export to SVG, the image generate is diferent of the canvas. (Pattern Size and position).

![differror](https://cloud.githubusercontent.com/assets/12199353/18133577/88d82bfa-6f71-11e6-8906-7099446b1f99.PNG)

Follow the code and files used:

> http://200.98.71.86/demo/svg/coracao.svg
http://200.98.71.86/demo/img/wolf.jpg

```
$(document).ready(function () {
    criarCanvas();
});

function criarCanvas() {
    var image = null;
    var canvas = new fabric.Canvas('canvasImage', {
        selectionLineWidth: 1,
        scaleY: 1,
        scaleX: 1,
        width: 600,
        height: 600,
        selection: false
    });

    fabric.Image.fromURL('img/wolf.jpg', function (img) {

        var patternSourceCanvas = new fabric.StaticCanvas();
        patternSourceCanvas.add(img);

        var pattern = new fabric.Pattern({
            source: function () {
                patternSourceCanvas.setDimensions({
                    width: img.getWidth(),
                    height: img.getHeight()
                });
                return patternSourceCanvas.getElement();
            },
            repeat: 'repeat'
        });

        fabric.loadSVGFromURL('svg/coracao.svg', function (objects, options) {
            objects[0].fill = pattern;
            var obj = fabric.util.groupSVGElements(objects, options);
            canvas.add(obj).renderAll();

            //window.open(canvas.toDataURL('png'));
            window.open(
                    'data:image/svg+xml;utf8,' +
                    encodeURIComponent(canvas.toSVG()));
        });

    });


}
;

```

**Comment by asturur** [comment] 2016-09-05 13:36
would you pack this code in a working fiddle? i will follow up shortly then.

**Comment by marcelo3macedo** [comment] 2016-09-20 18:59
Hi!
:)

Follow above:
http://jsfiddle.net/0fbefh52/49/

**Comment by asturur** [comment] 2016-10-02 10:25
cannot reproduce with your use case due to missing svg.
http://jsfiddle.net/0fbefh52/51/

with normal pattern it works.
I close the issue unless you can provide a working fiddle with the that generate the issue.

**Closed by asturur** 2016-10-02 10:25 UTC
