### ISSUE TITLE
Settings object control borders to a dashed array

### ISSUE THREAD

**Issue by onassar** [kangax/fabric.js#2700] opened 2015-12-21 05:14 UTC
I may have just missed it, but think it'd be helpful to be able to specify a `strokeDashArray` for object control-borders (while active). Is this possible?

**Comment by asturur** [comment] 2015-12-21 07:01
as of now it is not possible. not hard to implement.
if @kangax marks it as a possible feature is doable.

**Comment by onassar** [comment] 2015-12-21 15:04
Thanks @asturur
I did find a simple way by updating the source of `drawBorders` with the following:

    if (fabric.StaticCanvas.supports('setLineDash') === true) {
        ctx.setLineDash([4, 4]);
    }

The context is this: if the canvas has a black background, and the border is black, it can't be seen. Conversely, if I make the border white, then it can't be seen on a white background. The approach I just included above works to a certain extent, but unfortunately since the dashes are alternating color and a space, it's also prone to the same problem.

Is there a recommended practice for ensure that the border of an object can be seen when it's selected, regardless of the background color?

**Comment by asturur** [comment] 2016-04-30 12:36
I'm working on customizing controls. I close this as duplicate of customizing controls.
I'll try to include also dashed.

duplicate of #1947

**Closed by asturur** 2016-04-30 12:36 UTC
Labels: possible_feature

**Comment by asturur** [comment] 2016-05-02 06:42
I was think to always see the borders you can still override your dashing border, add an offset to the dash array ( it can be done ) and stroke opposite color.

setLinedDash [x,y]
stroke black
`ctx.lineDashOffset = x;`  --> this is actual code.
setLinedDash [y,x]
stroke white

i will not put this in the library as it is just additional complication of over complicated things, but if you try it and it works tell me.
