### ISSUE TITLE
May be a quick win on performance issue

### ISSUE THREAD

**Issue by mbaudry** [kangax/fabric.js#2553] opened 2015-10-14 16:08 UTC
Hello,

I have a request for you, about rendering performance on browsers like Firefox, because I noticed lower performance on it when moving objects on a canvas. I would like to suggest an improvement about this. Could it be possible to add a `requestAnimationFrame` on the `renderAll` function.

Doing so I hit 40fps against 20fps without it with my use case.

What do you think about it?

**Comment by asturur** [comment] 2015-10-14 16:12
duplicate of #1979.
Please chek older issue before opening new

**Closed by asturur** 2015-10-14 16:12 UTC
