### ISSUE TITLE
Importing svg with text does not work

### ISSUE THREAD

**Issue by dbubs** [kangax/fabric.js#2302] opened 2015-06-21 21:03 UTC
I am trying to load SVG from a string using `loadSVGFromString()` but the text inside `<tspan>` get combined into a single `<text>` tag. Upon looking through the code, I see this is happening inside `fabric.Text.fromElement`. I am thinking I will need to override this function in order to get imported text to look right, but I'm not sure how to create a `Text` object from a `text` node with multiple `tspan` nodes. Is this possible?

Here is the svg that I want to import into the canvas:
```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="100%" height="100%" style="background-color: rgba(255, 255, 255, 0)" viewBox="0 0 600 300" xml:space="preserve">
  <desc>Created with Fabric.js 1.5.0</desc>
  <defs></defs>  
  <g transform="translate(263.84 123.78)">
    <text font-family="signaritazhai" font-size="32" font-style="normal" font-weight="normal" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #454545; fill-rule: nonzero; opacity: 1;" >
      <tspan x="-229.1839" y="-55.7312" fill="#454545">A dream you dream </tspan>
      <tspan x="-229.1839" y="-13.7856" fill="#454545">alone is only a dream. </tspan>
      <tspan x="-229.1839" y="28.16" fill="#454545">A dream you dream </tspan>
      <tspan x="-229.1839" y="70.1056" fill="#454545">together is reality.</tspan>
    </text>
  </g>
  <g transform="translate(396.6 254)">
    <text font-family="arial" font-size="20" font-style="normal" font-weight="normal" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #454545; fill-rule: nonzero; opacity: 1;" >
      <tspan x="-63.9404" y="4.492" fill="#454545">- John Lennon</tspan>
    </text>
  </g>
</svg>
```

**Comment by asturur** [comment] 2015-06-21 21:41
tspan is not supported yet.
duplicate of #1280
Please to store and load back content do not use SVG.
Use toObject, fromObject methods.

**Closed by asturur** 2015-06-21 21:41 UTC

**Comment by dbubs** [comment] 2015-06-21 21:54
@asturur so if I serialize the object from `toObject` and store that in a database, will `fromObject` work properly?

**Comment by asturur** [comment] 2015-06-21 22:05
It will.
If not you can open an issue and get the bug fixed.
TSPAN support is one of the next features to get, but there are so many things that will stop some svg to be imported back  correctly ( patterns, resulting transformations, clipmask, masks )
