### ISSUE TITLE
Issue on zoom in canvas, object are blurred

### ISSUE THREAD

**Issue by mbaudry** [kangax/fabric.js#3565] opened 2016-12-22 09:29 UTC
## Version
1.7.2

I can't reproduce it on a fiddle, I'm sorry. But I made capture of my case

Not blurred:

![not_blurred](https://cloud.githubusercontent.com/assets/15127641/21421088/47ce7574-c831-11e6-81e5-875405f1b08c.png)

Blurred:
![blurred](https://cloud.githubusercontent.com/assets/15127641/21421089/4ae56ef2-c831-11e6-8084-e6e3eb924b8b.png)

## Steps to reproduce
write an IText, unzoom in the canvas and then zoom in. We can se that the text is blurred when we unzoom, and it's never clean again, even if we zoom.

It's blurred with the objectCaching set to true

**Comment by asturur** [comment] 2016-12-22 09:48
if you cannot reproduce in a fiddle is a problem with your own code.
So nothing we can fix it here.

**Comment by mbaudry** [comment] 2016-12-22 10:31
May be, I just know it appears since the objectCaching option was added, but I don't realy know if it's the main cause. I can't reproduce the exact same case in a fiddle for the moment :/

**Comment by asturur** [comment] 2016-12-23 20:48
if you are not going to open a fiddle for this problem please close the issue.

**Closed** 2016-12-23 21:05 UTC
