### ISSUE TITLE
FabricJS inside a rotated div

### ISSUE THREAD

**Issue by ombr** [kangax/fabric.js#4490] opened 2017-11-23 15:24 UTC
I would like to be able to interact with a rotated FabricJS canvas.
I think this is related to #868 and #1168.

Here is an example:

## Version
2.0 && 1.7.0

## Test Case
https://jsfiddle.net/ombr/phdmuuwy/2/

## Steps to reproduce
Apply a css `transform: rotation(180deg);` to the canvas container.

## Expected Behavior
I should be able to draw.

## Actual Behavior
The rotation is not taken into account.

Is there any plan to manage somethink like this ?

Thanks

**Comment by asturur** [comment] 2017-11-23 17:02
well there is a plan since there is a plan to make the upper canvas retina enabled.
the plan involves having a cross browser method to get all the css transforms applied to the element in a matrix form.

If you know something like that please surface it.

**Comment by asturur** [comment] 2017-11-23 17:03
duplicate of #3959

**Closed by asturur** 2017-11-23 17:03 UTC

**Comment by ombr** [comment] 2017-11-23 17:40
@asturur I started a library to this:

https://github.com/ombr/referentiel

Should I try to integrate it ?

**Comment by asturur** [comment] 2017-11-23 17:45
Good i see you know what is it about.
So fabricjs can already do that for svg transform attribute that is
similar. Would you like to see if the code in parser.js can be tweaked or
refactored to parse SVG and CSS transform attributes?

**Comment by ombr** [comment] 2017-11-23 22:06
Hi,

I just had a look and I got it working on my project by changing the function getPointer of 
https://github.com/kangax/fabric.js/blob/master/src/canvas.class.js#L1238

with this (less lines):
```
    getPointer: function (e, ignoreZoom, upperCanvasEl) {
      if (!upperCanvasEl) {
        upperCanvasEl = this.upperCanvasEl;
      }
      return getPointer(e);
      var pointer = getPointer(e),
          bounds = upperCanvasEl.getBoundingClientRect(),
          boundsWidth = bounds.width || 0,
          boundsHeight = bounds.height || 0,
          cssScale;

      var ref = new Referentiel(this.element); //Should be stored so it is cached...
      var point = ref.global_to_local([pointer.x, pointer.y]);
      //console.log('event:', event, element);
      pointer.x = point[0];
      pointer.y = point[1];

      if (!boundsWidth || !boundsHeight ) {
        if ('top' in bounds && 'bottom' in bounds) {
          boundsHeight = Math.abs( bounds.top - bounds.bottom );
        }
        if ('right' in bounds && 'left' in bounds) {
          boundsWidth = Math.abs( bounds.right - bounds.left );
        }
      }

      if (!ignoreZoom) {
        pointer = this.restorePointerVpt(pointer);
      }

      return {
        x: pointer.x,
        y: pointer.y
      };
    },
```

It would require add referentiel [less than 200 lines](https://github.com/ombr/referentiel/blob/master/src/referentiel.coffee).

How do you add/manage external dependency ? on Fabric.js ?

I did not manage to run the tests of Fabric.js locally (got QUnit is missing...) but might try again to create the pull-request.

@asturur What do you think about this ?

**Comment by asturur** [comment] 2017-11-23 22:31
is not aboit the 200 lines, would look crazy to clone a dependency.

i wondering if our code for the svg transform can be tweaked to do what referentiel does

**Comment by ombr** [comment] 2017-11-24 05:04
@asturur I tried to look at the svg transform code. Indeed, It does something similar.

I was not able to find where the computed matrix where used. Do you use it to compute positions or only to convert SVG to Fabric Objects ?

**Comment by asturur** [comment] 2017-11-24 09:53
the computed matrix are kept in the transformMatrix attribute, then decomposed and trow away.

fabric can catch those transfroms:

skewX(number)
skewY(number)
rotate(number)
scale(number) or scale(number,number)
translate(number) or translate(number,number)
matrix(n,n,n,n,n,n)

Which are the css transforms for css?
the first difference i can think of is rotate -> rotation.
can you think of others?

```javascript
number = fabric.reNum,

        commaWsp = '(?:\\s+,?\\s*|,\\s*)',

        skewX = '(?:(skewX)\\s*\\(\\s*(' + number + ')\\s*\\))',

        skewY = '(?:(skewY)\\s*\\(\\s*(' + number + ')\\s*\\))',

        rotate = '(?:(rotate)\\s*\\(\\s*(' + number + ')(?:' +
                    commaWsp + '(' + number + ')' +
                    commaWsp + '(' + number + '))?\\s*\\))',

        scale = '(?:(scale)\\s*\\(\\s*(' + number + ')(?:' +
                    commaWsp + '(' + number + '))?\\s*\\))',

        translate = '(?:(translate)\\s*\\(\\s*(' + number + ')(?:' +
                    commaWsp + '(' + number + '))?\\s*\\))',

        matrix = '(?:(matrix)\\s*\\(\\s*' +
                  '(' + number + ')' + commaWsp +
                  '(' + number + ')' + commaWsp +
                  '(' + number + ')' + commaWsp +
                  '(' + number + ')' + commaWsp +
                  '(' + number + ')' + commaWsp +
                  '(' + number + ')' +
                  '\\s*\\))',

        transform = '(?:' +
                    matrix + '|' +
                    translate + '|' +
                    scale + '|' +
                    rotate + '|' +
                    skewX + '|' +
                    skewY +
                    ')',

        transforms = '(?:' + transform + '(?:' + commaWsp + '*' + transform + ')*' + ')',

        transformList = '^\\s*(?:' + transforms + '?)\\s*$',

        // http://www.w3.org/TR/SVG/coords.html#TransformAttribute
        reTransformList = new RegExp(transformList),
        // == end transform regexp

        reTransform = new RegExp(transform, 'g');
```

**Comment by asturur** [comment] 2017-11-24 10:44
this is what mdn gives me

```css
transform: matrix(1.0, 2.0, 3.0, 4.0, 5.0, 6.0);
transform: translate(12px, 50%);
transform: translateX(2em);
transform: translateY(3in);
transform: scale(2, 0.5);
transform: scaleX(2);
transform: scaleY(0.5);
transform: rotate(0.5turn);
transform: skew(30deg, 20deg);
transform: skewX(30deg);
transform: skewY(1.07rad);
transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);
transform: translate3d(12px, 50%, 3em);
transform: translateZ(2px);
transform: scale3d(2.5, 1.2, 0.3);
transform: scaleZ(0.3);
transform: rotate3d(1, 2.0, 3.0, 10deg);
transform: rotateX(10deg);
transform: rotateY(10deg);
transform: rotateZ(10deg);
transform: perspective(17px);
```

removing the 3d methods that we can't support and removing the Z ones, i think is trivial to extend the regexps to support also the X/Y counter parts i wonder what is the rotate standard axis on the plane ( i would say Z but i can be wrong ).
Also i see some strange unit measures... `0.5turn` what is that?

**Comment by ombr** [comment] 2017-11-25 01:15
Ok I tested on code pen,
1turn -> 360deg
.5turn -> 180deg

Here is the list of the matrix we would have to parse:

transform: translateX(2em);
transform: translateY(3in);
transform: scale(2, 0.5);
transform: scaleX(2);
transform: scaleY(0.5);
transform: rotate(0.5turn);
transform: skew(30deg, 20deg);
transform: rotateZ(10deg);
transform: perspective(17px);

But there is another tricky part... In css you can define transform-origin... So you would need to take that into account too...

Another question, In referentiel, I am not computing the matrix from the raw css, I am getting the matrix directly via:

`window.getComputedStyle(element, null).getPropertyValue('transform')`

But It is not compatible with old Firefox and co... So it would be better to parse it directly... I will read more carefully how FabricJS Parser work arround this...

**Comment by ombr** [comment] 2017-11-25 03:16
So I looked at parser.js.

It will be tricky to get the equivalent to getComputedStyle on all browser... Jquery.css abstract this a bit.
I was able to make referentiel work on IE9 with the -ms- prefix but using Jquery.css instead of:
`window.getComputedStyle(element, null).getPropertyValue('transform')` :smile:

I still have a question, why do you need to parse the raw styles to compute the properties? Can't you use something like this: `window.getComputedStyle(element, null).getPropertyValue('transform')` of Jquery.css to get the value from the browser ?

**Comment by asturur** [comment] 2017-11-25 07:43
if getComputedStyle works with ie10+ firefox chrome and safari is ok.

i would get around the origin adding another translation matrix before all the rest.

if the getComputedStyle would work for svg attributes too would be good, but i do not think so.

**Comment by ombr** [comment] 2017-11-27 22:31
Hey,

Just tested this on IE10, firefox 16+, chrome 47+ but could not make it work on Safari :disappointed:

```html
<!DOCTYPE html>
<html>
  <head>
  <script
    src="https://code.jquery.com/jquery-1.12.4.js"
    integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU="
    crossorigin="anonymous"></script>
  </head>
  <style>
    #test{
      fill: red;
      transform: rotate(30deg);
      -webkit-transform: rotate(30deg);
      -ms-transform: rotate(30deg);
      -moz-transform: rotate(30deg);
      -o-transform: rotate(30deg);
    }
  </style>
<body>
<div>
<svg><g id="test"></g></svg>
</div>
<script>
$(function(){
  $('body').prepend($('#test').css('fill'));
  $('body').prepend($('#test').css('transform'));
});
</script>
</body>
</html>
```

Safari apply the transformation and I can see it in the debugger but can not get the value back...

**Comment by asturur** [comment] 2017-11-28 07:49
forgot we have also nodejs.
That even if it has not to  handle it completely, maybe jsdom does not support getComputedStyle.

**Comment by ombr** [comment] 2017-12-06 21:23
Hum indeed, jsdom does not support getComputedStyle...
I did a workaround here: https://github.com/ombr/fabric.js/commit/fcaac331b261109354679a962cf3dcf5ecdbbdd5

What do you think about something like that ?
