### ISSUE TITLE
Any plans to finish svgCache?

### ISSUE THREAD

**Issue by onassar** [kangax/fabric.js#2727] opened 2016-01-08 15:48 UTC
Could use it in a project I'm working on, and am hesitant to implement it myself incase I miss something or don't optimize it well for larger-svgs.

Any chance there's an implementation floating around somewhere in a branch?

**Comment by asturur** [comment] 2016-04-29 01:57
duplicate of #814.
Yes plan to do it.
Still some more important features before ( 3 of them )

**Closed by asturur** 2016-04-29 01:57 UTC
