### ISSUE TITLE
fabric.loadSVGFromURL gives No 'Access-Control-Allow-Origin' header is present on the requested resource. error

### ISSUE THREAD

**Issue by niyotaa** [kangax/fabric.js#3791] opened 2017-03-20 16:29 UTC
## Version
1.7.6

## Test Case
http://jsfiddle.net/7gvJG/166/

## Steps to reproduce
Run the fiddle
## Expected Behavior
Both SVG and image should load on the canvas but only image loads not the SVG image.
Both the images are in the same S3 amazon bucket
## Actual Behavior

i see others have the same issue but when they try to do a dataURL. i thought i'll create a new one.

Please let me know of any workaround to this issue if it exists.

Thanks,
Harsha

**Comment by niyotaa** [comment] 2017-03-21 18:37
just to help anyone looking to find a workaround, This is the solution that worked for me 
 HTTP.get(SVGURL, {}, function (err, response) {

            if (!err) {
                var svg = new String(response.content)
                fabric.loadSVGFromString(svg, function (ob, op) {
                    canvas.add(new fabric.PathGroup(ob, op).set({ left: 100, top: 100 }).scale(0.7));
                });
            }

        });

**Comment by niyotaa** [comment] 2017-03-22 14:31
well, even this solution  is not reliable.
I had to download the image on the server and pass it to the client. This is very slow but works all the time since the requests from my server to S3 has all the correct headers than request from client to S3.

I hope this feature gets implemented soon in fabricjs.

**Comment by asturur** [comment] 2017-03-25 17:30
duplicate of #3589

**Closed by asturur** 2017-03-25 17:30 UTC
Labels: possible_feature
