### ISSUE TITLE
Tosvg export not working with clipped canvas

### ISSUE THREAD

**Issue by nitin-bc** [kangax/fabric.js#4298] opened 2017-09-11 04:58 UTC
Hi,

I have been using canvas.toSVG() export feature. It seems working fine with single canvas without masking. But when i do apply mask on canvas then it doesn't return the result with masked element. Can you please help me out?

**Comment by nitin-bc** [comment] 2017-09-11 04:58
Also, is it possible to merge to svg output in case of multiple canvas?

**Comment by nitin-bc** [comment] 2017-09-12 05:01
Hi, is someone have any update for me?

**Comment by asturur** [comment] 2017-09-12 06:07
Hi @nitin-bc, being a free project, we work on it on free time, and days may lack of free time! yesterday was one of those.
Said so, the clip feature is not available in toSVG yet, not in svg import or export.

That is the next big feature we are going to work on.

**Comment by asturur** [comment] 2017-09-12 06:08
duplicate of #894

**Closed** 2017-09-12 06:30 UTC

**Comment by nitin-bc** [comment] 2017-09-12 07:17
Hi, thanks for the info. Can you please let me know once you are done with development? Also is it possible to merge multiple exported svg data from multiple canvas?
