### ISSUE TITLE
Chrome page crash when repeatedly updating fontSize within canvas.forEachObject

### ISSUE THREAD

**Issue by Koosmann** [kangax/fabric.js#2490] opened 2015-09-22 19:38 UTC
If you load this jsbin (http://jsbin.com/busokiyiva/edit?js,output) in chrome, then switch away from the tab, the page will crash (i.e. you'll get the 'Aw, snap!' page).

If you do the same with this jsbin (http://jsbin.com/hadeqequlu/1/edit?js,output), it won't crash.

The only difference is that the first uses ```canvas.forEachObject``` to do the iteration while the second uses a regular for loop.  Weirdly, this jsbin (http://jsbin.com/rugoxuviqe/1/edit?js,output) also does not crash, it does use ```canvas.forEachObject```, but the layers have the same ```fontSize```.

**Comment by asturur** [comment] 2015-09-22 20:15
Cannot reproduce.

**Comment by asturur** [comment] 2015-09-22 20:17
Cannot reproduce.

**Comment by Koosmann** [comment] 2015-09-22 20:45
Happens for me in OS X (10.10.5) / Chrome 45.0.2454.99 (64-bit).  I've been able to reproduce on 2 separate machines with this env.

**Comment by asturur** [comment] 2015-09-22 20:59
would it be possible for you to disable hardware acceleration and try again? i see it is causing major problems with 45.x and 64bit recently.
Expecially on intel integrated cards.

**Comment by Koosmann** [comment] 2015-09-22 21:11
In chrome://settings, I unchecked "Use hardware acceleration when available" and restarted.  Still happens :(

**Comment by Koosmann** [comment] 2015-09-25 20:40
Quick update on this, the crash does not happen in Chrome Canary; so, likely a Chrome issue.

**Comment by kangax** [comment] 2015-10-03 02:20
If it doesn't happen in Canary, I think it's safe to close this then.

**Closed by kangax** 2015-10-03 02:20 UTC
