### ISSUE TITLE
Setting  group evented to false doesnt work

### ISSUE THREAD

**Issue by kenmarshall** [kangax/fabric.js#2334] opened 2015-07-14 04:25 UTC
I want to be able to handle events on individual objects within a group. I figure setting the group evented property to false should solve that problem but apparent the group object still handling the event.

**Comment by asturur** [comment] 2016-04-26 01:49
Not evented to false is no meant for that.
Event in groups is not supported yet.
duplicate of #485

**Closed by asturur** 2016-04-26 01:49 UTC
Labels: needs_confirmation
