### ISSUE TITLE
Support for ClipPath

### ISSUE THREAD

**Issue by willmcneilly** [kangax/fabric.js#367] opened 2013-01-04 16:15 UTC
Hi.

I've come across a couple of SVGs that contain ClipPath Elements. Just wondering if there's been any thought on implementing this in Fabric?

Here's the W3 Spec, http://www.w3.org/TR/SVG/masking.html#EstablishingANewClippingPath

Thanks.

**Comment by kangax** [comment] 2015-04-16 11:45
Duplicate of #1454

**Closed by kangax** 2015-04-16 11:45 UTC
Labels: feature
