### ISSUE TITLE
Open SVG file in Illustrator

### ISSUE THREAD

**Issue by nikksan** [kangax/fabric.js#3011] opened 2016-05-26 09:45 UTC
Hey,
I`m using your library to generate svg,which I later on (with php) save to a file.
When the SVG has <image xlink:href="mysite.com/test.svg"></image> ,Ilustrator refuses to open it - thros error - Could not find a plug-in to read linked file 'test.svg' .
I tried replacing the whole <image> tag with the svg content,but the image tag has attributes that are lost,and even if I can now open it without problem,all the svgs are located somewhere else.
Can you help me figure out a way to open this file using Illustrator?

**Comment by asturur** [comment] 2016-05-26 10:11
Can you explain it better? example, file, error in illustrator.

**Comment by nikksan** [comment] 2016-05-26 10:18
Here is archive with the files.
The one called test.svg is the problematic one ,and the one with the prefix fix_ is the one that can be opened but svgs are not located correctly.
https://mega.nz/#!0V8V0TbB!WVjL22fMLw62ULu0m1MFWE6_SDSu7jh8fWJNtH4SfbU
The Iluustrator error is "Could not find a plug-in to read linked file 'test.svg' ..";

**Comment by asturur** [comment] 2016-05-26 10:51
You are loading 3 svg as images.
Illustrator does not like the external links as far as i remember.
You should  either:
1) Import that svg as pathgroups ( maybe with not perfect import )
2) write a function that instead of giving the link is giving the dataurl of the svg

i needed it once and i thit this:

```javascript
fabric.Image.prototype.getSvgSrc = function(embed) {
      return this.toDataURLforSVG();
    };
 fabric.Image.prototype.toDataURLforSVG = function(options) {
      options || (options = { });

      var el = fabric.util.createCanvasElement();

      el.width = this._element.naturalWidth;
      el.height = this._element.naturalHeight;

      // to avoid common confusion https://github.com/kangax/fabric.js/issues/806
      if (options.format === 'jpg') {
        options.format = 'jpeg';
      }

      if (options.format === 'jpeg') {
        canvas.backgroundColor = '#fff';
      }

      el.getContext("2d").drawImage(this._element, 0, 0);

      var data = el.toDataURL(options);

      return data;
    };

```

please try and then close the issue, it will be closed as other illustrator incompatibility or as duplicate of another issue that asks for embeeded svgs.

**Comment by nikksan** [comment] 2016-05-27 06:35
Hey ,we solved it by loading the svg ,using loadSvgFromString ,however now we face another issue.
There is a problem with some SVGs. When they are added to the canvas the following error occurs - 

> TypeError: Failed to execute 'createLinearGradient' on 'CanvasRenderingContext2D': The provided double value is non-finite.(…)

Here is a problematic a SVG - https://mega.nz/#!xd1EwaSS!s7KXaJJZIyMoKwsmtm-wJCNo60yjvXtRvPAzkKfEG3Q

**Comment by asturur** [comment] 2016-05-27 06:43
please attach the xml here, do not make me go on mega.nz, download, unzip.
Copy paste the svg code in the proper markup "insert code" the one with the icon <>

**Comment by nikksan** [comment] 2016-05-27 06:50
`<svg width="48" xmlns="http://www.w3.org/2000/svg" height="48" xmlns:xlink="http://www.w3.org/1999/xlink">
<defs>
<linearGradient id="linearGradient6019" xlink:href="#linearGradient6001" y1="-Infinity" y2="Infinity" x1="0.401576" x2="0.39193"/>
<linearGradient id="linearGradient6011" xlink:href="#linearGradient6001" y1="Infinity" y2="Infinity" x1="0.289787" x2="0.387118"/>
<linearGradient id="linearGradient6007" xlink:href="#linearGradient6001" y1="Infinity" y2="Infinity" x1="0.289787" x2="0.382702"/>
<linearGradient id="svg_1" xlink:href="#linearGradient6001" y1="-Infinity" y2="-Infinity" x1="0.635415" x2="0.612882"/>
<linearGradient id="linearGradient4126">
<stop offset="0" style="stop-color:#fff" id="stop4128"/>
<stop offset="1" style="stop-color:#fff;stop-opacity:.165" id="stop4130"/>
</linearGradient>
<linearGradient id="linearGradient4825">
<stop offset="0" style="stop-color:#fff" id="stop4827"/>
<stop offset="1" style="stop-color:#fff;stop-opacity:0" id="stop4829"/>
</linearGradient>
<linearGradient id="linearGradient6001">
<stop offset="0" style="stop-color:#fff" id="stop6003"/>
<stop offset="1" style="stop-color:#fff;stop-opacity:0" id="stop6005"/>
</linearGradient>
<linearGradient id="linearGradient3962">
<stop offset="0" style="stop-color:#d3e9ff" id="stop3964"/>
<stop offset="0.155172" style="stop-color:#d3e9ff" id="stop4134"/>
<stop offset="0.75" style="stop-color:#4074ae" id="stop4346"/>
<stop offset="1" style="stop-color:#36486c" id="stop3966"/>
</linearGradient>
<radialGradient fx="18.247644" fy="15.716079" cx="18.247644" cy="15.716079" gradientTransform="scale(0.999989,1.000011)" r="29.993349" id="radialGradient3968" xlink:href="#linearGradient3962" gradientUnits="userSpaceOnUse"/>
<radialGradient fx="12.071323" fy="12.493138" cx="12.071323" cy="12.493138" r="6.717515" id="radialGradient5989" xlink:href="#linearGradient4825" gradientUnits="userSpaceOnUse"/>
<radialGradient fx="12.071323" fy="12.493138" cx="12.071323" cy="12.493138" r="6.717515" id="radialGradient5987" xlink:href="#linearGradient4825" gradientUnits="userSpaceOnUse"/>
<radialGradient fx="15.601279" fy="12.142302" cx="15.601279" cy="12.142302" gradientTransform="scale(0.999989,1.000011)" r="43.526714" id="radialGradient4132" xlink:href="#linearGradient4126" gradientUnits="userSpaceOnUse"/>
<radialGradient fx="12.071323" fy="12.493138" cx="12.071323" cy="12.493138" r="6.717515" id="radialGradient5985" xlink:href="#linearGradient4825" gradientUnits="userSpaceOnUse"/>
<radialGradient fx="12.071323" fy="12.493138" cx="12.071323" cy="12.493138" r="6.717515" id="radialGradient5983" xlink:href="#linearGradient4825" gradientUnits="userSpaceOnUse"/>
</defs>
<g>
<g id="layer1" externalResourcesRequired="false">
<path style="fill:url(#radialGradient3968);stroke:#39396c" id="path3214" d="m 43.9599,23.4855 c 0,10.7097 -8.6821,19.3917 -19.3903,19.3917 -10.7092,0 -19.3908,-8.6821 -19.3908,-19.3917 0,-10.7092 8.68161,-19.3904 19.3908,-19.3904 10.7082,0 19.3903,8.68112 19.3903,19.3904 z "/>
<g style="fill:#204a87;fill-opacity:.713" id="g4136" transform="matrix(0.982371,0.000000,0.000000,0.982371,0.121079,0.232914)">
<g id="g4138">
<g id="g4142">
<path id="path4144" d="m 44.0713,20.7144 c 0,0.262701 0,0 0,0 l -.5449,.6172 c -0.334,-0.3936 -0.709,-0.7246 -1.0898,-1.0703 l -.8359,.123 -.7637,-.8633 v 1.0684 l .6543,.4951 .4355,.4932 .582,-.6582 c 0.1465,0.274399 0.291,0.5488 0.436501,0.8232 v 0.8223 l -.6553,.7402 -1.1992,.8232 -.9082,.9063 -.582,-.6602 .291,-.7402 -.5811,-.6582 -.9814,-2.0977 -.8359,-.9453 -.2188,.2461 .3281,1.1934 .6172,.6992 c 0.352501,1.0176 0.701199,1.9902 1.1641,2.9629 0.7178,0 1.3945,-0.0762 2.1074,-0.166 v 0.5762 l -.8721,2.1392 -.7998,.9043 -.6543,1.4004 c 0,0.767601 0,1.5352 0,2.3027 l .2188,.9063 -.3633,.4102 -.8008,.4941 -.8359,.6992 .6914,.7813 -.9453,.8242 .1816,.5332 -1.418,1.6055 h -0.944302 l -.7998,.4941 h -0.5098 v -0.658203 l -.2168,-1.3184 c -0.2813,-0.826202 -0.5742,-1.6465 -0.872097,-2.4668 0,-0.605499 0.036098,-1.2051 0.0723,-1.8105 l .3643,-.8223 -.5098,-.9883 .0371,-1.3574 -.6914,-.7813 .3457,-1.1309 -.5625,-.6382 h -0.982399 l -.3271,-.3701 -.9814,.6177 -.3994,-.4536 -.9092,.7817 c -0.617201,-0.699699 -1.2354,-1.3989 -1.8535,-2.0981 l -.7266,-1.7285 .6543,-.9863 -.3633,-.4111 .7988,-1.8936 c 0.6563,-0.816401 1.3418,-1.5996 2.0352,-2.3857 l 1.2363,-.3291 1.3809,-.1641 .9453,.2471 1.3447,1.3564 .4727,-.5342 .6533,-.082 1.2363,.4111 h 0.945301 l .6543,-.5762 .291,-.4111 -.6553,-.4111 -1.0908,-.082 c -0.3027,-0.419901 -0.584,-0.8613 -0.943401,-1.2344 l -.3643,.1641 -.1455,1.0703 -.6543,-.7402 -.1445,-.8242 -.7266,-.5742 h -0.292 l .7275,.8223 -.291,.7402 -.5811,.1641 .3633,-.7402 -.6553,-.3281 -.5801,-.6582 -1.0918,.2461 -.1445,.3281 -.6543,.4121 -.3633,.9053 -.9082,.4521 -.4004,-.4521 h -0.435499 v -1.4814 l .9453,-.4941 h 0.726601 l -.1465,-.5752 -.5801,-.5762 .9805,-.2061 .5449,-.6162 .4355,-.7412 h 0.8008 l -.2188,-.5752 .5098,-.3291 v 0.6582 l 1.0898,.2461 1.0898,-.9043 .0732,-.4121 .9443,-.6577 c -0.341801,0.0425 -0.683598,0.0737 -1.0176,0.1646 v -0.7411 l .3633,-.8228 h -0.363297 l -.7984,.7402 -.2188,.4116 .2188,.5767 -.3643,.9863 -.5811,-.3291 -.5078,-.5752 -.8008,.5752 -.291,-1.3159 1.3809,-.9048 v -0.4941 l .873,-.5757 1.3809,-.3296 .9453,.3296 1.7441,.3291 -.4355,.4932 h -0.945301 l .9453,.9873 .7266,-.8223 .2207,-.3618 c 0,0 2.7871,2.498 4.3799,5.2305 1.5928,2.7334 2.3408,5.9551 2.3408,6.6094 z "/>
</g>
</g>
<g id="g4146">
<g id="g4150">
<path id="path4152" d="m 26.0703,9.2363 l -.0732,.4932 .5098,.3291 .8711,-.5757 -.4355,-.4937 -.582,.3296 -.29,-.0825"/>
</g>
</g>
<g id="g4154">
<g id="g4158">
<path id="path4160" d="m 26.8701,5.8633 l -1.8906,-.7407 -2.1797,.2466 -2.6904,.7402 -.5088,.4941 1.6719,1.1514 v 0.6582 l -.6543,.6582 .873,1.729 .5801,-.3301 .7285,-1.1514 c 1.123,-0.3472 2.1299,-0.7407 3.1973,-1.2344 l .873,-2.2212"/>
</g>
</g>
<g id="g4162">
<g id="g4166">
<path id="path4168" d="m 28.833,12.7749 l -.291,-.7412 -.5098,.165 .1465,.9043 .6543,-.3281"/>
</g>
</g>
<g id="g4170">
<g id="g4174">
<path id="path4176" d="m 29.123,12.6089 l -.1455,.9883 .7998,-.165 .5811,-.5752 -.5088,-.4941 c -0.1709,-0.4551 -0.367199,-0.8799 -0.5811,-1.3164 h -0.435499 v 0.493199 l .29,.3291 v 0.7402"/>
</g>
</g>
<g id="g4178">
<g id="g4182">
<path id="path4184" d="m 18.3652,28.2422 l -.582,-1.1523 -1.0903,-.2466 -.5815,-1.5625 -1.4536,.1641 -1.2354,-.9043 -1.3091,1.1514 v 0.181601 c -0.396,-0.1143 -0.8828,-0.1299 -1.2354,-0.346701 l -.291,-.8223 v -0.9053 l -.8721,.082 c 0.0728,-0.5762 0.145,-1.1514 0.2183,-1.7275 h -0.509299 l -.5083,.6582 -.5093,.2461 -.7271,-.4102 -.0728,-.9053 .1455,-.9873 1.0908,-.8223 h 0.8721 l .145,-.4941 1.0903,.2461 .7998,.9883 .1455,-1.6465 1.3813,-1.1514 .5088,-1.2344 1.0176,-.4111 .5815,-.8223 1.3081,-.248 .6548,-.9863 c -0.654301,0 -1.3086,0 -1.9629,0 l 1.2358,-.5762 h 0.871599 l 1.2363,-.4121 .1455,-.4922 -.4365,-.4121 -.5088,-.165 .1455,-.4932 -.3633,-.7402 -.8726,.3281 .1455,-.6577 -1.0176,-.5762 -.7993,1.3979 .0723,.4941 -.7993,.3301 -.5093,1.0693 -.2178,-.9873 -1.3813,-.5762 -.2183,-.7402 1.8174,-1.0703 .7998,-.7402 .0728,-.9048 -.436,-.2471 -.5815,-.0825 -.3633,.9053 c 0,0 -0.6079,0.1191 -0.7642,0.1577 -1.9961,1.8394 -6.0293,5.8101 -6.9663,13.3062 0.0371,0.1738 0.6792,1.1816 0.6792,1.1816 l 1.5264,.9043 1.5264,.4121 .6548,.8232 1.0171,.7402 .5815,-.082 .436,.1963 v 0.132801 l -.5811,1.563 -.4365,.6582 .1455,.3301 -.3633,1.2324 1.3086,2.3867 1.3081,1.1523 .582,.8223 -.0732,1.7285 .4365,.9863 -.4365,1.8926 c 0,0 -0.034201,-0.0117 0.0215,0.1777 0.0562,0.189499 2.3291,1.4512 2.4736,1.3438 0.144001,-0.109398 0.267101,-0.205101 0.267101,-0.205101 l -.145,-.4102 .5811,-.5762 .2183,-.5762 .9453,-.3301 .7266,-1.8105 -.2178,-.4922 .5078,-.7402 1.0908,-.248 .582,-1.3164 -.1455,-1.6445 .8721,-1.2344 .1455,-1.2344 c -1.1934,-0.591801 -2.377,-1.2012 -3.5615,-1.8105"/>
</g>
</g>
<g id="g4186">
<g id="g4190">
<path id="path4192" d="m 16.7656,9.5649 l .7266,.4937 h 0.581999 v -0.575701 l -.7266,-.3291 -.582,.4111"/>
</g>
</g>
<g id="g4194">
<g id="g4198">
<path id="path4200" d="m 14.876,8.9072 l -.3638,.9048 h 0.727099 l .3638,-.8228 c 0.3135,-0.2217 0.6255,-0.444799 0.944799,-0.658199 l .7271,.2471 c 0.4844,0.3291 0.9688,0.6582 1.4536,0.9868 l .7275,-.6577 -.8003,-.3291 -.3638,-.7407 -1.3809,-.1646 -.0728,-.4116 -.6543,.165 -.2904,.5758 -.3638,-.7407 -.145,.3291 .0728,.8228 -.5816,.494"/>
</g>
</g>
<g id="g4202">
<g style="opacity:.75" id="g4204"/>
<g id="g4208"/>
</g>
<g id="g4212">
<g style="opacity:.75" id="g4214"/>
<g id="g4218"/>
</g>
<g id="g4222">
<g id="g4226">
<path id="path4228" d="m 17.4922,6.8496 l .3638,-.3286 .7271,-.1646 c 0.498001,-0.2422 0.998001,-0.4053 1.5264,-0.5762 l -.29,-.4937 -.9385,.1348 -.4434,.4419 -.731,.106 -.6499,.3052 -.3159,.1528 -.1929,.2583 .9443,.1641"/>
</g>
</g>
<g id="g4230">
<g id="g4234">
<path id="path4236" d="m 18.7285,14.6665 l .4365,-.6582 -.6548,-.4932 .2183,1.1514"/>
</g>
</g>
</g>
<g style="fill:none">
<path style="opacity:.396;stroke:url(#radialGradient4132)" id="path4122" d="m 42.9751,23.4855 c 0,10.1658 -8.24118,18.4069 -18.4056,18.4069 -10.1654,0 -18.4061,-8.24118 -18.4061,-18.4069 0,-10.1654 8.24071,-18.4056 18.4061,-18.4056 10.1644,0 18.4056,8.24025 18.4056,18.4056 z "/>
<g style="stroke-linecap:round;fill-rule:evenodd;stroke-linejoin:round;stroke-width:.882">
<path style="stroke:url(#linearGradient6007)" id="path5991" d="m 40.8641,32.8088 a 17.7947,8.31455 0 1,1 -35.5894,-19.2919 17.7947,8.31455 0 1,1 35.5894,19.2919 z "/>
<path style="stroke:url(#linearGradient6011)" id="path6009" d="m 44.0351,13.398 a 14.7785,6.90525 0 1,1 -29.5571,27.6615 14.7785,6.90525 0 1,1 29.5571,-27.6615 z "/>
</g>
</g>
<g style="fill-rule:evenodd;stroke-linecap:round;stroke-linejoin:round">
<g id="g4933" transform="matrix(-1.04577 0.767251 0.767251 1.04577 35.6165 -22.144)">
<path style="fill:url(#radialGradient5987)" id="path4935" d="m 33.7391,35.4236 a 6.71751,6.71751 0 1,1 -13.435,0 6.71751,6.71751 0 1,1 13.435,0 z "/>
<path style="fill:#fff" id="path4937" d="m 29.0924,35.4236 a 2.07081,2.07081 0 1,1 -4.14163,0 2.07081,2.07081 0 1,1 4.14163,0 z "/>
</g>
<g style="fill:none">
<path style="stroke:url(#svg_1);stroke-width:.882" id="path6013" d="m 3.2795,19.9406 a 20.1434,9.41196 0 1,1 40.2867,3.96975 20.1434,9.41196 0 1,1 -40.2867,-3.96975 z "/>
<path style="stroke:url(#linearGradient6019);stroke-width:.902" id="path6017" d="m 39.0865,10.5322 a 14.441,6.74733 0 1,1 -28.8821,27.029 14.441,6.74733 0 1,1 28.8821,-27.029 z "/>
</g>
<g id="g5075" transform="matrix(-0.806276,0.59154,0.59154,0.806276,12.38564,-18.02921)">
<path style="fill:url(#radialGradient5983)" id="path5077" d="m 33.7391,35.4236 a 6.71751,6.71751 0 1,1 -13.435,0 6.71751,6.71751 0 1,1 13.435,0 z "/>
<path style="fill:#fff" id="path5079" d="m 29.0924,35.4236 a 2.07081,2.07081 0 1,1 -4.14163,0 2.07081,2.07081 0 1,1 4.14163,0 z "/>
</g>
<g id="g4945" transform="matrix(-0.806276,0.59154,0.59154,0.806276,13.4991,-31.50022)">
<path style="fill:url(#radialGradient5985)" id="path4947" d="m 33.7391,35.4236 a 6.71751,6.71751 0 1,1 -13.435,0 6.71751,6.71751 0 1,1 13.435,0 z "/>
<path style="fill:#fff" id="path4949" d="m 29.0924,35.4236 a 2.07081,2.07081 0 1,1 -4.14163,0 2.07081,2.07081 0 1,1 4.14163,0 z "/>
</g>
<g id="g4939" transform="matrix(-0.870227,0.638572,0.638458,0.870381,25.20503,-35.31278)">
<path style="fill:url(#radialGradient5989)" id="path4941" d="m 33.7391,35.4236 a 6.71751,6.71751 0 1,1 -13.435,0 6.71751,6.71751 0 1,1 13.435,0 z "/>
<path style="fill:#fff" id="path4943" d="m 29.0924,35.4236 a 2.07081,2.07081 0 1,1 -4.14163,0 2.07081,2.07081 0 1,1 4.14163,0 z "/>
</g>
</g>
</g>
</g>
</svg>
`

**Comment by asturur** [comment] 2016-05-27 07:05
infinity in gradient definition. i have to check if this is in the spec, if it is, we are gonna support it, at least swapping with correct value.

**Comment by asturur** [comment] 2016-05-27 07:52
It is not supported. There is an attribute spreadMethod = "pad | reflect | repeat" that we do not support yet but should not create problems to you.
at least here
https://www.w3.org/TR/SVG/pservers.html#LinearGradientElementX1Attribute

they talk about numbers and canvas wants a double, that this may be another problem also.

**Comment by nikksan** [comment] 2016-05-27 12:40
Hmm...
The problem comes is here: 
`createLinearGradient(r.x1, r.y1, r.x2, r.y2)`

> r.y1 = 'Infinity' , so as r.y2
Can you help me resolve it?

**Comment by nikksan** [comment] 2016-05-30 06:20
Anyone?

**Comment by asturur** [comment] 2016-05-30 13:18
remove the infinity on x1,y1 with 0 , while x2,y2 infinities with 1.
We cannot do more than this now.

**Closed** 2016-07-17 08:31 UTC
Labels: needs_confirmation, svg_parser
