### ISSUE TITLE
Unable to install fabric js on Node 4.2.4 Npm 3.5.3 Node-gyp 3.2.1

### ISSUE THREAD

**Issue by khawerrind** [kangax/fabric.js#2755] opened 2016-01-27 08:30 UTC
I am unable to install fabric js on `Node 4.2.4` `Npm 3.5.3` `Node-gyp 3.2.1`. Here are the errors i am having

```code
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\CanvasGr
adient.cc) [C:\projects\frontend\node_modules\fabric\node_modules\canvas\build\canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): note: command-line arguments:  see previous definition of 'snprintf' (compiling so
  urce file ..\src\CanvasGradient.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Lib
rary function declaration (compiling source file ..\src\CanvasGradient.cc) [C:\projects\frontend\node_modules\fabric\node_modules\canvas\build\canvas.vcx
proj]
  color.cc
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\CanvasPa
ttern.cc) [C:\projects\frontend\node_modules\fabric\node_modules\canvas\build\canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): note: command-line arguments:  see previous definition of 'snprintf' (compiling so
  urce file ..\src\CanvasPattern.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Lib
rary function declaration (compiling source file ..\src\CanvasPattern.cc) [C:\projects\frontend\node_modules\fabric\node_modules\canvas\build\canvas.vcxp
roj]
  Image.cc
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\Canvas.c
c) [C:\projects\frontend\node_modules\fabric\node_modules\canvas\build\canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): note: command-line arguments:  see previous definition of 'snprintf' (compiling so
  urce file ..\src\Canvas.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Lib
rary function declaration (compiling source file ..\src\Canvas.cc) [C:\projects\frontend\node_modules\fabric\node_modules\canvas\build\canvas.vcxproj]
  ImageData.cc
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\color.cc
) [C:\projects\frontend\node_modules\fabric\node_modules\canvas\build\canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): note: command-line arguments:  see previous definition of 'snprintf' (compiling so
  urce file ..\src\color.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Lib
rary function declaration (compiling source file ..\src\color.cc) [C:\projects\frontend\node_modules\fabric\node_modules\canvas\build\canvas.vcxproj]
  init.cc
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\Image.cc
) [C:\projects\frontend\node_modules\fabric\node_modules\canvas\build\canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): note: command-line arguments:  see previous definition of 'snprintf' (compiling so
  urce file ..\src\Image.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Lib
rary function declaration (compiling source file ..\src\Image.cc) [C:\projects\frontend\node_modules\fabric\node_modules\canvas\build\canvas.vcxproj]
  PixelArray.cc
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\ImageDat
a.cc) [C:\projects\frontend\node_modules\fabric\node_modules\canvas\build\canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): note: command-line arguments:  see previous definition of 'snprintf' (compiling so
  urce file ..\src\ImageData.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Lib
rary function declaration (compiling source file ..\src\ImageData.cc) [C:\projects\frontend\node_modules\fabric\node_modules\canvas\build\canvas.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\CanvasRe
nderingContext2d.cc) [C:\projects\frontend\node_modules\fabric\node_modules\canvas\build\canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): note: command-line arguments:  see previous definition of 'snprintf' (compiling so
  urce file ..\src\CanvasRenderingContext2d.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Lib
rary function declaration (compiling source file ..\src\CanvasRenderingContext2d.cc) [C:\projects\frontend\node_modules\fabric\node_modules\canvas\build\
canvas.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\init.cc)
 [C:\projects\frontend\node_modules\fabric\node_modules\canvas\build\canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): note: command-line arguments:  see previous definition of 'snprintf' (compiling so
  urce file ..\src\init.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Lib
rary function declaration (compiling source file ..\src\init.cc) [C:\projects\frontend\node_modules\fabric\node_modules\canvas\build\canvas.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\PixelArr
ay.cc) [C:\projects\frontend\node_modules\fabric\node_modules\canvas\build\canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): note: command-line arguments:  see previous definition of 'snprintf' (compiling so
  urce file ..\src\PixelArray.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Lib
rary function declaration (compiling source file ..\src\PixelArray.cc) [C:\projects\frontend\node_modules\fabric\node_modules\canvas\build\canvas.vcxproj
]
```

I have installed manually `Canvas v1.3.8` without any issues. Maybe you need to upgrade to `Canvas 1.3.x`?

**Comment by mahnunchik** [comment] 2016-02-01 10:23
+1

**Comment by asturur** [comment] 2016-02-08 13:36
duplicate of #2609

**Closed by asturur** 2016-02-08 13:36 UTC

**Comment by jtencate** [comment] 2016-02-22 14:32
Just like to point out that this issue was on a Windows machine where #2609 was on iOS. Specifically the problem here is what is discussed here: http://stackoverflow.com/questions/27754492/vs-2015-compiling-cocos2d-x-3-3-error-fatal-error-c1189-error-macro-definiti
