### ISSUE TITLE
Hebrew text issue with annotation

### ISSUE THREAD

**Issue by chehmer** [kangax/fabric.js#2825] opened 2016-03-07 09:15 UTC
version v1.6.0-rc.1

The main issue : The Hebrew text created with reverse direction on the canvas :
```
var canvas = fabric.createCanvasForNode(867, 1211);
var text = new fabric.IText('שלום', {
  left: 50,
  top: 50,
  fill: '#f55',
  angle: 15,
  fontFamily:'sans-serif',
});
canvas.add(text);

var stream = canvas.createPNGStream();
stream.on('data', function(chunk) {
  out.write(chunk);
});
```

This result is an PNG file with image "םולש" on it (this need to be "שלום")

There is a solution for that ? or any work around ?

Thanks you,
Roy

**Comment by asturur** [comment] 2016-03-07 09:29
duplicate of #2673

**Closed by asturur** 2016-03-07 09:29 UTC

**Comment by chehmer** [comment] 2016-03-07 09:52
Hello,
Thank you for your quick reply.

I don't think that this issue is exactly like #2673, it's not about the RTL direction of the text.
This issue is point only to the - CanvasForNode in the node.js server that the Hebrew (and I guess also with Arabic) letters which present in reverse position.

the fabric canvas in js (in the browsers) is working well on the Hebrew letters...

Thank you,
Roy

**Comment by asturur** [comment] 2016-08-07 20:06
#2374

**Comment by YaakovHatam** [comment] 2020-05-17 14:54
@chehmer bplease look at the issue #2374 i am developing a RTL version please test it
