### ISSUE TITLE
Path positions are distorted after updating / re-initialization of the path.

### ISSUE THREAD

**Issue by ayanonly1** [kangax/fabric.js#2550] opened 2015-10-14 11:30 UTC
Sample fiddel- http://jsfiddle.net/d7c645pg/3/

I have created a path (rect with path command). The path is starting 50 away from the left border. Initiallt the path element is as expected.
But later when I update the path with another path command (rectangle of 150 \* 50 dimenssion starting from 150,50 position.), the path is placed at 175 px away from the left.

// creation of the path-
 var canvas = new fabric.Canvas('c', {width: 400, height: 400});
 var line = new fabric.Path('M,50,50,L,50,150,150,150,150,50,Z', {  
    fill: 'blue'
});
//line.setCoords();
canvas.add(line);
canvas.renderAll();

// during updating
line.initialize('M,150,50,L,150,150,300,150,300,50,Z')
 //line.setCoords();
 canvas.renderAll();

<img width="410" alt="screen shot 2015-10-14 at 4 59 24 pm" src="https://cloud.githubusercontent.com/assets/1720560/10482326/fe82deb6-7294-11e5-9ab2-6fbb0a9791f2.png">

**Comment by asturur** [comment] 2015-10-14 11:38
Dynamic path support is not in yet.
You can see a similar question that has been solved cloning the path.

https://github.com/kangax/fabric.js/issues/2520

**Comment by davidagee** [comment] 2015-11-12 21:29
I'm working in 1.5.x and had a similar issue, I managed to resolve it without using the clone/destroy/create method above. After updating your Path.path commands array, add the following two lines:

```
            path.pathOffset = null;
            path._setPositionDimensions();
```

Where `path` is your `Path` instance. This is because `_setPositionDimensions` does not update `pathOffset`, it checks for an existing value and uses it if it exists (path.class.js:132).

Would it be a good idea to add this into the `.set` logic? That way, you would be able to dynamically adjust the path by using `.set('path', updatedPath)`.

**Comment by asturur** [comment] 2017-09-03 14:05
duplicate of #1025

**Closed by asturur** 2017-09-03 14:05 UTC
Labels: possible_feature
