### ISSUE TITLE
IText objects are not at the proper place when I loaded back from the DB.

### ISSUE THREAD

**Issue by kuldipem** [kangax/fabric.js#2527] opened 2015-10-06 19:16 UTC
HI, I  want to load serialized object from the DB and want to edit. But When I load back to Canvas, IText objects are not at the proper places, but When I click on the Canvas than all IText objects are moved at the proper places. 

```
{"objects":[{"type":"image","originX":"left","originY":"top","left":0,"top":0,"width":400,"height":480,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"src":"http://www.pixbuddy.net/wp-content/uploads/2015/10/Sky_Grass_1920x1200_cool_twitter_backgrounds.jpg","filters":[],"crossOrigin":"","alignX":"none","alignY":"none","meetOrSlice":"meet"},{"type":"image","originX":"left","originY":"top","left":310,"top":385.5,"width":150,"height":159,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":0.5,"scaleY":0.5,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"src":"http://www.pixbuddy.net/wp-content/uploads/users/1/thumb/b444c0cefbade2058a0b015dbb98212e-.png","filters":[],"crossOrigin":"","alignX":"none","alignY":"none","meetOrSlice":"meet"},{"type":"group","originX":"left","originY":"top","left":209.95,"top":579.95,"width":487.39,"height":487.39,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":0.12,"scaleY":0.12,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"objects":[{"type":"path","originX":"left","originY":"top","left":-243.7,"top":-243.7,"width":486.39,"height":486.39,"fill":"#010002","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":[1,0,0,1,0,0],"path":[["M",243.196,0],["C",108.891,0,0,108.891,0,243.196],["s",108.891,243.196,243.196,243.196],["s",243.196,-108.891,243.196,-243.196],["C",486.392,108.861,377.501,0,243.196,0],["z"],["M",306.062,243.165],["l",-39.854,0.03],["l",-0.03,145.917],["h",-54.689],["V",243.196],["H",175.01],["v",-50.281],["l",36.479,-0.03],["l",-0.061,-29.609],["c",0,-41.039,11.126,-65.997,59.431,-65.997],["h",40.249],["v",50.311],["h",-25.171],["c",-18.817,0,-19.729,7.022,-19.729,20.124],["l",-0.061,25.171],["h",45.234],["L",306.062,243.165],["z"]],"pathOffset":{"x":243.196,"y":243.196}}]},{"type":"group","originX":"left","originY":"top","left":10.45,"top":7.04,"width":487.39,"height":487.39,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":0.12,"scaleY":0.12,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"ikanvas":{"name":"icon","multicolor":true,"element":true},"objects":[{"type":"path","originX":"left","originY":"top","left":-243.7,"top":-243.7,"width":486.39,"height":486.39,"fill":"rgb(100, 128, 217)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":[1,0,0,1,0,0],"path":[["M",243.196,0],["C",108.891,0,0,108.891,0,243.196],["s",108.891,243.196,243.196,243.196],["s",243.196,-108.891,243.196,-243.196],["C",486.392,108.861,377.501,0,243.196,0],["z"],["M",306.062,243.165],["l",-39.854,0.03],["l",-0.03,145.917],["h",-54.689],["V",243.196],["H",175.01],["v",-50.281],["l",36.479,-0.03],["l",-0.061,-29.609],["c",0,-41.039,11.126,-65.997,59.431,-65.997],["h",40.249],["v",50.311],["h",-25.171],["c",-18.817,0,-19.729,7.022,-19.729,20.124],["l",-0.061,25.171],["h",45.234],["L",306.062,243.165],["z"]],"pathOffset":{"x":243.196,"y":243.196}}]},{"type":"group","originX":"left","originY":"top","left":334,"top":3,"width":50.65,"height":50.65,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1.19,"scaleY":1.19,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"ikanvas":{"name":"line","multicolor":true,"element":true},"objects":[{"type":"path","originX":"left","originY":"top","left":-25.33,"top":-25.33,"width":49.65,"height":49.65,"fill":"rgb(21, 84, 236)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":[1,0,0,1,0,0],"path":[["M",24.826,0],["C",11.137,0,0,11.137,0,24.826],["c",0,13.688,11.137,24.826,24.826,24.826],["c",13.688,0,24.826,-11.138,24.826,-24.826],["C",49.652,11.137,38.516,0,24.826,0],["z"],["M",35.901,19.144],["c",0.011,0.246,0.017,0.494,0.017,0.742],["c",0,7.551,-5.746,16.255,-16.259,16.255],["c",-3.227,0,-6.231,-0.943,-8.759,-2.565],["c",0.447,0.053,0.902,0.08,1.363,0.08],["c",2.678,0,5.141,-0.914,7.097,-2.446],["c",-2.5,-0.046,-4.611,-1.698,-5.338,-3.969],["c",0.348,0.066,0.707,0.103,1.074,0.103],["c",0.521,0,1.027,-0.068,1.506,-0.199],["c",-2.614,-0.524,-4.583,-2.833,-4.583,-5.603],["c",0,-0.024,0,-0.049,0.001,-0.072],["c",0.77,0.427,1.651,0.685,2.587,0.714],["c",-1.532,-1.023,-2.541,-2.773,-2.541,-4.755],["c",0,-1.048,0.281,-2.03,0.773,-2.874],["c",2.817,3.458,7.029,5.732,11.777,5.972],["c",-0.098,-0.419,-0.147,-0.854,-0.147,-1.303],["c",0,-3.155,2.558,-5.714,5.713,-5.714],["c",1.644,0,3.127,0.694,4.171,1.804],["c",1.303,-0.256,2.523,-0.73,3.63,-1.387],["c",-0.43,1.335,-1.333,2.454,-2.516,3.162],["c",1.157,-0.138,2.261,-0.444,3.282,-0.899],["C",37.987,17.334,37.018,18.341,35.901,19.144],["z"]],"pathOffset":{"x":24.826,"y":24.826}}]},{"type":"i-text","originX":"left","originY":"top","left":103.5,"top":100,"width":196,"height":52.43,"fill":"rgb(0, 28, 170)","stroke":"#8ae234","strokeWidth":2,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":null,"fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"text":"Jay Jalaram","fontSize":40,"fontWeight":"normal","fontFamily":"Lobster","fontStyle":"","lineHeight":1.16,"textDecoration":"","textAlign":"center","textBackgroundColor":"","styles":{"0":{"1":{},"2":{},"3":{},"4":{},"5":{},"6":{},"7":{},"8":{},"9":{},"10":{"fontFamily":"Lobster","fontSize":40,"fontWeight":"normal","fontStyle":""},"11":{"fill":"rgb(76, 205, 90)","backgroundColor":null}}}}],"background":""}
``` 
I  have tested upon serialized object into the kitchensink through JSON.

**Comment by kuldipem** [comment] 2015-10-06 19:17
Is anything that should I care before I serialize or de-serialize object ?

**Comment by asturur** [comment] 2015-10-07 14:37
if i do a normal JSON save and LOAD from kitchensink, with text elements i do not see any defect.

**Comment by kuldipem** [comment] 2015-10-07 14:49
I also do same thing but with iText objects, you can past  above  JSON to kitechen-sink.

**Comment by kangax** [comment] 2015-10-11 15:34
I'm closing until we have reproducible test case (since it works in kitchensink with itext objects)

**Closed by kangax** 2015-10-11 15:34 UTC
