### ISSUE TITLE
Enable full viewport handling including rotation

### ISSUE THREAD

**Issue by virror** [kangax/fabric.js#3701] opened 2017-02-16 18:46 UTC
## Version
1.7.4

## Test Case
https://jsfiddle.net/Lx26eatv/5/

## Steps to reproduce
Run fiddle with and without the zoom (line 36)

## Expected Behavior
With zoom:
Canvas to be rotated 80 degrees and zoomed to twice it size.
Selection to work as expected (single and multi)

Without zoom:
Canvas to be rotated 80 degrees without distortions.
Selection to work as expected (single and multi)

## Actual Behavior
With zoom:
Canvas is not rotated properly.
Selection does not work as expected (single and multi)

Without zoom:
Rotation is correct, but the shapes are very distorted.
Selection does not work as expected (single and multi)

**Comment by virror** [comment] 2017-02-16 18:48
Here is a solution that seems to work for the zoom + TransforMatrix issue:
Fabric.Canvas.prototype.getZoom = () ->
		vpt = @viewportTransform
		Math.sqrt vpt[0] * vpt[0] + vpt[1] * vpt[1]

	Fabric.Canvas.prototype.zoomToPoint = (point, value) ->
		point = fabric.util.transformPoint point, fabric.util.invertTransform @viewportTransform

		translate = [1, 0, 0, 1, point.x, point.y]
		translateInv = [1, 0, 0, 1, -point.x, -point.y]

		scale = value / @getZoom()
		scale = [scale, 0, 0, scale, 0, 0]

		vpt = @viewportTransform.slice 0
		vpt = fabric.util.multiplyTransformMatrices vpt, translate
		vpt = fabric.util.multiplyTransformMatrices vpt, scale
		vpt = fabric.util.multiplyTransformMatrices vpt, translateInv

		@setViewportTransform vpt

The issues with distortion and selection still persists though.

**Comment by asturur** [comment] 2017-02-16 18:52
Hello Victor.
The canvas can be zoomed and translated.
Not rotated.

All the fabric library is not ready to support that.

**Comment by virror** [comment] 2017-02-16 18:57
Now this is very strange.
We are using a slightly older version in our project, but the fiddle is using the latest and are showing issues.
Tried upgrading our project now and it works perfectly (with the fix i posted for the zoom).
Both selection, zoom and no distortion seems to work flawlessly with the exact same rotation code.
Hmm...

Well, consider adding the code for zoom and you are on a good way of having it supported : )

**Comment by asturur** [comment] 2017-02-16 19:01
probably can be done with general matrix logic, there are open questions about how the control boxes should handle and all the stuff, other than also the pointer events would need some logic maybe.
Every time i can i move the code to general matrix and inverseMatrix operations so that everything get supported easier.

**Comment by virror** [comment] 2017-02-16 19:31
Most stuff seems to work fine in my project now, just have to find some workaround for selections. When rotated, it works to select, but its very restrictive where you can click, just a small part of the object seem valid, also the rotation widget is upside-down : )

**Comment by Vecxinnt** [comment] 2017-04-10 13:58
@virror did you find a workaround for selections?

**Comment by virror** [comment] 2017-04-10 14:15
Yeah, i just had to remake the selection from code.

**Comment by Vecxinnt** [comment] 2017-04-10 14:53
No less! x)

**Comment by asturur** [comment] 2017-09-03 13:32
duplicate of #2382

**Closed by asturur** 2017-09-03 13:32 UTC
Labels: possible_feature

**Comment by yadue** [comment] 2017-12-14 14:22
@virror are you able to share part of your code related to selection?

**Comment by virror** [comment] 2017-12-14 16:18
Sorry, im not able to share any custom code from this project : /
