### ISSUE TITLE
Unable to draw multi-select box from over objects with '*.selectable = false', only over canvas

### ISSUE THREAD

**Issue by quantumjockey** [kangax/fabric.js#2961] opened 2016-05-09 20:36 UTC
This hasn't changed from older versions but wanted to point it out for discussion. If an object has '*selectable=false' set, multi-select boxes cannot be drawn from the area within the non-selectable object when 'canvas.selection=true'. However, multi-select boxes are drawn when originating a mouse-down + drag movement from the canvas itself as expected.

Here's a JSFiddle demonstrating this behavior:
https://jsfiddle.net/quantumjockey/b7g2jprj/1/

When mouse-down + dragging from the canvas itself, the multi-select box shows with no issue. However, when mouse-down + dragging from inside the blue box, nothing happens. There is a work-around which I'll make a fiddle for momentarily, which worked well for resolving this issue in 1.6.0-rc1 but breaks in 1.6.1 :(

At any rate, is it not intuitive that the multi-select box should appear on drag over non-selectable objects within a canvas having 'selection = true'? The main use case I have for this is to place objects within a scene as static background elements for other (movable) objects.

**Comment by asturur** [comment] 2016-05-09 20:50
duplicate of #1506.

As we said there, you should use the "evented:false".
If evented:false is not good for you, put a +1 in the older thread. Soon or later we will fix that.

**Closed by asturur** 2016-05-09 20:50 UTC
