### ISSUE TITLE
SVG - tspan with rotation issue

### ISSUE THREAD

**Issue by JugnuPathak** [kangax/fabric.js#3018] opened 2016-05-30 12:45 UTC
## Version
1.6.2

## Test Case
[https://jsfiddle.net/jugnu_pathak/3wer3o97/]

I have one svg in which some text element having rotation applied using rotation attribute on tspan. 
As shown below: 

`  <g transform="matrix(0.889837 0 0 0.999316 -1843.63 -4855.45)">
   <text x="3311" y="8601" id="7" class="fil1 fnt0"><tspan rotate="308">G</tspan></text>
   <text x="4135" y="7552" id="7" class="fil1 fnt0"><tspan rotate="330">O</tspan></text>
   <text x="5321" y="6872" id="7" class="fil1 fnt0"><tspan rotate="345">R</tspan></text>
   <text x="6593" y="6554" id="7" class="fil1 fnt0"><tspan rotate="355">I</tspan></text>
   <text x="7336" y="6471" id="7" class="fil1 fnt0"><tspan rotate="3">L</tspan></text>
   <text x="8646" y="6551" id="7" class="fil1 fnt0"><tspan rotate="15">L</tspan></text>
   <text x="9916" y="6894" id="7" class="fil1 fnt0"><tspan rotate="30">A</tspan></text>
   <text x="11078" y="7557" id="7" class="fil1 fnt0"><tspan rotate="52">S</tspan></text>
  </g>`

When this object is loaded on canvas using **loadSVGFromURL/loadSVGFromString** rotation is not applied properly as you can see in fiddle.

**Comment by asturur** [comment] 2016-05-30 12:52
tspan are not supported, nor is rotation with them.
duplicate of #1280

**Comment by JugnuPathak** [comment] 2016-05-30 12:52
any alternative to make it working??

**Closed by asturur** 2016-05-30 12:52 UTC

**Comment by asturur** [comment] 2016-05-30 12:54
well, as of now you can make a text for each tspan and try to apply transform="rotate(x)" over them directly. I do not know if is the same rotate.
