### ISSUE TITLE
SVG loading issue without grouping

### ISSUE THREAD

**Issue by sarath-prohaktiv** [kangax/fabric.js#2248] opened 2015-06-01 11:18 UTC
Please refer screen shot for the issue
![image](https://cloud.githubusercontent.com/assets/7422434/7911655/dc83218a-087d-11e5-85cd-58d1eca95fa8.png)

Thanks
Sarath

**Comment by sarath-prohaktiv** [comment] 2015-06-01 11:19
In the above screen shot line is selected but selection is away from actual object

**Comment by asturur** [comment] 2015-06-01 11:27
duplicate of #1520.
Svg created with fabricjs are not intended for loading back, if loadedback use LOAD and not load without grouping.
If you need to save and restore canvas please use toObject and fromObject ( or JSON )

**Closed by asturur** 2015-06-01 11:27 UTC

**Comment by sarath-prohaktiv** [comment] 2015-06-01 11:41
Got your point. But it is still applicable to SVG created from illustrator

**Comment by asturur** [comment] 2015-06-01 11:56
Yes, as per issue #1520 the transformatrix is not supported in any single object outside pathgroup.
A known issue we are solving.
