### ISSUE TITLE
Stroke shows up in non-italicized position for certain fonts in Firefox 49.0.1

### ISSUE THREAD

**Issue by Aubron** [kangax/fabric.js#3357] opened 2016-10-19 17:52 UTC
## Version

1.6.5
## Test Case

http://fabricjs.com/kitchensink
## Steps to reproduce

1) Use firefox 49.0.1
2) Change font to Impact, or Engagement (other fonts have been shown to also do this, don't have a connecting factor yet)
3) Italicize font
4) Add stroke
## Expected Behavior

Stroke follows the italicized font
## Actual Behavior

Stroke shows up in non-italicized position.

![image](https://cloud.githubusercontent.com/assets/1171076/19530756/233e7d40-9603-11e6-836b-b76b17b968d7.png)

**Comment by asturur** [comment] 2016-10-19 22:11
Cannot reprodue on win10 VM, firefox 49.0.1.

**Comment by Aubron** [comment] 2016-10-19 22:24
I just went through and reproduced it on another physical win10 machine, as well as a few browserstack instances to be sure it's not something dumb and localized for computers on our network. Looks like its not a present in FF 50 beta, so maybe just FF's problem?

**Comment by asturur** [comment] 2016-10-19 22:32
i guess. If you have access to firefox 50, can you check this:
https://github.com/kangax/fabric.js/issues/3334

**Comment by asturur** [comment] 2016-10-24 10:51
can you try again on firefox 49.0.2 and in case close it? i cannot reproduce it, so i could end up closing it anyway.

**Comment by Aubron** [comment] 2016-10-24 13:36
Still happening on 49.0.2 - http://i.imgur.com/FxwjCMM.png

**Comment by ncou** [comment] 2016-11-22 23:02
I can reproduce the bug in the FF 49.0.1, but after the update to FF 50.0, the bug is no more present.

**Comment by asturur** [comment] 2016-11-22 23:13
firefox 49 come bugged in canvas text.
i still canno reproduce but being an isolated case i   can just let go.
i would like to reproduce anyway, can you give me instruction?

**Closed by asturur** 2016-11-22 23:13 UTC
Labels: browser_bug
