### ISSUE TITLE
Using one ui element for scale and rotate objects

### ISSUE THREAD

**Issue by Kureev** [kangax/fabric.js#1231] opened 2014-03-20 12:34 UTC
> Since version 1.0 Fabric uses alternative UI by default — objects can no longer be scaled and rotated at the same time

I still need to use one UI element(for example, one of the bounding box corners) for resizing and scale object. Does it possible to make smth like this without heavy hacks?

**Comment by asturur** [comment] 2016-05-01 01:14
duplicate of #623

**Closed by asturur** 2016-05-01 01:14 UTC
Labels: possible_feature
