### ISSUE TITLE
Fix width of textbox with fontstyle and rescale

### ISSUE THREAD

**Issue by mbaudry** [kangax/fabric.js#3700] opened 2017-02-16 16:20 UTC
Hi guys !

I would like to speak about a feature like this one: https://github.com/kangax/fabric.js/issues/2376.
My case is that I would like to fix the width of an IText.

But the text comes from HTML, so I need to parse `strong`, `em` and `br` to build an IText with the correct fonts, and it is on only one line, so I need to split it in multiple lines to fix a width.

Here is my code to transform HTML tags in fabric js font (bold and italic):
```
parseHtml(textBox) {
        const regExpStr = '<%s>(.*?)</%s>';
        const config = {strong: 'bold', em: 'italic'};

        for (const style in config) {
            // need this check for jshint
            if (Object.prototype.hasOwnProperty.call(config, style)) {
                const regExp = new RegExp(regExpStr.replace('%s', style).replace('%s', style), 'g');
                let result;
                while ((result = regExp.exec(textBox.text)) !== null) {
                    const str = result[1],
                        font = style === 'strong' ? {fontWeight: 'bold'} : {fontStyle: 'italic'};
                    textBox.setSelectionStart(result.index + style.length + 2);
                    textBox.setSelectionEnd(result.index + style.length + 2 + str.length);
                    textBox.setSelectionStyles(font);
                }
                this._removeTag(textBox, style);
            }
        }
        return textBox;
    }
```

The main problem (which differentiates this ticket from others already opened on this subject) is that when I split the text in different lines, all the fonts are removed... I saw on Textbox that there is a styles object which permits to define all the font on each char, for each line. But the Textbox can't solve my problem because I juste want to fix the width of  a text, then I would like to rescale the box like an IText.

It's like an hybrid between a textbox (which manage font and multi line), and an IText which permits to rescale the box.

**Comment by asturur** [comment] 2017-02-21 12:19
duplicate of #3525

**Closed by asturur** 2017-02-21 12:19 UTC

**Comment by mbaudry** [comment] 2017-02-21 13:07
Why is it a duplicate of https://github.com/kangax/fabric.js/issues/3525 ?? I do not understand...

**Comment by asturur** [comment] 2017-02-21 13:10
is the same problem, scalable textbox.

**Comment by mbaudry** [comment] 2017-02-21 13:25
ok, is it a problem if we parse html tags in it (bold, italic, etc) ?

**Comment by asturur** [comment] 2017-02-21 13:29
html tags its your own code/app and is not a fabric feature

**Comment by mbaudry** [comment] 2017-02-21 13:43
ok, never mind, parse html is just done using `setSelectionStyles` on text so I suppose it will not cause problem for scalable textbox. Thanks !

**Comment by rlebosse** [comment] 2017-06-20 15:14
@asturur 

I'm encountering the same issue, and seeing that you closed this one, I was wondering if something has been set up to scale an IText box.

Is there an option I can use to do so? I would like to fix the maximum width of a very large text.

**Comment by asturur** [comment] 2017-06-20 15:20
no i reopened the linked issue, since it has not be fixed in the text rewrite. is in the 2.0 checklist anyway
