### ISSUE TITLE
Gradient problem with gradientTransform

### ISSUE THREAD

**Issue by neopheus** [kangax/fabric.js#4264] opened 2017-08-31 07:59 UTC
## Version
2.0.0-beta6

## Test Case
With problem :
https://jsfiddle.net/ecvctazk/99/
Without : https://www.mwrecyclage.fr/img/179-v2-noscale.svg

## Problem
Fabricjs does not parse the coordinates and angles of the gradients correctly with gradientTransform

WIthout gradientTransform : https://jsfiddle.net/ecvctazk/100/
https://www.mwrecyclage.fr/img/179-v2-notransform.svg

**Comment by asturur** [comment] 2017-08-31 08:09
is a duplicate of #4017 and is hard to fix for now.

simply canvas can t do whatever svg does.

i added a very similar svg in import tests here

http://fabricjs.com/test/svg_import/

the test 180 shows the exact problem.

**Closed by asturur** 2017-08-31 08:09 UTC
