### ISSUE TITLE
Event "text:editing:exited" not firing after loadFromJson 

### ISSUE THREAD

**Issue by bodeva** [kangax/fabric.js#3557] opened 2016-12-20 17:12 UTC
Sorry for my English ...

After add a new Textbox or IText in new Canvas and modify it, text:editing:exited event was fired.
But if I load a canvas from loadFromJson and try to modify an existing Textbox or IText, text:editing:exited event is not firing. 

Other event is firing (eg. object:scaling) 

No error trace in log

## Version
1.7.2

## Steps to reproduce
1° loadFromJson
2° Edit a Textbox or IText
3° Exit from the Textbox or IText

## Expected Behavior

Event text:editing:exited Fired

## Actual Behavior

Event text:editing:exited not Fired

**Comment by asturur** [comment] 2016-12-26 19:03
Tried to replicate but cannot.
In fabricjs.com/kitchensink, once i loaded from json some itext the event fires normally.
Add a failing fiddle or i will close the issue as non reproducible

**Closed** 2016-12-28 08:30 UTC
Labels: needs_confirmation, will be closed for missing / nonclear / not failing fiddle

**Comment by asturur** [comment] 2020-04-19 10:14
The issue was closed, because it wasn't possible to reproduce the bug. If you can reproduce the bug, please create a fiddle where with a minimal case the problem can be reproduced.

**Comment by arvindkumarpal** [comment] 2021-03-10 09:16
HI, issue is still occuring. Please help me in fix this.
Can be check here
http://jsfiddle.net/arvindpal/8x15Leas/
