### ISSUE TITLE
Clipping masks in svgs

### ISSUE THREAD

**Issue by idlethumbs** [kangax/fabric.js#2413] opened 2015-08-12 12:18 UTC
Hia, we can't seem to get SVG's created in illustrator that use clipping masks to appear correctly using this plugin. Sorry if this has been asked before.

The two paths just display as if it is a compound shape.

**Comment by asturur** [comment] 2015-08-12 12:20
It has been asked before indeed.
Provide SVG anyway we may use for future fixing.
duplicate of #1444.
Please paste there the SVG if possible

**Closed by asturur** 2015-08-12 12:20 UTC
