### ISSUE TITLE
when rendering corners is not taken into account the property transform

### ISSUE THREAD

**Issue by ffff4** [kangax/fabric.js#3694] opened 2017-02-15 04:26 UTC
Hello! In your demo http://fabricjs.com/kitchensink in tab LoadSVG I inserted the code c.txt. I clicked on the button "Load without grouping". The position of the corners does not coincide with the position of the rectangle. Because when rendering corners is not taken into account the property transform="translate(168.5 202.5) rotate(43)"

[c.txt](https://github.com/kangax/fabric.js/files/776053/c.txt)

**Comment by ffff4** [comment] 2017-02-15 04:29
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="1480" height="1000" viewBox="0 0 1480 1000" xml:space="preserve">
<desc>Created with Fabric.js 1.7.3</desc>
<defs>
</defs>
<rect x="-25" y="-25" rx="0" ry="0" width="50" height="50" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(192,216,12); fill-rule: nonzero; opacity: 0.8;" transform="translate(168.5 202.5) rotate(43)"/>
</svg>

**Comment by asturur** [comment] 2017-02-15 18:09
duplicate of #1520

**Closed by asturur** 2017-02-15 18:09 UTC
