### ISSUE TITLE
Rotation controll can be and corner

### ISSUE THREAD

**Issue by dmitrirussu** [kangax/fabric.js#1539] opened 2014-07-28 08:04 UTC
Sorry, I want to use [tr] instead of [mtr]. I want to do disable of [mtr] and to be posible to choose [tr] or [mr] after that to be posisble to put a image as rotation controller, or to be default simple circle. 
Can be improved some thing?

**Comment by jeffkillian** [comment] 2015-08-07 15:30
I'm not sure where to comment this, but I'm encountering this issue as well, and would love to see corner rotation implemented.

**Comment by seekshiva** [comment] 2016-06-15 07:14
I would love to have this feature too!

**Comment by asturur** [comment] 2016-06-15 07:41
so put a +1 here: https://github.com/kangax/fabric.js/issues/1947

**Comment by asturur** [comment] 2016-06-15 07:41
duplicate of #1947

**Closed by asturur** 2016-06-15 07:41 UTC
Labels: possible_feature
