### ISSUE TITLE
free drawing edge + touchscreen

### ISSUE THREAD

**Issue by alfredwesterveld** [kangax/fabric.js#2879] opened 2016-04-11 12:47 UTC
When using Microsoft surface(tablet) using default edge browser(which is a piece of crap) I can not do free drawing properly. 

```
edition: Windows 10 home
version: 1511
Build OS: 10586.218
```

When I installed google chrome on it works as it should.

Below also a picture of what is happening. You only see dots when drawing:

![edge](https://cloud.githubusercontent.com/assets/7066/14883024/261c4664-0d3c-11e6-8d29-e9e5b872507f.jpeg)
## Version

1.6.0
## Test Case

**http://fabricjs.com/freedrawing**
## Steps to reproduce
1. Use free drawing mode on edge
## Expected Behavior

You can draw
## Actual Behavior

only get points but no (complete) drawing

**Comment by asturur** [comment] 2016-04-25 05:06
it works as expected for me. Please add more details, screenshot, information on hardware configuration and i will reopen the issue.

**Comment by alfredwesterveld** [comment] 2016-04-28 10:25
@asturur thanks for the quick response. I have added some more information to bug and also a screenshot from what is happening on that (piece of crap) tablet.

**Comment by asturur** [comment] 2016-04-28 10:30
Can you please find a way to connect a mouse to that tablet and try? it **COULD** be something about how edge use touchsupport and on how we interact with it.

Di you try with gestures module on and off?

**Comment by asturur** [comment] 2016-05-08 19:07
I can confirm this is an issue with edge and touch. with mouse is going, with finger not. Something to do with gestures. I will not fix it easy without a windows 10 device and touch.
On a windows 10 phone it works normally

**Comment by DennisSmolek** [comment] 2016-06-09 13:59
The issue is how IE/Edge/Windows handles touches Vs chrome. 

Edge uses the pointer events while chrome translates them to act more like traditional mouse events.

We run into the same issue with tracking clicks, taps, touches, drags, etc. and only noticed when we switched to using Surface Pro's for laptops.

**Comment by asturur** [comment] 2016-06-09 15:03
i took a win 10 touch device.
if you go to edge and says that you want touch enabled, it will works. It is disabled by default.
I seriously do not know if handle this as a bug or just close it.
I'm ordering a win 10 touch device just to fiddle with it.

**Comment by alfredwesterveld** [comment] 2016-06-09 21:08
Quick response from phone. Playground worked for me last time i checked so
thanks☺. I hope tomorrow i can add screencast or something

**Comment by mvzen** [comment] 2016-07-21 09:45
I'm having the same problem with a Surface Pro (touchscreen) and Edge.

Any news? Thanks :)

**Comment by asturur** [comment] 2016-07-21 09:57
Did  you go to edge options and enable the touch events?
those events are disabled by default

**Comment by mvzen** [comment] 2016-07-21 10:33
OK. I didn't understand the previous message "says that you want touch disabled", sorry. 

For future readers, it is a flag that must be activated via about:flags (by default it is set to *Always disable touch events*). Which just seems crazy for a touch-centric device like a Windows Surface. 

This is not good news for me though, because I cannot expect my clients / users to go clicking around in the experimental flags of their browser. But I understand this is not your fault.

**Comment by mvzen** [comment] 2016-07-21 10:37
Hmmmm.

Why does jQuery UI Draggable demo work with the flag off / disabled ? AFAIK that uses touch events, too. Dragging the box around on their demo page is buttery smooth and perfectly follows my finger.

Could something be done [to fabricjs] to do whatever jQuery is doing to allow touch events ?

**Comment by asturur** [comment] 2016-07-21 11:11
it depends on what jQuery is doing. But did you try to enable it?

**Comment by paulcredmond** [comment] 2016-09-20 10:37
Any more updates or info on this? I'm having the exact same issue.

**Comment by asturur** [comment] 2016-09-20 11:01
I do not have any win 10 touch device.
Did you go to edge options and enable the touch events?
those events are disabled by default

**Comment by asturur** [comment] 2017-04-23 09:52
to be handled in #3869

**Closed by asturur** 2017-04-23 09:52 UTC
