### ISSUE TITLE
Control not selectable with controlsAboveOverlay: true

### ISSUE THREAD

**Issue by saadqbal** [kangax/fabric.js#3167] opened 2016-08-15 16:03 UTC
When you set the controlsAboveOverlay: true and the control are overlaying an object, they are not selectable.

[https://jsfiddle.net/ecvctazk/39/](https://jsfiddle.net/ecvctazk/39/)

Select the red box and try to resize it from the right control above the black one. It won't resize. It will select the black box instead.

**Comment by neopheus** [comment] 2016-08-15 19:55
it's ok : https://github.com/kangax/fabric.js/pull/3165

**Comment by asturur** [comment] 2016-08-18 05:47
duplicate of #3095

**Closed by asturur** 2016-08-18 05:47 UTC
