### ISSUE TITLE
On the website, animation option is missing in custom build

### ISSUE THREAD

**Issue by louiscloutierdakis** [kangax/fabric.js#2560] opened 2015-10-16 17:24 UTC
For a custom build on the website: http://fabricjs.com/build/ we don't have the option animation. If I select all the option and create a build, the code inside doesn't contain the animate functions.

Can you add the option animation in custom build?

**Comment by kangax** [comment] 2015-10-16 18:47
Duplicate of #1262

**Closed by kangax** 2015-10-16 18:47 UTC
