### ISSUE TITLE
object:moving renders entire canvas

### ISSUE THREAD

**Issue by ghost** [kangax/fabric.js#907] opened 2013-10-16 12:13 UTC
Hi,

When an object is dragged across the canvas after the events have fired there is a call to render all on the canvas:

https://github.com/kangax/fabric.js/blob/master/src/mixins/canvas_events.mixin.js#L524

The issue I have with this is that on a busy canvas, lets say around 110 objects, when I try and drag the object using an iPad, the performance is terrible. Almost unusable. When I scale down the number of objects the performance comes back.

Most of the objects on the canvas have no interactivity they are there for context and decoration. Only a small number of objects would actually need to move. Is there is a way to single those items out during rendering or can I specify that the canvas should only render the current moving object?

**Comment by asturur** [comment] 2016-04-28 23:20
duplicate of #1470

**Closed by asturur** 2016-04-28 23:20 UTC
Labels: possible_feature
