### ISSUE TITLE
Issue on change strokeWidth on the fly

### ISSUE THREAD

**Issue by mbaudry** [kangax/fabric.js#3556] opened 2016-12-20 10:45 UTC
## Version
1.7.2

## Test Case
https://jsfiddle.net/jf03bbc3/7/

## Steps to reproduce
select the rectangle

## Expected Behavior
the strokeWidth must be added to the first element of the group and be visible

## Actual Behavior
we do not see the strokeWidth until we resize the rectangle

Thanks !

**Comment by asturur** [comment] 2016-12-20 11:09
http://fabricjs.com/fabric-object-caching

as soon as i will update this page with better descriptions for groups also, i ll point you there and close the issue.

Give it a read, your case is covered but not really explicitly.
I will update asap.

**Comment by mbaudry** [comment] 2016-12-20 11:11
Ok ! Thank you so much

**Comment by asturur** [comment] 2016-12-22 08:28
Ok i addressed the document, anyway the problem is weird and i think i will fix it.
As for now you do not any other thing to do rather than enabling statefullCache to true for the group, but i will fix it in 1.7.3

**Comment by mbaudry** [comment] 2016-12-22 08:41
Yes I did it to solve my problem for the moment. I also noticed that I have much more blur on my objects on zoom in my canvas, even if I set noScaleCache to false.

**Comment by asturur** [comment] 2016-12-22 08:51
that is strange. Can you post a fiddle? that may be image positioning that i notice less because i have a retina screen.
I checked the code anyway and to me looks right as it is. The cache should be invalidated.

**Comment by asturur** [comment] 2016-12-22 08:56
Got the error of the setting true.
I fixed it i push it now.
Please open a separate ticket for the blurriness, i would like to understand it.

**Closed by asturur** 2016-12-22 08:56 UTC

**Comment by asturur** [comment] 2016-12-22 08:59
1.7.3 won't be released soon, please check the fix and backport if needed.

https://github.com/kangax/fabric.js/pull/3564/files
