### ISSUE TITLE
fabric.createCanvasForNode replacement?

### ISSUE THREAD

**Issue by karcass** [kangax/fabric.js#4586] opened 2017-12-28 02:15 UTC
I am upgrading my project from 1.7.9 to 2.0.0 (currently have rc4).  My server-side piece is unhappy because fabric.createCanvasForNode is gone.  What's the replacement?

**Comment by asturur** [comment] 2017-12-29 08:53
So more or less all the specific node-code has been removed.
You can use just `new fabric.Canvas(null, {width: ..., height: ...})` or `new fabric.StaticCanvas(null, {width: ..., height: ...})`

**Comment by asturur** [comment] 2017-12-29 08:59
Also there is an utility `fabric.util.getNodeCanvas`  that passed an element let you access its own node canvas instance.

Take care that there are no news for node user in fabric 2.0  Text improvements are likely not improving node-canvas text problems, filtering may be a bit faster, and there is an api normalization.
That's all.

I suggest you to move to 2.0 anyway.

For me is important to have feedback from node users about rendering differences and difficulties since i m not a great fabric-node user at all.

**Comment by asturur** [comment] 2017-12-29 09:03
Please close this issue when you are done.

**Comment by karcass** [comment] 2018-01-06 17:42
Will do.  Sorry for slow response, have been stomped by influenza.

**Comment by karcass** [comment] 2018-01-06 18:34
The crucial parameter for me was passing 'pdf' so that I can generate PDFs:
`const canvas = fabric.createCanvasForNode(3000, 2000, 'pdf')
...
fs.writeFile(outfile, canvas.nodeCanvas.toBuffer())`

I tried your simple suggestion of replacing the call with a `new Canvas`, but I need to figure out how that 'pdf' parameter gets through to node-canvas correctly.

**Comment by asturur** [comment] 2018-01-06 22:20
well with fabricjs you can't.

I leveraged everything to jsdom to have easier life, but the problem is that jsdom hides nodecanvas completely.

let me see if we can swap the jsdom implementation after a canvas is created.

**Comment by karcass** [comment] 2018-01-06 23:09
I pasted the old body of `createCanvasForNode` into my app, and that kind of halfway works, except for _renderFill:

```
TypeError: Image or Canvas expected
    at TypeError (native)
    at klass._renderFill (/home/max/drafty/node_modules/fabric/dist/fabric.js:19131:28)
    at klass._renderPaintInOrder (/home/max/drafty/node_modules/fabric/dist/fabric.js:13155:14)
    at klass._render (/home/max/drafty/node_modules/fabric/dist/fabric.js:19124:12)
    at klass.drawObject (/home/max/drafty/node_modules/fabric/dist/fabric.js:12941:12)
    at klass.render (/home/max/drafty/node_modules/fabric/dist/fabric.js:12877:14)
    at klass.drawObject (/home/max/drafty/node_modules/fabric/dist/fabric.js:18231:26)
    at klass.render (/home/max/drafty/node_modules/fabric/dist/fabric.js:12877:14)
    at klass.callSuper (/home/max/drafty/node_modules/fabric/dist/fabric.js:1920:22)
    at klass.render (/home/max/drafty/node_modules/fabric/dist/fabric.js:18175:12)
```

**Comment by asturur** [comment] 2018-01-06 23:15
and filters, filters will not work.
This is why i removed it.

As fabric rendering gets more complex we need to create use and trash canvas layers. This requires some uniform way to do it or things breaks.

can you paste here fabric.util.getNodeCanvas function body?

i m still on holiday and i have little access to the code

**Comment by karcass** [comment] 2018-01-06 23:22
If I can't render PDFs, I don't have a product, so that would leave me stuck on the 1.x branch forever.

```
  function getNodeCanvas(element) {
    var impl = fabric.jsdomImplForWrapper(element);
    return impl._canvas || impl._image;
  };
```

**Comment by asturur** [comment] 2018-01-07 00:16
Well pdf support is not a fabricjs feature. sadly.

Also i have no idea what nodecanvas can do with pdf support. can it paint a pdf canvas over another?
i imagine some features are kot of yoir interest but pdf nodecanvas could not work anyway woth fabircjs.

as of now you can do what i do in that function.

instead of returning  _canvas assign it to.your pdf canvas and try to figure out if it works.

create a staticCanvas, then swap for lowerCanvasEl the implememtation with your pdf nodecanvas created with node-canvas directly. (do not use old fabricjs function)

**Comment by karcass** [comment] 2018-01-07 18:13
Okay, I have a workable solution.  I hand-modified my copy of jsdom to always pass that third 'pdf' argument into the constructor.  It's not a generalized solution, and I'll have to re-make that edit if I ever take a new jsdom, but it works.

Also I had to hand-patch your new _renderFill because of that other image-scale bug we went around on:
```
    _renderFill: function(ctx) {
      var w = this.width, h = this.height, sW = w * this._filterScalingX, sH = h * this._filterScalingY,
          x = -w / 2, y = -h / 2, elementToDraw = this._element;
      if (!this.cropX && !this.cropY) { // %%%
        elementToDraw && ctx.drawImage(elementToDraw, // %%%
          x, y, w, h); // %%%
      } else { // %%%
        elementToDraw && ctx.drawImage(elementToDraw,
          this.cropX * this._filterScalingX,
          this.cropY * this._filterScalingY,
          sW,
          sH,
          x, y, w, h);
      } // %%%
    },
```

**Closed** 2018-01-07 18:18 UTC

**Comment by asturur** [comment] 2018-01-07 23:24
the canvas swap idea did not work?

**Comment by karcass** [comment] 2018-01-07 23:30
I didn't bother to try.  I'm satisfied with my solution.  I have enough other work to do porting from 1.x to 2.0.

**Comment by asturur** [comment] 2018-01-07 23:44
does image filter works with all canvases switched to pdf mode?

**Comment by karcass** [comment] 2018-01-08 00:26
I don't know, I don't use image filters.  But I suspect it'll work.  I
think the only difference when passing in the 'pdf' parameter is the
behavior of the `toBuffer()` call.

**Comment by friday** [comment] 2018-03-25 22:00
`canvas.lowerCanvasEl.toDataURL()` worked for me. `lowerCanvasEl.toBuffer()` doesn't exist, and `lowerCanvasEl.toBlob()` seemed to produce an empty blob.

Base64 data urls can be converted to buffers like this:
`Buffer.from(dataUrl.replace(/^data:\w+\/\w+;base64,/, ''), 'base64');`

Thanks @asturur!

**Comment by dhildreth** [comment] 2018-04-13 16:31
Sorry to hijack this, but it does seem somewhat relevant.  In attempting to replace `createCanvasForNode()` with `Canvas()` or `StaticCanvas()`, I'm getting a frustrating error message:

```
app-0 TypeError: fabric.StaticCanvas is not a constructor
app-0     at getCanvas (/var/www/ts-motd/public_html/ts-motd/app.js:30:19)
app-0     at autoloadCallback (/var/www/ts-motd/public_html/ts-motd/app.js:155:26)
app-0     at loadDatabaseCallback (/var/www/ts-motd/public_html/ts-motd/node_modules/lokijs/src/lokijs.js:1273:15)
app-0     at readFileCallback (/var/www/ts-motd/public_html/ts-motd/node_modules/lokijs/src/lokijs.js:1157:11)
app-0     at tryToString (fs.js:455:3)
app-0     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

Before:

`    var _canvas = fabric.createCanvasForNode(1920, 1080)
`

After:

`   var _canvas = new fabric.StaticCanvas(null, {width:1920,height:1080});
`

Same goes for `Canvas()`.  What did I miss?  Running Fabric v2.2.3 (installed using `npm install fabric@2.2.3`).

**Comment by friday** [comment] 2018-04-13 17:07
It really should work. Only you can debug your runtime environment, so you have to find out what's wrong yourself. Make sure you have imported fabric correctly (`const {fabric} = require('fabric')` or `import {fabric} from 'fabric'`) and haven't overloaded it or `fabric.StaticCanvas` anywhere. Check for errors in the npm build and when running the node server. Try to console.log `fabric.version` just to be sure, and also `fabric.StaticCanvas`, `fabric.StaticCanvas.constructor` `fabric.StaticCanvas.toString()`. Also make sure you're running a supported Node version.

**Comment by asturur** [comment] 2018-04-13 18:13
in fabric 2 you should not use special code for creating a canvas

**Comment by dhildreth** [comment] 2018-04-16 15:12
Thanks for the tips.  Good starting points. I'll try to get it figured out then.  What is a supported Node version for 2.2.3?

**Comment by asturur** [comment] 2018-04-16 16:07
4,6,8,9

As 1.7

Next major version ( unplanned yet ) i think i will cut out everything below 8, just to have smaller sets of tests.

**Comment by dhildreth** [comment] 2018-04-16 16:07
Ah, good news... I used `const {fabric} = require('fabric')` as opposed to `var fabric = require('fabric')` and everything just worked.  Thanks!

**Comment by wethk** [comment] 2018-12-13 07:11
![image](https://user-images.githubusercontent.com/12679696/49921577-f28d1480-fee8-11e8-94f2-06c04a76aec2.png)
fabric version: 2.4.5
Canvas version: 1.6.13

but throw Error
![image](https://user-images.githubusercontent.com/12679696/49921635-2ff1a200-fee9-11e8-9e46-a5b20d90d703.png)

i had tried  `new fabric.Canvas()` and `new fabric.StaticCanvas()` but throw the same error

**Comment by asturur** [comment] 2018-12-13 08:38
You probably do not have node-canvas installed.

**Comment by Benibur** [comment] 2019-04-08 05:35
if it can help, I made it work with : `node 10.15.3`, `fabricjs ^2.7.0`, `"jsdom": "^13.2.0"` (jsdom version seems important)
Install node-canvas dependencies - (here for Ubuntu/Debian)[https://github.com/Automattic/node-canvas/wiki/Installation:-Ubuntu-and-other-Debian-based-systems] - before.
