### ISSUE TITLE
tojson fromjson no work

### ISSUE THREAD

**Issue by costa974** [kangax/fabric.js#2429] opened 2015-08-19 20:52 UTC
Im using this svg.
```xml
<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><path d="M74.91 23.6c1.584.04 3.202 1.918 3.19 3.694-.01 1.352-1.877 2.84-3.427 2.732-1.397-.096-2.2-1.324-2.16-3.315.04-1.91.99-3.144 2.397-3.11zm.832 4.327l.187-.277-.33-.034.142.31zm-17.632-1.85c-.085 1.556-2.472 3.926-3.83 3.802-1.764-.165-3.467-1.913-3.46-3.56.005-1.99 1.775-3.727 3.744-3.676 1.708.05 3.625 1.906 3.546 3.434zm-4.56-1.555c.148-.215.3-.43.448-.645-.136.226-.272.453-.407.685-.146.215-.294.43-.435.644.13-.23.26-.458.396-.684zm1.81 2.715c1.336-.565.95-1.46.227-2.902l-.186 2.942c-.548.08-1.097.158-1.645.237.08.18.152.362.232.543.458-.265.916-.543 1.374-.82zm-27.19 9.56c.803-.56 1.408-1.216 2.155-1.477 3.632-1.278 7.297-2.404 11.19-2.652 3.62-.232 6.81 1.13 9.677 2.975 2.184 1.403 2.993 3.982 3.36 6.584.504 3.586-.786 6.907-2.178 9.94-5.322 11.56-12.342 22.088-20.533 31.823-1.475 1.753-3.2 3.298-5.3 5.447 0-1.24-.175-1.82.03-2.014 6.363-6.216 11.092-13.61 15.753-21.11 3.795-6.103 7.398-12.218 9.49-19.153C54 39.92 49.92 34.936 42.437 35.298c-4.503.215-8.88.673-13.186 1.98-.22.045-.53-.232-1.08-.48zm44.24 42.147c4.893-.345 9.017.142 13.237-.735 4.52-.94 9.01.344 13.49 2.256-.893 1.742-2.313 1.476-3.252 1.17-3.977-1.283-8.038-.79-12.07-.83-3.62-.035-7.247.124-10.868.027-1.78-.045-3.082.43-4.395 1.714-3.326 3.253-6.595 6.664-10.35 9.356-5.562 3.994-11.394 7.767-18.81 7.077-.6-.057-1.22-.085-1.81.006-7.79 1.216-11.924-3.717-15.42-9.396-1.385-2.246-2.07-4.92-3.077-7.4-.44-1.085-.882-2.17-1.425-3.512-4.91 0-9.724.04-14.532-.045-.645-.01-1.278-.645-2.19-1.13.804-.5 1.415-1.206 2.015-1.195 3.128.074 6.29-.582 9.39.526.944.34 2.087.232 3.133.18 2.382-.112 2.976-.904 2.484-3.12-.94-4.21-.815-12.56.056-17.36.504-2.78.526-5.647 1.04-8.424 1.55-8.372 4.153-16.342 8.6-23.718 2.16-3.586 3.987-7.354 6.753-10.538C38.945 8.638 43.753 4 50.99 2.518 54.35 1.828 57.594.934 61.08.95c8.083.035 14.996 2.897 21.535 7.553 5.322 3.79 8.37 8.79 10.232 14.78.345 1.12.594 2.308.65 3.473.114 2.41.007 4.83.086 7.247.17 5.288-.832 10.283-2.636 15.3-2.348 6.528-5.448 12.598-9.413 18.22-2.675 3.78-5.775 7.252-9.124 11.42zM63.96 32.78c-2.122-1.538-2.252-1.544-2.2-3.523.06-2.63-.703-5.018-1.857-7.292-1.227-2.415-4.316-4.112-6.652-3.546-6.68 1.616-13.213 3.636-18.586 8.218-2.393 2.042-4.53 4.44-7.14 6.143-1.945 1.273-2.76 3.027-3.568 4.882-.583 1.34-.883 2.83-1.17 4.282-.76 3.773-1.36 7.58-2.185 11.336-.802 3.643-1.362 7.263-1.475 11.025-.175 5.74 1.148 11.25 2.082 16.81.486 2.886 1.493 5.748 3.196 8.283 2.38 3.552 5.034 6.9 9.52 7.528 4.463.628 9.016.453 13.28-1.278 5.873-2.38 11.077-5.82 15.676-10.216 5.22-4.99 9.994-10.334 14.32-16.12 3.322-4.44 6.716-8.927 8.73-14.007 2.11-5.317 5.062-10.527 4.938-16.562 1.787-3.366.09-6.302-1.73-8.717-2.615-3.456-5.777-6.477-10.02-8.157-3.72-1.477-6.465-1.104-9.485 1.498-2.908 2.517-4.576 5.753-5.674 9.413zm27.05-3.83c.214-.17.423-.344.638-.514-.305-1.12-.718-2.223-.905-3.365-1.08-6.64-5.13-11.16-10.233-15.153-4.27-3.343-9.316-4.66-14.3-6.053-5.628-1.572-11.29-.684-16.64 1.47-5.9 2.377-11.015 5.827-14.793 11.19-2.902 4.123-4.916 8.654-7.235 13.106 4.016-3.74 8.304-6.89 13.242-9.215 3.552-1.674 7.286-2.466 11.06-3.303 5.158-1.143 8.936.645 10.7 5.328.544 1.45.9 2.97 1.393 4.64.35-.646.582-1.025.774-1.427 2.564-5.385 10.574-8.892 16.445-5.102 2.014 1.302 4.158 2.35 5.815 4.147 1.324 1.443 2.693 2.84 4.04 4.254z" fill="#000000"/></svg>
```

I change fillcolor and srtokecolor, it appers correctly on the canvas:

![untitled-2](https://cloud.githubusercontent.com/assets/9147483/9368518/fff16260-46c3-11e5-8074-7720b04cf729.jpg)

I serialize to json and i get:

```
{"objects":[{"type":"path-group","originX":"left","originY":"top","left":60,"top":59,"width":100,"height":100,"fill":"","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":3.34,"scaleY":3.34,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"paths":[{"type":"path","originX":"left","originY":"top","left":0.94,"top":0.95,"width":98.2,"height":98.22,"fill":{"hue":0,"saturation":1,"lightness":0.5,"alpha":1},"stroke":"#0000ff","strokeWidth":0.9,"strokeDashArray":null,"strokeLineCap":"round","strokeLineJoin":"round","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"path":[["M",74.91,23.6],["c",1.584,0.04,3.202,1.918,3.19,3.694],["c",-0.01,1.352,-1.877,2.84,-3.427,2.732],["c",-1.397,-0.096,-2.2,-1.324,-2.16,-3.315],["c",0.04,-1.91,0.99,-3.144,2.397,-3.11],["z"],["m",0.832,4.327],["l",0.187,-0.277],["l",-0.33,-0.034],["l",0.142,0.31],["z"],["m",-17.632,-1.85],["c",-0.085,1.556,-2.472,3.926,-3.83,3.802],["c",-1.764,-0.165,-3.467,-1.913,-3.46,-3.56],["c",0.005,-1.99,1.775,-3.727,3.744,-3.676],["c",1.708,0.05,3.625,1.906,3.546,3.434],["z"],["m",-4.56,-1.555],["c",0.148,-0.215,0.3,-0.43,0.448,-0.645],["c",-0.136,0.226,-0.272,0.453,-0.407,0.685],["c",-0.146,0.215,-0.294,0.43,-0.435,0.644],["c",0.13,-0.23,0.26,-0.458,0.396,-0.684],["z"],["m",1.81,2.715],["c",1.336,-0.565,0.95,-1.46,0.227,-2.902],["l",-0.186,2.942],["c",-0.548,0.08,-1.097,0.158,-1.645,0.237],["c",0.08,0.18,0.152,0.362,0.232,0.543],["c",0.458,-0.265,0.916,-0.543,1.374,-0.82],["z"],["m",-27.19,9.56],["c",0.803,-0.56,1.408,-1.216,2.155,-1.477],["c",3.632,-1.278,7.297,-2.404,11.19,-2.652],["c",3.62,-0.232,6.81,1.13,9.677,2.975],["c",2.184,1.403,2.993,3.982,3.36,6.584],["c",0.504,3.586,-0.786,6.907,-2.178,9.94],["c",-5.322,11.56,-12.342,22.088,-20.533,31.823],["c",-1.475,1.753,-3.2,3.298,-5.3,5.447],["c",0,-1.24,-0.175,-1.82,0.03,-2.014],["c",6.363,-6.216,11.092,-13.61,15.753,-21.11],["c",3.795,-6.103,7.398,-12.218,9.49,-19.153],["C",54,39.92,49.92,34.936,42.437,35.298],["c",-4.503,0.215,-8.88,0.673,-13.186,1.98],["c",-0.22,0.045,-0.53,-0.232,-1.08,-0.48],["z"],["m",44.24,42.147],["c",4.893,-0.345,9.017,0.142,13.237,-0.735],["c",4.52,-0.94,9.01,0.344,13.49,2.256],["c",-0.893,1.742,-2.313,1.476,-3.252,1.17],["c",-3.977,-1.283,-8.038,-0.79,-12.07,-0.83],["c",-3.62,-0.035,-7.247,0.124,-10.868,0.027],["c",-1.78,-0.045,-3.082,0.43,-4.395,1.714],["c",-3.326,3.253,-6.595,6.664,-10.35,9.356],["c",-5.562,3.994,-11.394,7.767,-18.81,7.077],["c",-0.6,-0.057,-1.22,-0.085,-1.81,0.006],["c",-7.79,1.216,-11.924,-3.717,-15.42,-9.396],["c",-1.385,-2.246,-2.07,-4.92,-3.077,-7.4],["c",-0.44,-1.085,-0.882,-2.17,-1.425,-3.512],["c",-4.91,0,-9.724,0.04,-14.532,-0.045],["c",-0.645,-0.01,-1.278,-0.645,-2.19,-1.13],["c",0.804,-0.5,1.415,-1.206,2.015,-1.195],["c",3.128,0.074,6.29,-0.582,9.39,0.526],["c",0.944,0.34,2.087,0.232,3.133,0.18],["c",2.382,-0.112,2.976,-0.904,2.484,-3.12],["c",-0.94,-4.21,-0.815,-12.56,0.056,-17.36],["c",0.504,-2.78,0.526,-5.647,1.04,-8.424],["c",1.55,-8.372,4.153,-16.342,8.6,-23.718],["c",2.16,-3.586,3.987,-7.354,6.753,-10.538],["C",38.945,8.638,43.753,4,50.99,2.518],["C",54.35,1.828,57.594,0.934,61.08,0.95],["c",8.083,0.035,14.996,2.897,21.535,7.553],["c",5.322,3.79,8.37,8.79,10.232,14.78],["c",0.345,1.12,0.594,2.308,0.65,3.473],["c",0.114,2.41,0.007,4.83,0.086,7.247],["c",0.17,5.288,-0.832,10.283,-2.636,15.3],["c",-2.348,6.528,-5.448,12.598,-9.413,18.22],["c",-2.675,3.78,-5.775,7.252,-9.124,11.42],["z"],["M",63.96,32.78],["c",-2.122,-1.538,-2.252,-1.544,-2.2,-3.523],["c",0.06,-2.63,-0.703,-5.018,-1.857,-7.292],["c",-1.227,-2.415,-4.316,-4.112,-6.652,-3.546],["c",-6.68,1.616,-13.213,3.636,-18.586,8.218],["c",-2.393,2.042,-4.53,4.44,-7.14,6.143],["c",-1.945,1.273,-2.76,3.027,-3.568,4.882],["c",-0.583,1.34,-0.883,2.83,-1.17,4.282],["c",-0.76,3.773,-1.36,7.58,-2.185,11.336],["c",-0.802,3.643,-1.362,7.263,-1.475,11.025],["c",-0.175,5.74,1.148,11.25,2.082,16.81],["c",0.486,2.886,1.493,5.748,3.196,8.283],["c",2.38,3.552,5.034,6.9,9.52,7.528],["c",4.463,0.628,9.016,0.453,13.28,-1.278],["c",5.873,-2.38,11.077,-5.82,15.676,-10.216],["c",5.22,-4.99,9.994,-10.334,14.32,-16.12],["c",3.322,-4.44,6.716,-8.927,8.73,-14.007],["c",2.11,-5.317,5.062,-10.527,4.938,-16.562],["c",1.787,-3.366,0.09,-6.302,-1.73,-8.717],["c",-2.615,-3.456,-5.777,-6.477,-10.02,-8.157],["c",-3.72,-1.477,-6.465,-1.104,-9.485,1.498],["c",-2.908,2.517,-4.576,5.753,-5.674,9.413],["z"],["m",27.05,-3.83],["c",0.214,-0.17,0.423,-0.344,0.638,-0.514],["c",-0.305,-1.12,-0.718,-2.223,-0.905,-3.365],["c",-1.08,-6.64,-5.13,-11.16,-10.233,-15.153],["c",-4.27,-3.343,-9.316,-4.66,-14.3,-6.053],["c",-5.628,-1.572,-11.29,-0.684,-16.64,1.47],["c",-5.9,2.377,-11.015,5.827,-14.793,11.19],["c",-2.902,4.123,-4.916,8.654,-7.235,13.106],["c",4.016,-3.74,8.304,-6.89,13.242,-9.215],["c",3.552,-1.674,7.286,-2.466,11.06,-3.303],["c",5.158,-1.143,8.936,0.645,10.7,5.328],["c",0.544,1.45,0.9,2.97,1.393,4.64],["c",0.35,-0.646,0.582,-1.025,0.774,-1.427],["c",2.564,-5.385,10.574,-8.892,16.445,-5.102],["c",2.014,1.302,4.158,2.35,5.815,4.147],["c",1.324,1.443,2.693,2.84,4.04,4.254],["z"]],"pathOffset":{"x":50.03749999999998,"y":50.06036841156944}}]}],"background":""}
```
I get:

![untitled-3](https://cloud.githubusercontent.com/assets/9147483/9368650/ccf926b2-46c4-11e5-832a-616cbc966438.jpg)

backcolor has gone....
I tries also pathgroup group everything

![untitled-3](https://cloud.githubusercontent.com/assets/9147483/9368650/ccf926b2-46c4-11e5-832a-616cbc966438.jpg)

svg export works as expected:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="500" height="500" xml:space="preserve"><desc>Created with Fabric.js 1.6.0-rc.1</desc><defs></defs><g style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: none; fill-rule: nonzero; opacity: 1;" transform="translate(60 59) scale(3.34 3.34)" >
<path d="M 74.91 23.6 c 1.584 0.04 3.202 1.918 3.19 3.694 c -0.01 1.352 -1.877 2.84 -3.427 2.732 c -1.397 -0.096 -2.2 -1.324 -2.16 -3.315 c 0.04 -1.91 0.99 -3.144 2.397 -3.11 z m 0.832 4.327 l 0.187 -0.277 l -0.33 -0.034 l 0.142 0.31 z m -17.632 -1.85 c -0.085 1.556 -2.472 3.926 -3.83 3.802 c -1.764 -0.165 -3.467 -1.913 -3.46 -3.56 c 0.005 -1.99 1.775 -3.727 3.744 -3.676 c 1.708 0.05 3.625 1.906 3.546 3.434 z m -4.56 -1.555 c 0.148 -0.215 0.3 -0.43 0.448 -0.645 c -0.136 0.226 -0.272 0.453 -0.407 0.685 c -0.146 0.215 -0.294 0.43 -0.435 0.644 c 0.13 -0.23 0.26 -0.458 0.396 -0.684 z m 1.81 2.715 c 1.336 -0.565 0.95 -1.46 0.227 -2.902 l -0.186 2.942 c -0.548 0.08 -1.097 0.158 -1.645 0.237 c 0.08 0.18 0.152 0.362 0.232 0.543 c 0.458 -0.265 0.916 -0.543 1.374 -0.82 z m -27.19 9.56 c 0.803 -0.56 1.408 -1.216 2.155 -1.477 c 3.632 -1.278 7.297 -2.404 11.19 -2.652 c 3.62 -0.232 6.81 1.13 9.677 2.975 c 2.184 1.403 2.993 3.982 3.36 6.584 c 0.504 3.586 -0.786 6.907 -2.178 9.94 c -5.322 11.56 -12.342 22.088 -20.533 31.823 c -1.475 1.753 -3.2 3.298 -5.3 5.447 c 0 -1.24 -0.175 -1.82 0.03 -2.014 c 6.363 -6.216 11.092 -13.61 15.753 -21.11 c 3.795 -6.103 7.398 -12.218 9.49 -19.153 C 54 39.92 49.92 34.936 42.437 35.298 c -4.503 0.215 -8.88 0.673 -13.186 1.98 c -0.22 0.045 -0.53 -0.232 -1.08 -0.48 z m 44.24 42.147 c 4.893 -0.345 9.017 0.142 13.237 -0.735 c 4.52 -0.94 9.01 0.344 13.49 2.256 c -0.893 1.742 -2.313 1.476 -3.252 1.17 c -3.977 -1.283 -8.038 -0.79 -12.07 -0.83 c -3.62 -0.035 -7.247 0.124 -10.868 0.027 c -1.78 -0.045 -3.082 0.43 -4.395 1.714 c -3.326 3.253 -6.595 6.664 -10.35 9.356 c -5.562 3.994 -11.394 7.767 -18.81 7.077 c -0.6 -0.057 -1.22 -0.085 -1.81 0.006 c -7.79 1.216 -11.924 -3.717 -15.42 -9.396 c -1.385 -2.246 -2.07 -4.92 -3.077 -7.4 c -0.44 -1.085 -0.882 -2.17 -1.425 -3.512 c -4.91 0 -9.724 0.04 -14.532 -0.045 c -0.645 -0.01 -1.278 -0.645 -2.19 -1.13 c 0.804 -0.5 1.415 -1.206 2.015 -1.195 c 3.128 0.074 6.29 -0.582 9.39 0.526 c 0.944 0.34 2.087 0.232 3.133 0.18 c 2.382 -0.112 2.976 -0.904 2.484 -3.12 c -0.94 -4.21 -0.815 -12.56 0.056 -17.36 c 0.504 -2.78 0.526 -5.647 1.04 -8.424 c 1.55 -8.372 4.153 -16.342 8.6 -23.718 c 2.16 -3.586 3.987 -7.354 6.753 -10.538 C 38.945 8.638 43.753 4 50.99 2.518 C 54.35 1.828 57.594 0.934 61.08 0.95 c 8.083 0.035 14.996 2.897 21.535 7.553 c 5.322 3.79 8.37 8.79 10.232 14.78 c 0.345 1.12 0.594 2.308 0.65 3.473 c 0.114 2.41 0.007 4.83 0.086 7.247 c 0.17 5.288 -0.832 10.283 -2.636 15.3 c -2.348 6.528 -5.448 12.598 -9.413 18.22 c -2.675 3.78 -5.775 7.252 -9.124 11.42 z M 63.96 32.78 c -2.122 -1.538 -2.252 -1.544 -2.2 -3.523 c 0.06 -2.63 -0.703 -5.018 -1.857 -7.292 c -1.227 -2.415 -4.316 -4.112 -6.652 -3.546 c -6.68 1.616 -13.213 3.636 -18.586 8.218 c -2.393 2.042 -4.53 4.44 -7.14 6.143 c -1.945 1.273 -2.76 3.027 -3.568 4.882 c -0.583 1.34 -0.883 2.83 -1.17 4.282 c -0.76 3.773 -1.36 7.58 -2.185 11.336 c -0.802 3.643 -1.362 7.263 -1.475 11.025 c -0.175 5.74 1.148 11.25 2.082 16.81 c 0.486 2.886 1.493 5.748 3.196 8.283 c 2.38 3.552 5.034 6.9 9.52 7.528 c 4.463 0.628 9.016 0.453 13.28 -1.278 c 5.873 -2.38 11.077 -5.82 15.676 -10.216 c 5.22 -4.99 9.994 -10.334 14.32 -16.12 c 3.322 -4.44 6.716 -8.927 8.73 -14.007 c 2.11 -5.317 5.062 -10.527 4.938 -16.562 c 1.787 -3.366 0.09 -6.302 -1.73 -8.717 c -2.615 -3.456 -5.777 -6.477 -10.02 -8.157 c -3.72 -1.477 -6.465 -1.104 -9.485 1.498 c -2.908 2.517 -4.576 5.753 -5.674 9.413 z m 27.05 -3.83 c 0.214 -0.17 0.423 -0.344 0.638 -0.514 c -0.305 -1.12 -0.718 -2.223 -0.905 -3.365 c -1.08 -6.64 -5.13 -11.16 -10.233 -15.153 c -4.27 -3.343 -9.316 -4.66 -14.3 -6.053 c -5.628 -1.572 -11.29 -0.684 -16.64 1.47 c -5.9 2.377 -11.015 5.827 -14.793 11.19 c -2.902 4.123 -4.916 8.654 -7.235 13.106 c 4.016 -3.74 8.304 -6.89 13.242 -9.215 c 3.552 -1.674 7.286 -2.466 11.06 -3.303 c 5.158 -1.143 8.936 0.645 10.7 5.328 c 0.544 1.45 0.9 2.97 1.393 4.64 c 0.35 -0.646 0.582 -1.025 0.774 -1.427 c 2.564 -5.385 10.574 -8.892 16.445 -5.102 c 2.014 1.302 4.158 2.35 5.815 4.147 c 1.324 1.443 2.693 2.84 4.04 4.254 z" style="stroke: #0000ff; stroke-width: 0.899; stroke-dasharray: none; stroke-linecap: round; stroke-linejoin: round; stroke-miterlimit: 10; fill: #FF0000; fill-rule: nonzero; opacity: 1;" transform="" stroke-linecap="round" />
</g>
</svg>
```
ps
exporting large jpg or png... like 5000x5000 crasches chrome

**Comment by costa974** [comment] 2015-08-19 20:58
ups my svg source has gone... github doesnt like vector graphics... try again:
<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><path d="M74.91 23.6c1.584.04 3.202 1.918 3.19 3.694-.01 1.352-1.877 2.84-3.427 2.732-1.397-.096-2.2-1.324-2.16-3.315.04-1.91.99-3.144 2.397-3.11zm.832 4.327l.187-.277-.33-.034.142.31zm-17.632-1.85c-.085 1.556-2.472 3.926-3.83 3.802-1.764-.165-3.467-1.913-3.46-3.56.005-1.99 1.775-3.727 3.744-3.676 1.708.05 3.625 1.906 3.546 3.434zm-4.56-1.555c.148-.215.3-.43.448-.645-.136.226-.272.453-.407.685-.146.215-.294.43-.435.644.13-.23.26-.458.396-.684zm1.81 2.715c1.336-.565.95-1.46.227-2.902l-.186 2.942c-.548.08-1.097.158-1.645.237.08.18.152.362.232.543.458-.265.916-.543 1.374-.82zm-27.19 9.56c.803-.56 1.408-1.216 2.155-1.477 3.632-1.278 7.297-2.404 11.19-2.652 3.62-.232 6.81 1.13 9.677 2.975 2.184 1.403 2.993 3.982 3.36 6.584.504 3.586-.786 6.907-2.178 9.94-5.322 11.56-12.342 22.088-20.533 31.823-1.475 1.753-3.2 3.298-5.3 5.447 0-1.24-.175-1.82.03-2.014 6.363-6.216 11.092-13.61 15.753-21.11 3.795-6.103 7.398-12.218 9.49-19.153C54 39.92 49.92 34.936 42.437 35.298c-4.503.215-8.88.673-13.186 1.98-.22.045-.53-.232-1.08-.48zm44.24 42.147c4.893-.345 9.017.142 13.237-.735 4.52-.94 9.01.344 13.49 2.256-.893 1.742-2.313 1.476-3.252 1.17-3.977-1.283-8.038-.79-12.07-.83-3.62-.035-7.247.124-10.868.027-1.78-.045-3.082.43-4.395 1.714-3.326 3.253-6.595 6.664-10.35 9.356-5.562 3.994-11.394 7.767-18.81 7.077-.6-.057-1.22-.085-1.81.006-7.79 1.216-11.924-3.717-15.42-9.396-1.385-2.246-2.07-4.92-3.077-7.4-.44-1.085-.882-2.17-1.425-3.512-4.91 0-9.724.04-14.532-.045-.645-.01-1.278-.645-2.19-1.13.804-.5 1.415-1.206 2.015-1.195 3.128.074 6.29-.582 9.39.526.944.34 2.087.232 3.133.18 2.382-.112 2.976-.904 2.484-3.12-.94-4.21-.815-12.56.056-17.36.504-2.78.526-5.647 1.04-8.424 1.55-8.372 4.153-16.342 8.6-23.718 2.16-3.586 3.987-7.354 6.753-10.538C38.945 8.638 43.753 4 50.99 2.518 54.35 1.828 57.594.934 61.08.95c8.083.035 14.996 2.897 21.535 7.553 5.322 3.79 8.37 8.79 10.232 14.78.345 1.12.594 2.308.65 3.473.114 2.41.007 4.83.086 7.247.17 5.288-.832 10.283-2.636 15.3-2.348 6.528-5.448 12.598-9.413 18.22-2.675 3.78-5.775 7.252-9.124 11.42zM63.96 32.78c-2.122-1.538-2.252-1.544-2.2-3.523.06-2.63-.703-5.018-1.857-7.292-1.227-2.415-4.316-4.112-6.652-3.546-6.68 1.616-13.213 3.636-18.586 8.218-2.393 2.042-4.53 4.44-7.14 6.143-1.945 1.273-2.76 3.027-3.568 4.882-.583 1.34-.883 2.83-1.17 4.282-.76 3.773-1.36 7.58-2.185 11.336-.802 3.643-1.362 7.263-1.475 11.025-.175 5.74 1.148 11.25 2.082 16.81.486 2.886 1.493 5.748 3.196 8.283 2.38 3.552 5.034 6.9 9.52 7.528 4.463.628 9.016.453 13.28-1.278 5.873-2.38 11.077-5.82 15.676-10.216 5.22-4.99 9.994-10.334 14.32-16.12 3.322-4.44 6.716-8.927 8.73-14.007 2.11-5.317 5.062-10.527 4.938-16.562 1.787-3.366.09-6.302-1.73-8.717-2.615-3.456-5.777-6.477-10.02-8.157-3.72-1.477-6.465-1.104-9.485 1.498-2.908 2.517-4.576 5.753-5.674 9.413zm27.05-3.83c.214-.17.423-.344.638-.514-.305-1.12-.718-2.223-.905-3.365-1.08-6.64-5.13-11.16-10.233-15.153-4.27-3.343-9.316-4.66-14.3-6.053-5.628-1.572-11.29-.684-16.64 1.47-5.9 2.377-11.015 5.827-14.793 11.19-2.902 4.123-4.916 8.654-7.235 13.106 4.016-3.74 8.304-6.89 13.242-9.215 3.552-1.674 7.286-2.466 11.06-3.303 5.158-1.143 8.936.645 10.7 5.328.544 1.45.9 2.97 1.393 4.64.35-.646.582-1.025.774-1.427 2.564-5.385 10.574-8.892 16.445-5.102 2.014 1.302 4.158 2.35 5.815 4.147 1.324 1.443 2.693 2.84 4.04 4.254z" fill="#000000"/></svg>

**Comment by costa974** [comment] 2015-08-19 21:02
maybe now encoding it:
&lt;svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"&gt;&lt;path d="M74.91 23.6c1.584.04 3.202 1.918 3.19 3.694-.01 1.352-1.877 2.84-3.427 2.732-1.397-.096-2.2-1.324-2.16-3.315.04-1.91.99-3.144 2.397-3.11zm.832 4.327l.187-.277-.33-.034.142.31zm-17.632-1.85c-.085 1.556-2.472 3.926-3.83 3.802-1.764-.165-3.467-1.913-3.46-3.56.005-1.99 1.775-3.727 3.744-3.676 1.708.05 3.625 1.906 3.546 3.434zm-4.56-1.555c.148-.215.3-.43.448-.645-.136.226-.272.453-.407.685-.146.215-.294.43-.435.644.13-.23.26-.458.396-.684zm1.81 2.715c1.336-.565.95-1.46.227-2.902l-.186 2.942c-.548.08-1.097.158-1.645.237.08.18.152.362.232.543.458-.265.916-.543 1.374-.82zm-27.19 9.56c.803-.56 1.408-1.216 2.155-1.477 3.632-1.278 7.297-2.404 11.19-2.652 3.62-.232 6.81 1.13 9.677 2.975 2.184 1.403 2.993 3.982 3.36 6.584.504 3.586-.786 6.907-2.178 9.94-5.322 11.56-12.342 22.088-20.533 31.823-1.475 1.753-3.2 3.298-5.3 5.447 0-1.24-.175-1.82.03-2.014 6.363-6.216 11.092-13.61 15.753-21.11 3.795-6.103 7.398-12.218 9.49-19.153C54 39.92 49.92 34.936 42.437 35.298c-4.503.215-8.88.673-13.186 1.98-.22.045-.53-.232-1.08-.48zm44.24 42.147c4.893-.345 9.017.142 13.237-.735 4.52-.94 9.01.344 13.49 2.256-.893 1.742-2.313 1.476-3.252 1.17-3.977-1.283-8.038-.79-12.07-.83-3.62-.035-7.247.124-10.868.027-1.78-.045-3.082.43-4.395 1.714-3.326 3.253-6.595 6.664-10.35 9.356-5.562 3.994-11.394 7.767-18.81 7.077-.6-.057-1.22-.085-1.81.006-7.79 1.216-11.924-3.717-15.42-9.396-1.385-2.246-2.07-4.92-3.077-7.4-.44-1.085-.882-2.17-1.425-3.512-4.91 0-9.724.04-14.532-.045-.645-.01-1.278-.645-2.19-1.13.804-.5 1.415-1.206 2.015-1.195 3.128.074 6.29-.582 9.39.526.944.34 2.087.232 3.133.18 2.382-.112 2.976-.904 2.484-3.12-.94-4.21-.815-12.56.056-17.36.504-2.78.526-5.647 1.04-8.424 1.55-8.372 4.153-16.342 8.6-23.718 2.16-3.586 3.987-7.354 6.753-10.538C38.945 8.638 43.753 4 50.99 2.518 54.35 1.828 57.594.934 61.08.95c8.083.035 14.996 2.897 21.535 7.553 5.322 3.79 8.37 8.79 10.232 14.78.345 1.12.594 2.308.65 3.473.114 2.41.007 4.83.086 7.247.17 5.288-.832 10.283-2.636 15.3-2.348 6.528-5.448 12.598-9.413 18.22-2.675 3.78-5.775 7.252-9.124 11.42zM63.96 32.78c-2.122-1.538-2.252-1.544-2.2-3.523.06-2.63-.703-5.018-1.857-7.292-1.227-2.415-4.316-4.112-6.652-3.546-6.68 1.616-13.213 3.636-18.586 8.218-2.393 2.042-4.53 4.44-7.14 6.143-1.945 1.273-2.76 3.027-3.568 4.882-.583 1.34-.883 2.83-1.17 4.282-.76 3.773-1.36 7.58-2.185 11.336-.802 3.643-1.362 7.263-1.475 11.025-.175 5.74 1.148 11.25 2.082 16.81.486 2.886 1.493 5.748 3.196 8.283 2.38 3.552 5.034 6.9 9.52 7.528 4.463.628 9.016.453 13.28-1.278 5.873-2.38 11.077-5.82 15.676-10.216 5.22-4.99 9.994-10.334 14.32-16.12 3.322-4.44 6.716-8.927 8.73-14.007 2.11-5.317 5.062-10.527 4.938-16.562 1.787-3.366.09-6.302-1.73-8.717-2.615-3.456-5.777-6.477-10.02-8.157-3.72-1.477-6.465-1.104-9.485 1.498-2.908 2.517-4.576 5.753-5.674 9.413zm27.05-3.83c.214-.17.423-.344.638-.514-.305-1.12-.718-2.223-.905-3.365-1.08-6.64-5.13-11.16-10.233-15.153-4.27-3.343-9.316-4.66-14.3-6.053-5.628-1.572-11.29-.684-16.64 1.47-5.9 2.377-11.015 5.827-14.793 11.19-2.902 4.123-4.916 8.654-7.235 13.106 4.016-3.74 8.304-6.89 13.242-9.215 3.552-1.674 7.286-2.466 11.06-3.303 5.158-1.143 8.936.645 10.7 5.328.544 1.45.9 2.97 1.393 4.64.35-.646.582-1.025.774-1.427 2.564-5.385 10.574-8.892 16.445-5.102 2.014 1.302 4.158 2.35 5.815 4.147 1.324 1.443 2.693 2.84 4.04 4.254z" fill="#000000"/&gt;&lt;/svg&gt;

**Comment by asturur** [comment] 2015-08-19 22:23
What are you using to change color?
you have to showe a jsfiddle with the problem, not just problem description.

I bet the problem is here:
```"fill":{"hue":0,"saturation":1,"lightness":0.5,"alpha":1},"stroke":"#0000ff"```

why you do not try to set fill to "rgb(255,0,0)" or "#FF0000"
i may be wrong but i do not think that
"fill":{"hue":0,"saturation":1,"lightness":0.5,"alpha":1},
is supported.

**Comment by asturur** [comment] 2015-08-30 14:13
If you can show us how you change the color code of your pathgroup fill, we may check further. Otherway we are closing the issue.

**Comment by costa974** [comment] 2015-08-30 14:58
close, my mistake

**Closed** 2015-08-31 15:40 UTC
