### ISSUE TITLE
Xor and svg export works not us expected

### ISSUE THREAD

**Issue by webmak** [kangax/fabric.js#2194] opened 2015-05-13 14:43 UTC
I have create fabric js canvas with xor element
![2015-05-13 15 38 26](https://cloud.githubusercontent.com/assets/10329044/7613134/8c31da22-f997-11e4-979a-49d88fe9defa.png)
But when I have exported it to svg I recive this
![2015-05-13 15 39 56](https://cloud.githubusercontent.com/assets/10329044/7613141/9d662b4a-f997-11e4-894b-dba55807a939.png)

**Comment by asturur** [comment] 2015-05-13 14:46
duplicate of #1883

https://github.com/kangax/fabric.js/issues/1883

You can add there.

**Closed by asturur** 2015-05-13 14:46 UTC
