### ISSUE TITLE
Issue with loading some SVGs with transform/translate values as follows:

### ISSUE THREAD

**Issue by onassar** [kangax/fabric.js#2728] opened 2016-01-09 00:06 UTC
Head to the kitchen sink demo, clear the canvas, and then the *Load SVG* section.
Paste in the following SVG:

    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 89.999931 86.000238" x="0px" y="0px"><path d="m281.28 577c0 18.983 0 39.966 0 58.949-4.455-.855-9.924.272-14.8 3.049-8.666 4.942-12.987 13.575-9.651 19.281 3.336 5.707 13.06 6.326 21.73 1.385 6.522-3.727 10.805-9.721 10.754-15.05h.02v-49.725h48.32v41.06c-4.455-.855-9.924.272-14.8 3.049-8.666 4.942-12.987 13.575-9.651 19.281 3.335 5.707 13.06 6.326 21.73 1.385 6.681-3.817 10.995-10 10.746-15.405h.027v-67.26z" transform="translate(-255.7-577)"></path></svg>

You'll see the following when you select the invisible layer:
![](https://i.imgur.com/rXDvD3T.png)

Make this layer a bit smaller, you'll notice this:
![](https://i.imgur.com/FZwOQQL.png)

It seems like the parser isn't reading the translate transformation properly. I've noticed this with a number of SVGs I've been using lately (CC0 licensed from 3rd parties).

Any chance of getting this bug patched?

**Comment by asturur** [comment] 2016-01-09 08:55
You opened the same question ob SO, i will answer you also there. I think that if you press the load button instead of the load without grouping everything is fine. I will post some code to avoid this. As of now is duplicate of #1520

**Closed by asturur** 2016-01-09 08:55 UTC
