### ISSUE TITLE
toSVG text does not retain position

### ISSUE THREAD

**Issue by suomilapsi** [kangax/fabric.js#2698] opened 2015-12-20 22:11 UTC
Hello,

Text is not retaining it's position if canvas is saved to svg and loaded back. Note that it does retain if saved to JSON and loaded back. Seems to be a back in toSVG?

https://jsfiddle.net/suomilapsi/gn4b616z/15/

Best regards,
Suomilapsi

**Comment by asturur** [comment] 2015-12-20 23:24
duplicate of #1280

**Closed by asturur** 2015-12-20 23:24 UTC
