### ISSUE TITLE
SVG Not Rendering Properly

### ISSUE THREAD

**Issue by bernays** [kangax/fabric.js#3981] opened 2017-06-06 22:50 UTC
In order to get around performance hit of rendering lines individually I am trying to load the background as an SVG. Fabric just loads the grid lines as a black box rather than grid lines.

https://codepen.io/anon/pen/GEJyxe

**Comment by asturur** [comment] 2017-06-06 23:14
duplicate of #476 

we still do not support patterns.
Hopefully with release of 2.0 many things will change

**Closed by asturur** 2017-06-06 23:14 UTC
