### ISSUE TITLE
getting the correct bounding box of text

### ISSUE THREAD

**Issue by dshep4** [kangax/fabric.js#2552] opened 2015-10-14 13:44 UTC
The bounding box of text seems to be based on the font size rather than the properties of the actual font.. maybe its based on a single font's properties (but which one?). It causes problems when loading the serialized data into another platforms canvas because the 'top' position isn't accurate.

How would you go about getting the actual top position of the text? The baseline of text always seems to be the same ascension from the top of the box, for a given text size, but there doesn't seem to be a way to get that value.

**Comment by dshep4** [comment] 2015-10-15 12:11
Each one of these text objects has the same font size

![text1](https://cloud.githubusercontent.com/assets/7524863/10513234/419a3a58-7314-11e5-943c-44f14155840c.png)
![text2](https://cloud.githubusercontent.com/assets/7524863/10513236/439f4b68-7314-11e5-906a-83ab122a4a50.png)
![text3](https://cloud.githubusercontent.com/assets/7524863/10513237/45a973b6-7314-11e5-882b-120607c57047.png)

**Comment by asturur** [comment] 2015-10-15 14:02
text metric in javascript returns only the width of text, not the height nor the position of baseline. we guess the height looking at fontsize.

to have better metrics we need an external lib or newer apis from browsers.

**Comment by asturur** [comment] 2017-09-03 10:43
duplicate of #1108

**Closed by asturur** 2017-09-03 10:43 UTC
Labels: possible_feature
