### ISSUE TITLE
Need to Zoom in/out all objects from center point without zoomToPoint function.

### ISSUE THREAD

**Issue by jrishna** [kangax/fabric.js#3845] opened 2017-04-12 01:30 UTC
Hi,
I can zoom in/out objects from center point using this http://jsfiddle.net/Kienz/2Luoaxv4/ link,but i want to zoom in/out objects from center point using following code.

var objects = canvas.getObjects();
for (var i in objects) {
var scaleX = objects[i].scaleX;
var scaleY = objects[i].scaleY;
var left = objects[i].left;
var top = objects[i].top;

  var tempScaleX = scaleX * factor;
  var tempScaleY = scaleY * factor;
  var tempLeft = left * factor;
  var tempTop = top * factor;

  objects[i].scaleX = tempScaleX;
  objects[i].scaleY = tempScaleY;
  objects[i].left = tempLeft;
  objects[i].top = tempTop;
  objects[i].setCoords();
}
canvas.renderAll();
canvas.calcOffset();

Please help.

**Comment by jrishna** [comment] 2017-04-12 01:47
Objects scaling but while zoom in/out objects moving up/down.
Please check attached file.
[fabric.zip](https://github.com/kangax/fabric.js/files/915167/fabric.zip)

**Comment by asturur** [comment] 2017-04-14 08:18
please provide a jsfiddle based on latest ( you find 1.7.7 available in jsfiddle ) with your current setup of code. then describe the problem on that fiddle.

**Comment by asturur** [comment] 2017-04-14 09:11
continue to post here, do not open another issue, i m closing this since is not a big.

**Comment by asturur** [comment] 2017-04-14 09:12
i meant not a BUG

**Closed by asturur** 2017-04-14 09:11 UTC

**Comment by jrishna** [comment] 2017-04-14 09:35
Hi Andrea,
Thanks for reply.I have attached my source code. I want to zoom all objects without canvas.zoomToPoint(point, .canvas.getZoom() * 1.1) function and without setViewport.


 Please check attached zip file.

**Comment by asturur** [comment] 2017-04-14 09:45
no i have to use my free time with efficency. create a fiddle with your own code and o see if i can understand the problem or propose a workaround.

try to explain visually what do you mean by zooming from center ( a gif a video, a screenshot )

**Comment by jrishna** [comment] 2017-04-15 04:43
Hi Andrea,

Thanks for reply.I have attached screenshot of my requirement.
[zoominout.zip](https://github.com/kangax/fabric.js/files/923333/zoominout.zip)
