### ISSUE TITLE
Wrong reported left and top value for object in object:rotating event

### ISSUE THREAD

**Issue by gsouquet** [kangax/fabric.js#2596] opened 2015-10-30 12:14 UTC
Hi, 
First of all thanks for the amazing work with this library, really useful! 

I think I spotted an inconsistency with the reported `left` and `top` value in the `target` in the following events: `object:moving` and `object:rotating`.

```
var canvas = new fabric.Canvas('canvas');
var onObjectMoving = function(evt) {
  console.log(evt.target.left);
  console.log(evt.target.top);
};
canvas.on('object:selected', onObjectMoving);
canvas.on('object:moving', onObjectMoving);
canvas.on('object:rotating', onObjectMoving);
```

When the event `object:selected` or `object:moving` is triggered the reported value for `left` and `top` and relative to the top left of the object. 

But when it is called via `object:rotating` it seems that there is an offset, the `left` and `top` value are now relative to the center of the object.

To illustrate the issue I created this [JSBin](http://jsbin.com/xatafucihi/1/edit?html,js,console,output)

Steps to reproduce the issue:
* Select the text
* Rotate the text
* Click somewhere else to lose the focus on the text
* Click again on the text to focus it
* Watch the console and how the last two different reported values are different

Hope all of that makes sense, I looked at the documentation and didn't see anything explaining that behaviour that I don't think that this is intended.

Thanks again

**Comment by asturur** [comment] 2015-10-30 12:16
duplicate of #1409

**Closed by asturur** 2015-10-30 12:16 UTC
