### ISSUE TITLE
Incorrectly imported SVG  ( filters and masks )

### ISSUE THREAD

**Issue by ggodlewski** [kangax/fabric.js#1096] opened 2014-01-14 17:06 UTC
I have a problem importing SVG file http://test.gitgis.com/fabricjs/test1.svg
This is how it looks like in fabric: http://test.gitgis.com/fabricjs/

It has wrong position of element, color and transparency.
Can I do anything to make it better?

**Comment by asturur** [comment] 2015-07-16 16:43
duplicate of #929

**Closed by asturur** 2015-07-16 16:43 UTC
Labels: bug, svg_parser
