### ISSUE TITLE
position of object in a transformed group

### ISSUE THREAD

**Issue by slow-loris** [kangax/fabric.js#2463] opened 2015-09-02 15:10 UTC
I have a problem with figuring out the absolute position of a object in a group, which is rotated for example.

Here is example screenshot:
![image](https://cloud.githubusercontent.com/assets/7202192/9635028/9643158a-5194-11e5-8ca9-29dd976fd6c3.png)
The yellow squares are members of a group.
If I click on the group, I catch the mouse:down event and getting the point I clicked and the group object.
How do i determine the inner object I clicked on?

The solution shown in #801 doesn't work on transformed objects.

**Comment by asturur** [comment] 2015-09-02 15:59
Duplicate of #485 

At the end there is a link to proposed PR that helps you to get group sub targeting work.

**Closed by asturur** 2015-09-02 15:59 UTC
