### ISSUE TITLE
Groups with textbox are locked on Y axis after loading from JSON

### ISSUE THREAD

**Issue by rodofatos** [kangax/fabric.js#2718] opened 2015-12-29 15:38 UTC
Hello, 
i have a strange problem with Fabric groups. I have a canvas on which i add a Rectangle which after i transform into a group with a text on the rectangle. Everything works fine, but if i save to JSON and then load it back then the scaling on Y is locked(althought it shows false on group properties). On X axis everything is working fine.
Here is a jsfiddle with the JSON i try to load into canvas. As far as i looked into it i cant see any propertie that would enforce lock on Y axis. Can someone look into this and give me a hint on what is the problem ? or I am doing something wrong ?
http://jsfiddle.net/fmgXt/408/

**Comment by asturur** [comment] 2015-12-29 15:46
is a textbox problem.
can you provide code that create the group, to test the group BEFORE it gets loaded from json?

thanks.

**Comment by rodofatos** [comment] 2015-12-29 17:46
var text = new fabric.Textbox(inputValue, {
                fontSize: 18,
                height: 100,
                width: 200,
                fontFamily: 'Lato',
                fill: 'white',
                backgroundColor : 'rgba(0,0,0,0.25)'
            });
            var info = new fabric.Textbox('Pending', {
                fontSize: 18,
                height: 100,
                width: 200,
                fontFamily: 'Lato',
                fill: 'white',
                backgroundColor: 'rgba(0,0,0,0.25)'
            });
            var left = selectedObject.left;
            var top = selectedObject.top;
            var angle = selectedObject.angle;
            window.editCanvas.remove(selectedObject);
            selectedObject.left = 0;
            selectedObject.top = 0;
            text.top = 5;
            text.left = 5;
            text.lockScalingX = false;
            text.lockScalingY = false;
            text.setOnGroup('scaleX', 1);
            text.textType = 'roomContent';
            info.top = selectedObject.height/2;
            info.left = 5;
            info.lockScalingX = false;
            info.lockScalingY = false;
            info.setOnGroup('scaleX', 1);
            info.textType = 'roomScheduleInfo';
            var group = new fabric.Group([selectedObject, text, info], {
                left: left,
                top: top,
                angle: angle
            });
            group.on('selected', function (element) {
                var object = window.editCanvas.getActiveObject();
                var text = object.getObjects('textbox')[0].text;
                $('#content-name').val(text);
            });
            group.on('modified', function (event) {
                window.editCanvas.renderAll();
            });
            group.lockScalingFlip = true;
            group.lockScalingY = false;
            window.editCanvas.add(group);
            window.editCanvas.bringToFront(text);



This is the code that creates the group from an existing rectangle(selectedObject). The idea is that before serializing it into JSON it works, but after loading it back it doesnt.

 var json = JSON.stringify(window.editCanvas.toJSON([ 'selectable', 'lockMovementX', 'lockMovementY', 'lockRotation', 'lockScalingX', 'lockScalingY', 'lockUniScaling']));
code for serialization

window.editCanvas.loadFromJSON(json);
window.editCanvas.forEachObject(function (o) {
        o.lockScalingY = false;
});
window.editCanvas.renderAll();
code for deserialization

**Comment by asturur** [comment] 2016-04-13 02:19
The problem is not related to json. When a group containing a textbox get squeezed below the minimum textbox width, then we have a problem.

**Comment by asturur** [comment] 2016-05-08 19:18
My old comment was wrong.
Textbox set lockscalingY true in initialize.
I  think that if the user wants to leave it enabled it should be able to do so.
I will swap the order in wich the properties gets applied so that the one passed by user win over the standard one

**Comment by asturur** [comment] 2016-05-08 19:25
closed via https://github.com/kangax/fabric.js/commit/13026beecbea130c0729629f919cb4eb8f1088fd
(accidentally skipped PR process)

**Closed by asturur** 2016-05-08 19:25 UTC
Labels: bug, itext
