### ISSUE TITLE
Resize on rotated groups

### ISSUE THREAD

**Issue by suroh1994** [kangax/fabric.js#2044] opened 2015-03-17 14:42 UTC
I detected a problem when resizing a rotated group. The objects in the group are not resizing like they should. 
For example: I draw some lines, rotate them by 90 degrees, deselect them and then reselect them. This is important, because else this does not happen. Now when resizing in width the lines look good. But once you deselect the lines they update and resize in their original width (which would now be their height) so they stretch/shrink in height instead of width.

You can easily reproduce this bug in kitchensink.

EDIT: Ok, I oversaw a previous post (issue 1879) where this problem is already discussed. Is there any chance this problem is getting fixed in the near future?

**Comment by KJTsanaktsidis** [comment] 2015-04-02 14:37
I tried fixing this at one point, and it's a real pit of despair. Our solution to this problem was simply to disable the side resize handles (the corner ones are OK) for groups. This stops you getting into a state where you can render your objects skewed.

**Comment by asturur** [comment] 2015-04-04 13:02
Duplicate of #726

**Closed by asturur** 2015-04-04 13:02 UTC
