### ISSUE TITLE
Set Position of Rotated Object Based on Bounding Box Left,Top

### ISSUE THREAD

**Issue by arminbusatlic** [kangax/fabric.js#3521] opened 2016-12-10 22:00 UTC
I have top left coordinates of the bounding box of my canvas object. If the object is rotated, left, top of object will be different than the bounding box left, top. 

Is there a way to set the objects correct position based off of the bounding box left, top?

I started creating some trig functions to calculate left,top of a rotated canvas object based off of the bounding box left, top and I really wish there was a better way of doing this.

If anyone knows a better way, let me know.

**Comment by asturur** [comment] 2016-12-11 10:45
you should provide at least a picture to understand what is bounding box for you and what point your are trying to calculate.

**Comment by arminbusatlic** [comment] 2016-12-11 23:34
Sorry for not being more detailed about this. 

![screenshot](https://cloud.githubusercontent.com/assets/2653785/21084352/3e135e5a-bfd0-11e6-9f4f-05f5dfaf1f7b.png)

The red is the bounding box, The x,y coordinates are the top left corner of the bounding box. I have x,y coordinates, but I need to calculate the left, top so that I can position the object properly, since the left, top position in object always refers to the left top corner of the object. When an object is rotated, the left top is different than x,y.

**Comment by arminbusatlic** [comment] 2016-12-12 19:53
I basically want to set left, top of watermark, but I only have the x,y ( top,left position of the boundary box of the object ). Any way to position the watermark based on its top, left boundary position?

Armin

**Comment by asturur** [comment] 2016-12-13 08:28
Yes there is a way.
Center of object and center of bounding box are the same. by definitition i guess.
So you can calculate the center of bounding box ( the function that gives you bounding box gives you all the information of widht/height.

Then you have a function called 
```setPositionByOrigin```
you can find it here http://fabricjs.com/docs/fabric.Object.html
You will pass this function the center of bounding box and the origin 'center' for the object, and it should position it.

Since this is an help request with custom code, and not a bug with library i close the issue. If information is not enought ( but it should ) write again i will still get notice of it.

**Closed by asturur** 2016-12-13 08:28 UTC

**Comment by arminbusatlic** [comment] 2016-12-15 14:46
Oh wow. That was 100 times easier to do. I was starting to go crazy with trigonometry :)
Thanks a lot! Wonderful advice.
