### ISSUE TITLE
Problem with parsing SVG

### ISSUE THREAD

**Issue by dgodard** [kangax/fabric.js#2283] opened 2015-06-12 16:19 UTC
The following SVG (test sample) is correctly opened in INKSCAPE but not in http://fabricjs.com/kitchensink/ : texts are moved and their positions are incorrect, image originx is set to center not to top/left....

The problem seems to be in parser > parseAttributes > if('transformMatrix')

This what i expected to see : 
![sans-titre](https://cloud.githubusercontent.com/assets/8191437/8134361/e08c5a58-112e-11e5-8742-d85f83fcbc58.png)

This is the svg file :
```xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="400" height="100" xml:space="preserve">
	<desc>Created with Fabric.js 1.2.0</desc>
	<defs/>
	<rect id="bandesbandeHaute" x="0" y="-50" rx="0" ry="0" width="0" height="100" style="stroke: #000000; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: none; text-anchor: middle; opacity: 1;" transform="translate(400 50)"/>
	<rect id="bandesbandeBasse" x="0" y="-50" rx="0" ry="0" width="0" height="100" style="stroke: #000000; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: none; text-anchor: middle; opacity: 1;" transform="translate(0 50)"/>
	<image xlink:href="http://localhost:25629/CLLWeb/CouponEditor/GetBarCode?code=210987654321&amp;type=ean13&amp;width=200" id="dyn_cb_ean13_1" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); text-anchor: middle; opacity: 1;" transform="translate(147.59 68.74) rotate(-35.00 111.00 83.00) scale(1.11 1.11)" width="200" height="150"/>
	<g transform="translate(111.16 100.83) rotate(-15)">
		<rect fill="none" x="0" y="0" width="195" height="60"/>
		<text id="dyn_text_2" font-family="Tahoma" font-size="60" font-weight="100" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #000000; text-anchor: start; opacity: 1;" >
			<tspan x="0" y="60" fill="#000000">Saisir...</tspan>
		</text>
	</g><g transform="translate(209.45 21.46) rotate(4)">
		<rect fill="none" x="0" y="0" width="284.79" height="60"/>
		<text id="stat_text_3" font-family="Tahoma" font-size="60" font-weight="100" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #000000; text-anchor: start; opacity: 1;" >
			<tspan x="0" y="60" fill="#000000">gdfgfd</tspan>
		</text>
	</g>
	<rect id="stat_carre_4" x="-29" y="-29" rx="0" ry="0" width="58" height="58" style="stroke: #000000; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #21e0c6; text-anchor: middle; opacity: 1;" transform="translate(300.63 105.63) rotate(-74)"/>
	<rect id="stat_carreRond_5" x="-24" y="-23" rx="10" ry="10" width="48" height="46" style="stroke: #000000; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #000000; text-anchor: middle; opacity: 1;" transform="translate(58.48 80.6) rotate(-6)"/>
	<circle id="stat_cercle_6" cx="0" cy="0" r="100" style="stroke: #000000; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #000000; text-anchor: middle; opacity: 1;" transform="translate(354.75 56.25) rotate(0) scale(0.52 0.52)"/>
	<image xlink:href="http://localhost:25629/CLLWeb/CouponEditor/GetImageUrl?id=Casino.png&amp;imgType=1" id="stat_image_static_7" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); text-anchor: middle; opacity: 1;" transform="translate(51.89 24.85) rotate(-11.00 42.50 14.00) scale(0.57 0.56)" width="149" height="50"/>
	<line id="stat_ligne_8" x1="6" y1="104" x2="351" y2="68" angle="-6.00" style="stroke: #000000; stroke-width: 3; stroke-dasharray: none; fill: #000000; opacity: 1;"/>
	<g transform="translate(148.5 33) rotate(-11)">
		<rect fill="none" x="0" y="0" width="98" height="30"/>
		<text id="stat_text_9" font-family="Tahoma" font-size="30" font-weight="100" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #000000; text-anchor: start; opacity: 1;" >
			<tspan x="0" y="30" fill="#000000">Saisir...</tspan>
		</text>
	</g>
</svg>
```

Test in JSFiddle : https://jsfiddle.net/dgodard/p9ss0b6u/1/

**Comment by asturur** [comment] 2015-06-12 16:25
problem looks like in tspan
move x and y property to text element and try again.
Consider that you posted an svg with reference to localhost that we cannot test.

**Comment by dgodard** [comment] 2015-06-12 17:00
Thank you,

But i have several svg files, provided by other people,   that can be opened in inkscape but not in FabricsJs 1.5.0.
The project i am working on use a modified version of FabricJS 1.2 that can display them correctly.

I tried to transposed the modification with no effective result. All my objects have their position (X, Y) corrupted but not the angle, scalling,  and aspect.

This is the display in Kitchensink with FabricsJS on my computer :
![2015-06-12_18h44_08](https://cloud.githubusercontent.com/assets/8191437/8134866/0fb2d5b0-1133-11e5-93cb-a629c41e2f5f.png)
 

With FabricsJS 1.5 modified :
![2015-06-12_18h58_41](https://cloud.githubusercontent.com/assets/8191437/8135144/2fba7bd6-1135-11e5-8158-3f0d87dbf7a8.png)


Regards.

**Comment by asturur** [comment] 2015-06-12 17:10
please provide those svgs if possible and we  will check if other than the unsupported fratures there are other issue.

transformMatrix error parsing is unlikely wrong.

**Comment by dgodard** [comment] 2015-06-13 08:46
I modified my svg doc after validating it with W3C validator ( https://validator.w3.org/check )
There was an error because angle attribute is not a valid one for Line element, so i corrected it. 

I also changed image references by using placehold.it

this is the new image inside a html5 web page
<!DOCTYPE html>
<html>
<head>
    <title>testSVG</title>
    <meta charset="UTF-8">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
</head>
<body>
    <?xml version="1.0" standalone="no" ?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="400" height="100" xml:space="preserve">
        <desc>Created with Fabric.js 1.2.0</desc>
        <defs/>
        <rect id="bandesbandeHaute" x="0" y="-50" rx="0" ry="0" width="0" height="100" style="stroke: #000000; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: none; text-anchor: middle; opacity: 1;" transform="translate(400 50)"/>
        <rect id="bandesbandeBasse" x="0" y="-50" rx="0" ry="0" width="0" height="100" style="stroke: #000000; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: none; text-anchor: middle; opacity: 1;" transform="translate(0 50)"/>
        <image xlink:href="http://placehold.it/200x150" id="dyn_cb_ean13_1" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); text-anchor: middle; opacity: 1;" transform="translate(147.59 68.74) rotate(-35.00 111.00 83.00) scale(1.11 1.11)" width="200" height="150"/>
        <g transform="translate(111.16 100.83) rotate(-15)">
            <rect fill="none" x="0" y="0" width="195" height="60"/>
            <text id="dyn_text_2" font-family="Tahoma" font-size="60" font-weight="100" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #000000; text-anchor: start; opacity: 1;" >
                <tspan x="0" y="60" fill="#000000">Saisir...</tspan>
            </text>
        </g><g transform="translate(209.45 21.46) rotate(4)">
        <rect fill="none" x="0" y="0" width="284.79" height="60"/>
        <text id="stat_text_3" font-family="Tahoma" font-size="60" font-weight="100" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #000000; text-anchor: start; opacity: 1;" >
            <tspan x="0" y="60" fill="#000000">gdfgfd</tspan>
        </text>
        </g>
        <rect id="stat_carre_4" x="-29" y="-29" rx="0" ry="0" width="58" height="58" style="stroke: #000000; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #21e0c6; text-anchor: middle; opacity: 1;" transform="translate(300.63 105.63) rotate(-74)"/>
        <rect id="stat_carreRond_5" x="-24" y="-23" rx="10" ry="10" width="48" height="46" style="stroke: #000000; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #000000; text-anchor: middle; opacity: 1;" transform="translate(58.48 80.6) rotate(-6)"/>
        <circle id="stat_cercle_6" cx="0" cy="0" r="100" style="stroke: #000000; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #000000; text-anchor: middle; opacity: 1;" transform="translate(354.75 56.25) rotate(0) scale(0.52 0.52)"/>
        <image xlink:href="http://placehold.it/149x50" id="stat_image_static_7" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); text-anchor: middle; opacity: 1;" transform="translate(51.89 24.85) rotate(-11.00 42.50 14.00) scale(0.57 0.56)" width="149" height="50"/>
        <line id="stat_ligne_8" x1="6" y1="104" x2="351" y2="68" style="stroke: #000000; stroke-width: 3; stroke-dasharray: none; fill: #000000; opacity: 1;"/>
        <g transform="translate(148.5 33) rotate(-11)">
            <rect fill="none" x="0" y="0" width="98" height="30"/>
            <text id="stat_text_9" font-family="Tahoma" font-size="30" font-weight="100" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #000000; text-anchor: start; opacity: 1;" >
                <tspan x="0" y="30" fill="#000000">Saisir...</tspan>
            </text>
        </g>
    </svg>
</body>
</html>

**Comment by dgodard** [comment] 2015-06-15 08:32
After reading this article : https://www.bountysource.com/issues/3284720-shapes-with-transformmatrix-have-misplaced-controls
I think it seems to be the same problem.

**Comment by asturur** [comment] 2015-06-15 08:56
@dgodard 

are you loading them grouped or ungrouped?

**Comment by dgodard** [comment] 2015-06-15 10:16
I tested both in Kitchensink sample.

In my application i want to load my SVG ungrouped in order to modify its items.

**Comment by asturur** [comment] 2015-06-15 10:25
So is duplicate of #1520.
Solution is coming anyway.

There is a partial solution here: #2215.
I will finish asap.

**Closed by asturur** 2015-06-15 10:25 UTC
