### ISSUE TITLE
getBoundingRect doesn't account for canvas zooming

### ISSUE THREAD

**Issue by ryan-digbil** [kangax/fabric.js#1745] opened 2014-10-13 06:02 UTC
While the object properties account for canvas zooming, getBoundingRect doesn't return an object that accounts for the current zoom level and pan of the canvas.
##

**Comment by lastobelus** [comment] 2015-01-22 07:49
@ggmendez, @ryan-digbil I'm curious to know when you would want a viewportTransform transformed bounding rect?

I think it is definitely not a bug that the current implementation doesn't transform the bounding rect; normal use of the bounding rect is to calculate things relative to other pre-transformed coordinates, but it could be useful to have another method as you implemented.

**Comment by asturur** [comment] 2015-01-22 11:35
We have a mixed situation i think.

Canvas zoom came later from a external PR that has been merged.
While canvas zooming and panning mostly work with everything is not perfect yet, some aspect have not been covered.

Adding functionalities often changes the meaning of some other functions but methods do not get renamed for this.

Probably have both methods would be usefull AFTER a  review of current situation ( what getBoundingBox does and if some other internal method uses it and why)

**Comment by asturur** [comment] 2015-06-01 12:01
The bounding rect is based on canvasZooming as well.
The problem is that calling the function does not force recalculation of setCoords();
if you call setCoords() on the object before asking for bouding box you will have correct values.

Maybe we should do it automatically?
we always avoided calling setCoords automatically.

**Comment by dhakan** [comment] 2016-01-08 15:06
I'm having what I assume is a similar issue to this one, where the bounding box is actually in the wrong place when applying zooming( zoomToPoint) and/or panning(relativePan) to the canvas. 

My usecase is a set group of fabric.Rect(created programmatically), where I'm trying to select individual objects within this group by clicking on them. Whenever I click on the group, I use discardActiveGroup, and then directly setActiveObject for the object whose coordinates are containsPoint with the mouse coordinates. 

I'm able to verify that the compensation fix above @ryan-digbil is outputting the correct coordinates, but I do not know how to use this to update the bounding box to account for the zooming or panning of the canvas, nor why this is happening in the first place.

I was digging through some of the source code also, without success. Neither did I get setCoords to work.

 Any thoughts?

**Comment by asturur** [comment] 2016-01-08 15:25
Did you try my comment above your post?

**Comment by dhakan** [comment] 2016-01-08 15:36
I did try to call setCoords before calling getBoundingRect without success, sorry for not clarifying. But I don't have a usecase where I want to use the values of the getBoundingRect, or is the call actually supposed to put the bounding box back to it's place?

**Comment by asturur** [comment] 2016-11-14 23:05
closed with https://github.com/kangax/fabric.js/pull/3417
Now getBoundingRect returns always updated coordinates and with a boolean flag you can choose to have it at canvas level or at zoomed canvas level.

**Closed by asturur** 2016-11-14 23:05 UTC
Labels: possible_feature
