### ISSUE TITLE
Clipped shape render issue

### ISSUE THREAD

**Issue by kangax** [kangax/fabric.js#1444] opened 2014-07-01 15:51 UTC
Came across clipped shape that doesn't render properly:

```svg
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" []>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
      <clipPath id="clipper">
          <rect height="10" y="0" width="100"></rect>
          <rect height="10" y="20" width="100"></rect>
      </clipPath>
  </defs>

  <rect width="100" height="100" fill="black" clip-path="url(#clipper)"></rect>
</svg>
```

**Comment by idlethumbs** [comment] 2015-08-12 12:34
Although in our experience, any svg containing a clipping mask will fail to render correctly. We just tried a simple example of a square clipping a circle. Will attach it. 

It's pretty vital for us as we're using this plugin to render a canvas for modifying custom products, and much of the artwork that we're using for base templates for customers to modify have clipping masks in them.

Here's a simple SVG :
<pre>
<?xml version="1.0" encoding="utf-8"?>

<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 100 100" style="enable-background:new 0 0 100 100;" xml:space="preserve">
<style type="text/css">
	.st0{clip-path:url(#SVGID_2_);}
</style>
<g>
	<defs>
		<circle id="SVGID_1_" cx="66.5" cy="63.7" r="25.5"/>
	</defs>
	<clipPath id="SVGID_2_">
		<use xlink:href="#SVGID_1_"  style="overflow:visible;"/>
	</clipPath>
	<rect x="17" y="23.2" class="st0" width="75" height="55.2"/>
</g>
</svg>
</pre>

and here is a screen shot of results:

![image](https://cloud.githubusercontent.com/assets/9349874/9223990/e8a10a52-40f6-11e5-81d2-c66ba0d0a7c1.png)

**Comment by asturur** [comment] 2015-08-12 12:52
Problem of supporting clipPath is the missing clipRule on canvas.
Otherways is not far away.

**Comment by idlethumbs** [comment] 2015-08-12 14:44
Ok thanks very much for getting back to me, we will have to flatten images for now, or manually remove clipping masks. Do you envisage finding a solution for the next release ?

**Comment by asturur** [comment] 2015-08-12 14:54
Next release is around the corner ( how far this corner is, no one knows ).
We are adding skew and maybe general transformMatrix support.

After 1.6.0 we are getting back to svg pattern parsing and clippath.
I already had a working implementation that was able to parse wikimedia logo.

```
<?xml version="1.0" standalone="yes"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">

<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"
   id="Wikimedia logo"
   viewBox="-599 -599 1198 1198" width="1024" height="1024">
<defs>
  <clipPath id="mask">
    <path d="M 47.5,-87.5 v 425 h -95 v -425 l -552,-552 v 1250 h 1199 v -1250 z" />
  </clipPath>
</defs>
<g clip-path="url(#mask)">
  <circle id="green parts" fill="#396" r="336.5"/>
  <circle id="blue arc" fill="none" stroke="#069" r="480.25" stroke-width="135.5" />
</g>
<circle fill="#900" cy="-379.5" r="184.5" id="red circle"/>
</svg>
```

signle path clipping.
clip-path composed of multiple path is still a problem.
I have some idea anyway.

**Comment by asturur** [comment] 2015-08-12 14:54
(i lost that implement and was based on fabric 1.4.6 anyway )

**Comment by idlethumbs** [comment] 2015-08-13 13:06
good luck! we will keep an eye on progress

**Comment by asturur** [comment] 2016-04-30 12:45
duplicate of #1454.

**Closed by asturur** 2016-04-30 12:45 UTC
Labels: bug, svg_parser
