### ISSUE TITLE
Possible to set a point of rotation?

### ISSUE THREAD

**Issue by nejc001** [kangax/fabric.js#2123] opened 2015-04-17 13:43 UTC
Hello, is possible to set a (x,y) point in a rectangle's (or any other shape) or its clickable area, as his rotating point?

Example:
We have a rectangle with width:100 and height:100.
With settings OriginX:left and OriginY:top, the rectangle would rotate around point (0,0), right?

I like to rotate in point (25,25), which in this example, with Origin isn't possible.

I saw object settings named rotationPointX and rotationPointY, but have no idea how do they work.
Tried to use them in some ways, but the object didnt seem to rotate in that point.

**Comment by asturur** [comment] 2015-04-17 14:38
Can you spell the settings correctly? i cannot find them in the fabric library at all.

Actually rotation is supported on center point, The transform method support a second parameter, called FromLeft which would allow to do what you say, but this would influence all trasformation not just the rotation.

**Comment by nejc001** [comment] 2015-04-18 08:36
My bad, it seems that those functions are from some other library then.

Thanks, I will try that next week in monday.

**Comment by nejc001** [comment] 2015-04-20 13:45
I didn't realy find an example of how to use this Transform for my current problem.
Here is an example of how it should work, if i was unclear in first post:
![Example](http://shrani.si/f/l/La/V6Dza2V/111641221020530527164580.jpg)
You should be able to set the rotation point anywhere in object (by entering x and y).

**Comment by kangax** [comment] 2015-05-14 12:16
Duplicate of #902

**Closed by kangax** 2015-05-14 12:16 UTC
