### ISSUE TITLE
Font issue "Myrad Pro" and "Impact".

### ISSUE THREAD

**Issue by hermans** [kangax/fabric.js#2787] opened 2016-02-12 17:34 UTC
Hi, 
I have issue with font in fabricjs, it happend when i make font in the desinger, the problem for font "Myrad Pro" and "Impact".
It work properly when saved to PNG from fabricjs, but when i try to save to SVG and open to another tool (inkscape) the font style different.

I tried in Centos and Windows OS.

Please see in the attached image bellow for detail

- save use fabricjs to png
![fabricjs_to_png](https://cloud.githubusercontent.com/assets/938767/13015053/88036274-d1e9-11e5-83f8-94c3a6c6ed65.png)

- load to another tool from SVG (generated by fabric js)
![fabricjs_in_svg](https://cloud.githubusercontent.com/assets/938767/13015052/87f42692-d1e9-11e5-905a-22395cc7d18d.png)

**Comment by asturur** [comment] 2016-02-12 17:40
duplicate of #2644
I'm currently working on this.

**Closed by asturur** 2016-02-12 17:40 UTC

**Comment by hermans** [comment] 2016-02-12 17:41
thank you :)
