### ISSUE TITLE
Cannot install fabric using NPM

### ISSUE THREAD

**Issue by StephanBijzitter** [kangax/fabric.js#2607] opened 2015-11-04 13:11 UTC
Debug data:
https://gist.github.com/StephanBijzitter/2df5948391cdd16a2b64

I would love to help on this one, but I am clueless.
Installing jQuery and Angular does work without any issues.

**Comment by asturur** [comment] 2015-11-04 13:37
Please if you are installing for node, check that libcairio is installed on your system.

**Comment by StephanBijzitter** [comment] 2015-11-04 13:39
Why is this not added as dependency in `package.json`?

**Comment by asturur** [comment] 2015-11-04 13:45
I do not know. I'm not node user. If you solve please close the issue. I normally install libcairo ( and libpango ) with "yum install" or "apt-get install" i do not know if there is a npm package counterpart. I think those are more system libraries.

**Comment by StephanBijzitter** [comment] 2015-11-04 13:59
Alright, after some Googling it seems that many packages rely on Cairo and they all instruct to install it manually before running NPM install. It's ugly (in my opinion), but I guess it's a limitation of NPM itself.

So I installed it and tried to install Fabric again, I will post the result below:
```

  CXX(target) Release/obj.target/contextify/src/contextify.o
  SOLINK_MODULE(target) Release/contextify.node
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"2.12.1"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"2.12.1"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"2.12.1"})
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "fabric" "--save"
npm ERR! node v0.10.33
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.1.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

```

**Closed** 2015-11-04 14:37 UTC

**Comment by gonsfx** [comment] 2015-11-13 14:00
@StephanBijzitter @kangax
I'm wondering if there's a solution for this. We're developing a single-page-app that installs all of its dependencies using `npm`.

We plan on using `fabric`, we want to install with `npm` but we don't want to install cairo - especially because the build process, where the files are bundled with browserify, should be able to run on any machine with node/npm and without any other requirements (such as cairo).

**Comment by kangax** [comment] 2015-11-13 14:08
@gonsfx how would we render anything with Fabric by running it on Node if it uses node-canvas which uses cairo?

**Comment by asturur** [comment] 2015-11-14 18:08
a feeling of deep unsuitableness is all around me

:)

**Comment by gonsfx** [comment] 2015-11-16 08:09
@kangax in our project, fabric is not supposed to run on node. the build process that bundles fabric with all the other dependencies for delivery to the users browser, on the other hand, is.

**Comment by asturur** [comment] 2015-11-16 08:14
can not you add the file as a normal resource? like a img or png or else?

**Comment by gonsfx** [comment] 2015-11-16 08:20
of cause i _could_ add the fabric.js file by simply throwing it into a subfolder.

i won't do it though, because that would mean i would have to manually deal with versioning, which is handled by `npm` for all other packages used. also, i would have to add the file to our repository so our build servers can access it. we don't have any external code in our repository and i plan on keeping it that way :)

**Comment by asturur** [comment] 2015-11-16 08:31
i may be wrong, but i think all deps from fabric npm are related to node use only.

if npm does not provide a "no deps" switch, all the things you are gonna download when installing npm package are of no use for normal browser use.

maybe a browser only npm package would be usefull?

**Comment by gonsfx** [comment] 2015-11-16 08:40
A browser only npm package of `fabric` would definitely be useful for my use-case. I'm not sure if it wouldn't introduce additional complexity for the maintainers of `fabric`, though ;)

**Comment by StephanBijzitter** [comment] 2015-11-16 08:41
@gonsfx We use Codeship to do our building and deployment and it has Cairo installed by default, so we  did not have to deal with an issue like this.

We do have some Ruby developer dependencies, though. These cannot be installed with npm either, so I opted to the following workflow for new developers: `npm install` would install all dependencies, as expected and then you run `sudo grunt setup` (a custom task) which uses `grunt-exec` (module) which handles all the command-line installation further.

**Comment by vkammerer** [comment] 2016-02-08 00:20
npm has become the de-facto package manager for front end dependencies (bower is on its way out), and I would guess that most people who want to use it in a browser app nowadays try to install with npm, as I just did.

I don't know what the solution can be here: 
- as @gonsfx suggests, distribute it under a different name ("fabric-frontend")
- or more simply, just list the requirement to cairo in the installing instructions, and stop including other dependencies in the package.json

**Comment by zonakusu** [comment] 2016-02-25 09:20
Agree with @vkammerer, we don't use bower for dependencies anymore. And I'm quite hesitant of using bower just for Fabric.

**Comment by mguijarr** [comment] 2016-05-02 12:55
I agree with @vkammerer and @zonakusu...

Personally I think a `fabric-frontend` package would be ok.

**Comment by asturur** [comment] 2016-05-02 13:08
We shipped 1.6.1 with optional dependencies. also we added support for node4 node5. You should not have problem if node-canvas fails.

**Comment by mguijarr** [comment] 2016-05-02 13:32
Great! Thanks a lot!

**Comment by limbo-lab** [comment] 2016-05-19 09:26
Maybe it is not the best solution. It just works by manually specifying `--no-optional`. When I install `fabric` using `npm install fabric --no-optional --save`, in `package.json`, there is an dependency entry:

```json
{
  "name": "dir",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "fabric": "^1.6.2"
  }
}
```

The problem is, the next time I run `npm install` to install dependences the '--no-optional' is missing or I have to using `npm install --no-optional` all the time.

**Comment by mguijarr** [comment] 2016-05-20 14:46
You're right @limbo-lab , what I do for the moment is a kind of hack: I install `fabric` with a postinstall script:

    { "scripts": { postinstall: "npm install fabric --no-optional" },
      "name": "dir",
      "version": "1.0.0",
      ...
      "author": "",
      "license": "ISC" }

**Comment by asturur** [comment] 2016-05-20 15:02
If the installation of optional dependencies fails, you should have no problem.
Do you have any?

**Comment by limbo-lab** [comment] 2016-06-02 03:44
@asturur Well, It has no any problems, but, since frontend has nothing to do with the optional dependencies, why not simply extract them out? or I have to use a workaroud like @mguijarr.
