### ISSUE TITLE
Android: Backspace key not working with I-Text

### ISSUE THREAD

**Issue by radykal** [kangax/fabric.js#3641] opened 2017-01-21 12:51 UTC
## Version
1.7.3

A customer reported a bug with Android and I-Text. The backspace key on the smartphone does not work. Can someone confirm this issue?

**Comment by asturur** [comment] 2017-01-21 18:11
duplicate of #3368

**Closed by asturur** 2017-01-21 18:11 UTC

**Comment by AmalkiranCHTS** [comment] 2020-04-03 07:03
I also got a issue with backspace Key press event as unidentified in android with default google keyboard can any1 solve this problem ?
I am using fabricjs textbox on canvas

**Comment by asturur** [comment] 2020-04-03 11:53
What android and what fabric version? can you reproduce it on any existing page on fabricjs.com?

**Comment by AmalkiranCHTS** [comment] 2020-04-03 12:18
We have used fabricjs 1.7.20 version to add i-text objects on canvas. 
On pressing ‘Backspace’ key we are getting event.keyCode == 229 and event.key == "Unidentified" inspected through **"chrome://inspect/#devices"** but this is wrong, for which the backspace key event is not working . 
I have tested with Android’s default keyboard i.e., Google Keyboard(Gboard), private keyboards like ‘SwiftKey keyboard' and ‘fleksy keyboard’.

This issue reproduces in mid-end phones and lower but not in  hight-end/ flagship phones.
Tested in Redmi poco f1,redmi note series almost, honour,Vivo,Oneplus.
Same issue we get.

**Comment by asturur** [comment] 2020-04-03 14:44
seems definitely an android issue here, not a fabricJS one.
You could try with newer version that do not use the backspace key directly anymore, and this could fix the issue for you.
This happen on version 2+ i believe, the one with onInput event handling.

**Comment by AmalkiranCHTS** [comment] 2020-04-03 14:56
sure thnku
