### ISSUE TITLE
Drawing off left edge with Apple Pencil results in line being erased

### ISSUE THREAD

**Issue by homerlex** [kangax/fabric.js#4036] opened 2017-06-26 17:32 UTC
## Version
1.7.13

- Hit http://fabricjs.com/freedrawing with iPad Pro (I tested with Safari and Chrome)
- Using an Apple Pencil draw from somewhere in the canvas  to outside the left edge and off the screen. 

Sometimes, as soon as the pencil exits the active screen area, the drawn line will disappear.  I can repro more consistently when I draw slowly.  I have only been able to repro using the pencil.  I cannot repro using my finger to draw.

I did some debugging and when this occurs I find there is at lease on point in the _points array that have properties like:
```
x: NaN
y: NaN
```

I tracked it down further to find that in _getPointer event.changedTouches[0].clientX (and clientY) are undefined.

My workaround on my local branch for now is to just not add any points to the _points array that have invalid x and/or y values.

Perhaps there is a more elegant solution.

**Comment by asturur** [comment] 2017-07-02 10:13
duplicate of #3946

**Closed by asturur** 2017-07-02 10:13 UTC
