### ISSUE TITLE
LoadFromJson Load flipY Image ONLY with smartphone

### ISSUE THREAD

**Issue by manu89ftt** [kangax/fabric.js#4684] opened 2018-02-06 18:00 UTC
Hi,
I've a problem with the function load from json, if I would like to load for example this object 

`{"type":"mamba-image","version":"2.0.0","originX":"left","originY":"top","left":346.99,"top":251.1,"width":392,"height":608,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":0.56,"scaleY":0.56,"angle":4.91,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"crossOrigin":"","cropX":0,"cropY":0,"src":"http://10.10.45.158/products/438646/01-large.jpg","filters":[{"type":"RemoveColor","color":"#FFFFFF","distance":0.08}],"idProduct":"438646","currentImg":"01","coords":[]}`

(mamba image is an extension on image with another params)

On pc I see the object correctly, but with smartphone (Samsung Galaxy S8 with Chrome) I see the object in the correct position but it is rendered as if flipY were true. 

For example if I change "flipY" to true I see the object correctly on mobile but flipped on desktop.

**Comment by jilster** [comment] 2018-02-06 18:17
I see the image is scaled down. Are you using Chrome 64 on your desktop? Sounds a bit like https://github.com/kangax/fabric.js/issues/4659

**Comment by manu89ftt** [comment] 2018-02-08 14:43
Yes It's the same issue.... 👎

**Comment by asturur** [comment] 2018-02-10 11:02
duplicate of #4659

**Closed by asturur** 2018-02-10 11:02 UTC
