### ISSUE TITLE
Incurrect click point when scaled down with cssOnly setDimensions

### ISSUE THREAD

**Issue by Exlord** [kangax/fabric.js#3993] opened 2017-06-10 07:19 UTC
## Version
1.7.12 (latest master)

## Test Case
https://jsfiddle.net/Exlord/424pvh1h/

## Steps to reproduce
Open the console and Try clicking on the center of the red box in the small canvas. see the positions in the log.

## Expected Behavior
Do the same thing on `c1`(bigger) canvas, The position is always the same.
Just like `c1`, The position to be the same(almost same with small margin of error) always.

## Actual Behavior
Each click gets a very different position!

`c2`(small canvas) is the exact copy of `c1`(big canvas), which is scaled down with `canvas.setDimensions({ width: width + 'px', height: height + 'px' }, { cssOnly: true });`

**Comment by asturur** [comment] 2017-06-10 07:23
duplicate of #3959

**Closed** 2017-06-10 22:43 UTC
