### ISSUE TITLE
Weird char widths bug when changing IText fonts

### ISSUE THREAD

**Issue by ajck** [kangax/fabric.js#2614] opened 2015-11-09 20:59 UTC
Hi,

I've got a canvas with a few i-texts on it each in a different webfont. I save it using json.stringify, reload it using canvas.loadFromJSON and do a canvas.renderAll()

Fonts are now not set correctly and each text appears in the default font (Times New Roman I think). But, that's not the bug (I can work around it so fonts appear correctly)

The bug is when I then reload each itext's font (which is in the itext object's fontFamily already) the character widths are wrong - they remain set to what the default font's char widths were. Furthermore, any new itexts I create on that canvas with the same fonts also have the wrong char widths. Note that the itext's boundary box and controls are all wrong too as they seem based on the wrong char widths, and typing in a certain place in the itext causes the typed characters to appear somewhere else, where they would be if I was still using the default font it displayed when first loaded.

The weird thing is if instead of trying to set the font in an itext to what it was previously (and what the fontFamily says) but instead use an entirely new font, the char widths are all perfect!

So, you would think I simply call setCoords on the itext and it recalculates boundary box and char widths? Nope, has no effect.

I have tried lots of different things to work around but nothing works. Was going to try actually copying each itext on load and destroying the original but don't know how to do this without copying the error with char widths.

Problem looks like char widths are being cached on a per font basis (rather than per itext) on the canvas, but are not being updated when I change font from the default so old ones get used rather than new ones (but this only happens for fonts already being used in the itexts already on canvas).

I am using Google's Web Font loader to load fonts but convinced this is not the problem...

Many thanks,
Alex

**Comment by asturur** [comment] 2015-11-09 21:48
the problem is always the same, using the font before it is completely loaded.
Yes the chars width are cached using some parameters (font family, font size and bold/italic).

**Comment by ajck** [comment] 2015-11-09 23:07
@asturur Thanks. Yes I thought that was the problem, but I've made sure the font is definitely fully loaded - not only is it visible but I can type in the itext box with the correct font etc. *then* apply setCoords() and nothing changes. There must be a way to refresh or update the chars width cache?

**Comment by jedsmithobd** [comment] 2015-11-17 19:03
I can confirm that if the font is fully loaded before I try and use it then the width is calculated properly. Like @ajck mentions though there doesn't seem to be a way to tell it to recalculate. Generally speaking it seems that this just means that we have to make sure that we are careful to always fully load the font before creating any elements in the canvas which use the font. What we are running into is that the data is being dynamically loaded and there are dozens of fonts which could be used in the application and it would be nice to do a preliminary rendering showing the basic text in the default font and then rendering with the new fonts as they are loaded. 

Looking through the code it appears that there are two things which would need to be addressed to allow for recalculating the width.

When rendering `this.shouldClearCache()` is called to see if any properties affecting the dimensions have changed to determine if the dimensions need to be re-rendered. However, the properties matching the `_dimensionAffectingProps` aren't changed because the same font name and styles are being used the change is the different real font being used. So we would need another way to specify that the cache should be cleared.

The second thing is that when calculating the width it uses a cache in `this._charWidthsCache[cacheProp]` which can be ignored if the object has `this.caching` set to `false`. but it would be nice to clear the cache for the font after loading a new font.

@arturur I am willing to create a method to clear a font for recalculation of fonts, either all or individually. If this would be something of value to add to fabric I can make something and add a pull-request.

**Comment by kangax** [comment] 2015-12-27 16:46
@jedsmithobd I think that would be great; please feel free to send a PR

**Comment by asturur** [comment] 2015-12-27 16:52
it would be nice also to move the cache from per iText object to fabric object level. If i'm not too confused now, i think we have cache per iText object. That means that every itext with same font keep its copy of cache.

**Comment by ajck** [comment] 2015-12-28 14:45
@jedsmithobd that would be great, thank you

**Comment by raffareis** [comment] 2016-03-09 22:24
was this implemented? does anyone have a workaround so far?

**Comment by asturur** [comment] 2016-04-11 11:41
duplicate of #2612

**Closed by asturur** 2016-04-11 11:41 UTC
Labels: possible_feature
