### ISSUE TITLE
[SVG IMPORT] Shapes with transformMatrix have misplaced and/or stretched controls.

### ISSUE THREAD

**Issue by saeschdivara** [kangax/fabric.js#1520] opened 2014-07-23 08:31 UTC
I tried to load an svg which was created by fabric.js (toSVG). Loading was possible but the selection area of the canvas objects are totally wrong (as can be seen in the screenshot)
![screen shot 2014-07-23 at 10 13 56](https://cloud.githubusercontent.com/assets/4942808/3670275/a38b6500-1241-11e4-94c8-22283e101047.png)

The fabric.js version is 1.4.9

In the fiddle you cannot even select the objects: http://jsfiddle.net/saskyrar/L8cmw/2/

Here is the svg:

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="800" height="700" style="background-color: rgb(255, 255, 255)" xml:space="preserve">
    <desc>Created with Fabric.js 1.4.5</desc>
    <defs></defs>

    <circle
        cx="0"
        cy="0"
        r="75"
        style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: blue; opacity: 1;"
        transform="translate(521 203)" id="2b0a303e-857e-9431-e2c9-d67a59759422"/>

    <rect
        x="-150"
        y="-100"
        rx="0"
        ry="0"
        width="300"
        height="200"
        style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: blue; opacity: 1;"
        transform="translate(185 229)" id="09e6bb6e-8970-57b2-bec4-bcb77787efc5"/>
</svg>
```
##

**Comment by defue** [comment] 2015-02-04 16:31
I've created a simple demonstration of the bug using the latest FabricJS version (1.4.13):
http://jsfiddle.net/4793dtua/

In the example if you click on red rectangle you will see that selection box is misplaced.

Hope it helps to debug the issue.

**Comment by asturur** [comment] 2015-02-04 16:54
The bug is very well know, i recently change some function with this topic in mind, so i hope i can draw the correct bounding box.

**Comment by goldguy23** [comment] 2015-03-07 15:27
This is a very simple fix.  Open file in illustrator.  Copy and paste. This will center the image in the middle of the art board. Select art board and make the art board the exact size of the image. This will center the image in the middle of the art board and your Mis aligning issues will disappear.  I have dealt with this for a long time and this is how you fix it.  Your images are not centered on the art board so it is way off

**Comment by aearly** [comment] 2015-06-05 01:47
I can reproduce this with simple code:

```js
    var image = document.createElement("img");
    image.src = "http://i.imgur.com/MwUmn5S.jpg";
    var fabricImage = new this.fabricJs.Image(image, {
      width: 300,
      height: 300,
      selectable: true
    });
    fabricCanvas.add(fabricImage);
    fabricCanvas.setActiveObject(fabricImage);
    fabricImage.setTransformMatrix([1, 0, 0, 1, 200, 200]);
    fabricImage.setCoords();
```

The fabric controls will be offset by (200,200).

**Comment by pranavgawri** [comment] 2015-08-07 13:14
Using Fabric version 1.6.0.. and the problem still exists with any element that has transformation. Following is the detailed scenario:
Any SVG having elements which have transformation matrix on them, when parsed and elements are added individually then the bounding box is misaligned as (missing transformation).
Temp fix is as suggested by asturur:
object.left = object.transformMatrix[4];
object.top = object.transformMatrix[5];
object.transformMatrix =[1,0,0,1,0,0];
object.setCoords();

But would be nice if its handled by fabric directly.
Also if any text has transformation matrix... then the bounding box of the text is incorrect.

**Comment by asturur** [comment] 2015-08-07 14:04
yes we are working on it.

**Comment by pranavgawri** [comment] 2015-08-07 16:00
Ok thanks.
Also, in the same situation as above, I am adding a text which has a transformation matrix (rotated) then the bounding box is incorrect (its smaller in width, height is fine though)
Following is the SVG of the element I am adding:
```
<g transform="matrix(1.2371 -0.112798 0.14095 0.990017 -60.7314 74.2014)">
   <text x="100" y="68.9637"  fill="white" font-weight="normal" font-size="39.3334" font-family="Anton">2015</text>
  </g>
```
and the width of bounding box is incorrect. 

Kindly let me know if this is also in pipeline. Thanks

**Comment by asturur** [comment] 2015-08-07 16:05
It is smaller because that transform matrix is not "rotated" but is scaled + rotated + skewed a bit + translated.

orizontally is streched by something like a factor of 1.2 so, the bounding box is original size while the text is streched.

**Comment by pranavgawri** [comment] 2015-08-07 17:14
Yup that's correct... if I remove the skewiness :) then the bounding box is fine, so guess that needs some handling.

Thanks for confirming the issue. Kindly let me know if the fix for this will be available sometime soon? or if you can suggest me some patch to use in the mean time?

thanks.

**Comment by asturur** [comment] 2015-08-07 17:32
The fix is not finished otherways i would happily release it.
handling the part 4 and 5 ( translation ) of transformMatrix is what is missing.

**Comment by pranavgawri** [comment] 2015-10-05 17:06
Hi, were you able to work on this one? looking forward for fix on this one.

thanks.

**Comment by asturur** [comment] 2015-10-19 04:43
![image](https://cloud.githubusercontent.com/assets/1194048/10569871/b28e3f0a-762c-11e5-935c-f8dd7ea3e265.png)


look! an ungrouped svg behaving normally

**Comment by asturur** [comment] 2015-10-19 04:45
![image](https://cloud.githubusercontent.com/assets/1194048/10569887/e8905e76-762c-11e5-8539-75b369967c21.png)

Still some gradient job to do.
This is a long wip, but i wanted to show progress so you do not loose hope :)

**Comment by asturur** [comment] 2015-10-19 04:50
This is ungrouped test svg ( one element per kind of shape ) with transform and without
![image](https://cloud.githubusercontent.com/assets/1194048/10569946/a48ba5b8-762d-11e5-9d06-c22a7cb0d422.png)

this is original
![image](https://cloud.githubusercontent.com/assets/1194048/10569954/ae962344-762d-11e5-83cd-3b0b54c54336.png)

so as you see something is still not perfect.

**Comment by asturur** [comment] 2015-10-19 05:05
shapes are done.
![image](https://cloud.githubusercontent.com/assets/1194048/10570105/a6495114-762f-11e5-98a7-996b602ba8a3.png)

![image](https://cloud.githubusercontent.com/assets/1194048/10570110/bab52556-762f-11e5-8537-afd8b5d2c328.png)

text is missing, gradients and patterns are missing.

**Comment by pranavgawri** [comment] 2015-10-19 05:41
Hey Thanks a lot for keeping me updated! :) I appreciate that work is in progress on it.
By any chance, the progress that you have made, is available to pull or in a version?

**Comment by asturur** [comment] 2015-10-19 07:26
Not yet, lot of cleaning is necessary.
Be aware that i will not propose an half version to be fast. When this is done, pathGroup will not be used, ungrouped svg will be different shapes, grouped svg will be a normal group. So this will bring ***big backward compatibility problem*** this is a 2.0 feature. I will share code if you want to use in your own way you are free to do so.

**Comment by kangax** [comment] 2015-10-19 12:23
I marked it for 2.0 (@asturur feel free to do it yourself in the future)

**Comment by GeorgeNarcis** [comment] 2015-10-22 18:58
I' m facing a kind of similar problem , but I'm not sure if the root cause is the same.
I am setting various viewport transforms on my fabric canvas instance: translate+scale+rotate.

At some point I am loading shapes to canvas from SVG. If the rotate transform is not set on my canvas viewport, the controls are looking fine. The scale and translate transforms seems to work as expect but when the rotate transformation is added the controls are broken, there seems that some kind of rotation is applied to them and the effect is very strange, they look totally broken.

Am I seeing the same problem as described in this bug or is a new problem (since i don t set transformmatrix on the shape but instead the transform is applied on canvas viewport)? I am using fabric 1.5.0, so any help or possible workaround for my problem would be highly appreciated.

**Comment by asturur** [comment] 2015-10-22 19:25
if you are talking about viewportTransform, rotation is not supported. all viewport transform are just scaling and translate. if you wanna be sure you can open a different issue adding a fiddle with a code sample.

**Comment by asturur** [comment] 2015-10-28 12:54
Currently looking to complex svg with both path and other shapes and GRADIENTS.
Positions of shapes looks correct, also control boxes are.
Gradients or colors look like a bit off sometimes.
So please for whom is interested in this fix contribute some strange svg you may have somewhere on your harddisk if opening a little bounty is not in your possibilties.

**Comment by DeDuke** [comment] 2016-09-15 13:53
is it possible to place the selection area via object-options?

**Comment by cgatian** [comment] 2017-03-03 20:39
I created a simple example of importing text and converting it to an IText.  The selection box is incorrect  when you attempt to edit. I am assuming this is the same issue?  
Thank you, and awesome library.

http://codepen.io/cgatian/pen/yMJLvQ

**Comment by krishnaisdinesh** [comment] 2017-04-05 07:59
Hi,

In lates released 7.9 still loading sg without group scatter in canvas. Not at actual position. 
`fabric.loadSVGFromURL("file.svg",function(objects,options){
    canvas.add.apply(canvas, objects);
});
`
Original svg

![screenshot from 2017-04-05 13-27-22](https://cloud.githubusercontent.com/assets/19422873/24695503/bc583672-1a03-11e7-9b1f-a18ac1d0a14a.png)

After upload 
![fireshot capture 078 - my yii application_ - http___localhost_diy_web_logo_edit](https://cloud.githubusercontent.com/assets/19422873/24695522/c955342e-1a03-11e7-91d8-5855ebb9f0aa.png)

I need to change color or edit elements of svg. So cann't group.

**Comment by asturur** [comment] 2017-04-05 08:06
there are some precision problem removing the transform matrix, that is why
we did not develop it further for now

On Apr 5, 2017 09:59, "Dinesh kumar krishna" <notifications@github.com>
wrote:

Hi,

In lates released 7.9 still loading sg without group scatter in canvas. Not
at actual position.
fabric.loadSVGFromURL("file.svg",function(objects,options){
canvas.add.apply(canvas, objects); });
Original svg

[image: screenshot from 2017-04-05 13-27-22]
<https://cloud.githubusercontent.com/assets/19422873/24695503/bc583672-1a03-11e7-9b1f-a18ac1d0a14a.png>

After upload
[image: fireshot capture 078 - my yii application_ -
http___localhost_diy_web_logo_edit]
<https://cloud.githubusercontent.com/assets/19422873/24695522/c955342e-1a03-11e7-91d8-5855ebb9f0aa.png>

I need to change color or edit elements of svg. So cann't group.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kangax/fabric.js/issues/1520#issuecomment-291784363>,
or mute the thread

**Comment by asturur** [comment] 2017-05-30 11:48
For who may be still interested, this thing is finally solved in #3969.
I m really excited about it.

**Comment by pranavgawri** [comment] 2017-05-30 13:36
Thanks!

**Comment by asturur** [comment] 2017-06-01 09:01
i m closing this issue.
Just to be clear, SVG import has been rewritten to absorb the transform matrix and respect controls.
So transform matrix get translated to left,top,scale,skew, etc etc.

Setting the transformMatrix directly yo an object will still give out of box controls.

transformaMatrix will stay as object property for who wants to draw custom things and is not in need of controls, for all other people a new method will be created ( to be named ) that will take as an input the transformMatrix, and mix it with current object properties.

This is already possible using calcTransformMatrix, multiplyTransformMatrices and qrDecompose, but maybe there will be a oneline helper

**Closed** 2017-06-01 09:02 UTC
Labels: bug
