### ISSUE TITLE
loadSVGFromString unexpected text translation behavior

### ISSUE THREAD

**Issue by malerba118** [kangax/fabric.js#4566] opened 2017-12-17 22:23 UTC
I'm encountering this weird behavior in my application when trying to export a group containing text

![screen shot 2017-12-17 at 4 12 20 pm](https://user-images.githubusercontent.com/5760059/34084417-8d973d5e-e345-11e7-9314-9156fd7c7c29.png)

To export as svg I first move the group to a new canvas with the same dimensions as the group and center it on the new canvas. This way I can export only a selection instead of the entire canvas. Everything works as expected when subsequently importing the exported svg except text objects always get shifted so that the bottom left of the text is at the center of the original.

In the browser the exported svg renders as i would expect it to. Here it is:

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="100" height="100" viewBox="0 0 100 100" xml:space="preserve">
<desc>Created with Fabric.js 2.0.0-beta7</desc>
<defs>
</defs>
<g transform="translate(50 50)" style="">
	<g transform="translate(0 0)" style="">
	<path d="M 299.04483 44.87069 c -30.36205 0 -59.36438 5.9469 -87.007 17.84069 c -27.64262 11.8938 -51.46009 27.82192 -71.45242 47.78437 c -19.99233 19.96245 -35.92046 43.77993 -47.78437 71.45242 c -11.86391 27.6725 -17.81081 56.67483 -17.84069 87.007 c -0.02988 30.33217 5.91701 59.3345 17.84069 87.007 c 11.92368 27.6725 27.8518 51.48997 47.78437 71.45242 c 19.93257 19.96245 43.75004 35.89057 71.45242 47.78437 c 27.70238 11.8938 56.70472 17.84069 87.007 17.84069 c 30.30228 0 59.30462 -5.9469 87.007 -17.84069 c 27.70238 -11.8938 51.51986 -27.82192 71.45242 -47.78437 c 19.93257 -19.96245 35.86069 -43.77993 47.78437 -71.45242 c 11.92368 -27.6725 17.87058 -56.67483 17.84069 -87.007 c -0.02988 -30.33217 -5.97678 -59.3345 -17.84069 -87.007 c -11.86391 -27.6725 -27.79203 -51.48997 -47.78437 -71.45242 c -19.99233 -19.96245 -43.80981 -35.89057 -71.45242 -47.78437 c -27.64262 -11.8938 -56.64495 -17.84069 -87.007 -17.84069 z M 568 269 c 0 48.80042 -12.02827 93.80559 -36.08482 135.0155 c -24.05655 41.20991 -56.68977 73.84314 -97.89968 97.89968 c -41.20991 24.05655 -86.21508 36.08482 -135.0155 36.08482 c -48.80042 0 -93.80559 -12.02827 -135.0155 -36.08482 c -41.20991 -24.05655 -73.84314 -56.68977 -97.89968 -97.89968 c -24.05655 -41.20991 -36.08482 -86.21508 -36.08482 -135.0155 c 0 -48.80042 12.02827 -93.80559 36.08482 -135.0155 c 24.05655 -41.20991 56.68977 -73.84314 97.89968 -97.89968 c 41.20991 -24.05655 86.21508 -36.08482 135.0155 -36.08482 c 48.80042 0 93.80559 12.02827 135.0155 36.08482 c 41.20991 24.05655 73.84314 56.68977 97.89968 97.89968 c 24.05655 41.20991 36.08482 86.21508 36.08482 135.0155 z" style="stroke: rgb(123,125,123); stroke-width: 0; stroke-dasharray: none; stroke-linecap: round; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(223,117,117); fill-rule: nonzero; opacity: 1;" transform="translate(0 -1.4211e-14) scale(0.18587360594795538 0.18587360594795535) translate(-299, -269) " stroke-linecap="round"></path>
		<g transform="translate(0 0)">
		<text xml:space="preserve" font-family="Raleway" font-size="40" font-style="normal" font-weight="normal" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(223,117,117); fill-rule: nonzero; opacity: 1; white-space: pre;">
			<tspan x="-41.32" y="12.57">Blah</tspan>
		</text>
	</g>
</g>
</g>
</svg>
```

I've spent a solid day on this with no real leads. I mostly fooled around with originX and originY, but couldn't get anything to budge.

**Comment by asturur** [comment] 2017-12-17 22:26
Text tspan are not supported yet.
duplicate of
#1280

**Closed by asturur** 2017-12-17 22:26 UTC
