### ISSUE TITLE
Implement HTML5 Pointer Events API

### ISSUE THREAD

**Issue by Exlord** [kangax/fabric.js#4639] opened 2018-01-21 11:39 UTC
Feature request : Implement HTML5 Pointer Events API

Since chrome changed the stylus events to touch instead of mouse, I encountered some problems with my whiteboard(paint) app.
This one https://github.com/kangax/fabric.js/issues/4610 for instance. 

Another problem is that chrome fires `touchmove` if the touch has moved at least some pixels from the `touchstart` point. You can test this in chrome's devtools device emulator, if you press and hold mouse button `touchstart` fires, BUT in order for `touchmove` to fire you need to move the mouse until the circle(chrome shows the mouse cursor as a circle) moves out of the `touchstart` start point, this is ok when using fingers but not with stylus(Pen). The stylus needs to be precise because users use it to write small texts.

There is a new Pointer Events API which fires `pointerdown` and `pointermove` events for both mouse and touch and pen.

https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events
https://mobiforge.com/design-development/html5-pointer-events-api-combining-touch-mouse-and-pen

**Comment by asturur** [comment] 2018-01-21 14:34
duplicate of #4134

**Closed by asturur** 2018-01-21 14:34 UTC
