### ISSUE TITLE
Issue with touch events on IE11

### ISSUE THREAD

**Issue by cannontechnology** [kangax/fabric.js#1926] opened 2015-01-12 00:00 UTC
Touch events are not working in IE11.   Try to drag and drop via touch in the demo:  http://fabricjs.com/touch-events/   

Thanks,

Matt

**Comment by kangax** [comment] 2015-01-12 09:44
Which device are you seeing this on?

**Comment by kangax** [comment] 2015-01-12 10:31
Actually looks like duplicate of #1896

**Closed by kangax** 2015-01-12 10:31 UTC
Labels: needs_confirmation
