### ISSUE TITLE
Image Clipto interactive area issue

### ISSUE THREAD

**Issue by BharatPatel1** [kangax/fabric.js#1569] opened 2014-08-06 06:19 UTC
Once we set clipto area of the image on crop operations than outside the clipto area is also selectable and with case of object layering on selection outside the crop area of image top object. Refer the attached image.

http://jsfiddle.net/86bTc/16/

![crop_selection](https://cloud.githubusercontent.com/assets/7869021/3822915/86379c1c-1d31-11e4-95c3-fe0183b2c751.jpg)

**Comment by asturur** [comment] 2015-04-06 12:46
in this particular case, you should just change the image width and height and use the preserve aspect ratio properties.


one way to achieve this for general use case is to render objects on separate canvas and check for pixel trasparency. now than transform point works as expected we may think of it.

**Comment by asturur** [comment] 2016-04-26 01:14
This issue derive from a particular implementation of crop functionality, that a this point we still do not support.
I mark this as duplicate of #2663 and i close it.
Semplifying the code of the aspect ratio support, we may introduce a method for cropping images easily.

**Closed by asturur** 2016-04-26 01:14 UTC
Labels: needs_confirmation
