### ISSUE TITLE
Use uuCanvas instead of explorercanvas

### ISSUE THREAD

**Issue by zhangzhzh** [kangax/fabric.js#558] opened 2013-04-12 04:47 UTC
1. make all demos work in IE 6-8 is very important, otherwise it's very frustrating.

2. maybe it's better choice to use uucanvas(http://uupaa-js-spinoff.googlecode.com/svn/trunk/uuCanvas.js/README.htm) instead of  excavas, especially from performance point, uucanvas has multiple backend(Silverlight, Flash and VML in IE, and other browsers do rendering with HTML5::Canvas.). Additionally, it's less bugs, more powerful(such as radial gradient, more text function, etc.), and work better in IE 6-8.

3. add the function of convert text with special fonts(downloaded or custom) into image. As of design, using special fonts on client machine and share with those without the fonts is very common. fabric should have the ability to convert text content or div to image.

Question: 
Can we change the Explorer Canvas to uucanvas by myself? Is it easy to do it?

**Comment by asturur** [comment] 2016-05-23 10:14
duplicate of #249

**Closed by asturur** 2016-05-23 10:14 UTC
Labels: possible_feature
