### ISSUE TITLE
Skew Object and Fabric Control 

### ISSUE THREAD

**Issue by ashishbhattb** [kangax/fabric.js#2172] opened 2015-05-05 14:02 UTC
Please check the below Fabric Js Example, How can i fix the control in skew position ?

Fabric js is not supporting Skew, any one has tried to fix ?

http://jsfiddle.net/Rq7hk/41/

Please guide me if any one has get success in this issue 

Regards,
Ashish Bhatt

**Comment by asturur** [comment] 2015-05-05 14:09
We are working on that, there is not an immediate fix for control box, that is really the only thing we need to skew properly.

**Comment by kangax** [comment] 2015-05-06 10:01
Duplicate of #726

**Closed by kangax** 2015-05-06 10:01 UTC
