### ISSUE TITLE
Circular object controls (corners)

### ISSUE THREAD

**Issue by cskwg** [kangax/fabric.js#885] opened 2013-10-01 13:14 UTC
For my current projec, fabric had to be slightly modified to allow round corners and to distinguish cornerColor and cornerFill. The reason was to make it more appealing for touch devices. 
May I submit the complete file, so that somebody may integrate the changes into the source? It is a version 1.3.7 with  a handfull of changes.

**Comment by JRVisualsLLC** [comment] 2015-06-05 18:50
@cskwg can you share how you accomplished this?

@kangax curious if this should be re-opened now that there's more info.

**Comment by kangax** [comment] 2015-06-05 21:30
@JRVisualsLLC sure, I marked it as possible feature. We'll see if we get any more requests for this.

**Comment by onassar** [comment] 2016-01-21 01:51
+!

**Comment by asturur** [comment] 2016-04-13 12:25
i think this should go toghter with customizable controls, is is definitely a subset of it.
(something i would like to start doing)
duplicate of #1947

**Closed by asturur** 2016-04-13 12:25 UTC
Labels: possible_feature
