### ISSUE TITLE
Display Controls of the paths

### ISSUE THREAD

**Issue by mariusturcu1** [kangax/fabric.js#2470] opened 2015-09-08 14:31 UTC
Hi, I run some tests with some svg file and i found something interesting.
If i load the svg from here http://fabricjs.com/assets/127.svg as load without group on the http://fabricjs.com/kitchensink/ everything seems is ok, but there is a problem with the controls of the paths. All controls seems to be a little to left and too top.
 I found a function called _setPositionDimensions() and it seems like from here the problem is apearing .the pathOffset of the object create the problem.
You know a solution for this? I also tried to run functions like setCoords() or to change the origin of the object but the result is the same.
Thanks!

**Comment by asturur** [comment] 2015-09-08 14:42
duplicate of #1520.
Please read there.
No fix yet.
The problem comes from the value of transformMatrix.

**Closed by asturur** 2015-09-08 14:43 UTC
