### ISSUE TITLE
Take snapshot on iOS devices does not work

### ISSUE THREAD

**Issue by mbaudry** [kangax/fabric.js#3297] opened 2016-09-29 15:28 UTC
I have an issue when I try to take a snapshot of a drawing on my iPhone.

http://jsfiddle.net/qp8x7a5w/36/

As you can see, I set the option `enableRetinaScaling` to false. When the snapshot is taken, it seems to be smaller than the original... I don't know why.

And if I try to take a snapshot with the option `enableRetinaScaling` set to true, it does not work, and I have the message **Canvas area exceeds the maximum limit (width * height > 16777216)** (may be because I set a multiplier to 4, and it's too much for the device).

So, I have a problem because I need a snapshot 4 times bigger than the original, but with or without the `enableRetinaScaling` option, there is an issue.

Do you have any idea ?

Thank you for your help !

**Comment by asturur** [comment] 2016-10-01 07:55
the message is clear, in that device you have some limit of canvas size. you cannot have a canvas that is bigger than 4k x 4k
i should check, maybe the canvas created for export is automatically rendered in retina enabled.

**Comment by asturur** [comment] 2016-10-02 11:09
duplicate of #3152

**Closed by asturur** 2016-10-02 11:09 UTC
