### ISSUE TITLE
contextify should be removed

### ISSUE THREAD

**Issue by farfromrefug** [kangax/fabric.js#3366] opened 2016-10-24 09:31 UTC
the contextify module does not compile with the latest nodejs. This is normal as it is not maintained anymore as it is part of nodejs.
I think you should remove the dependencies. 
For me it breaks npm install as it will create an error and stop the build process.

Thanks

**Comment by asturur** [comment] 2016-10-24 09:51
which version of fabricjs are you downloading and on wich node version?  i can succesfully build on node 4 5 and 6.

**Comment by farfromrefug** [comment] 2016-10-24 10:05
yes you are right i should have mentionned that i build fabric within electron 1.4.3 which uses node 6.5.0

And here is the contextify build error:
```
../src/contextify.cc:150:16: error: no member named 'SetAccessCheckCallbacks' in 'v8::ObjectTemplate'
        otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
        ~~~~~  ^
```

**Comment by asturur** [comment] 2016-10-24 10:12
![image](https://cloud.githubusercontent.com/assets/1194048/19641906/11cb315a-99e3-11e6-8428-2febae4909a0.png)

i can build fabric in node 6.8.1  in travis enviroment.
Are you shure is not a electron problem?

**Comment by asturur** [comment] 2016-10-24 10:13
![image](https://cloud.githubusercontent.com/assets/1194048/19641943/4f876a72-99e3-11e6-8f2e-20769a0e3bc0.png)

also contextify is not our direct dependency.

**Comment by farfromrefug** [comment] 2016-10-24 10:39
yes you are right it's not you directly. But you require a very old version of jsdom which still requires contextify

**Comment by asturur** [comment] 2016-10-24 10:43
i know, but to switch to jsdom latest, i have to dump node before 4. Something that is gonna happen soon or later. I belive that the problem is elesewhere, electron is a headless browser, i do not understand why it should require jsdom. Maybe you should prebuild fabricjs and just include it in your app.

**Comment by asturur** [comment] 2016-10-24 10:45
```--no-optional``` when you install should do the trick. in electron you do not need node-canvas also. Please check and close this issue.

**Comment by asturur** [comment] 2016-10-26 08:28
the new fabric2 branch, has just node 4 support and newer xmldom. I guess we can close this.

**Closed by asturur** 2016-10-26 08:28 UTC
Labels: needs_confirmation

**Comment by farfromrefug** [comment] 2016-10-26 12:10
@asturur i can't use --no-optional because i need optional for other modules...
Will try the new fabric2 branch, thanks

**Comment by asturur** [comment] 2016-10-26 13:17
fabric2 is in beta as of now, could have lot of problems, i m currently writing it and planning to release it as soon as i complete the object caching for the 1.x branch and new coordinate system in groups for 1.x branch.

**Comment by samael205** [comment] 2016-10-26 13:23
How do you go with the new coordinate system?.
I have to prove anything more that vesion post for my project

**Comment by asturur** [comment] 2016-10-26 13:24
Inside groups the coordiantes of objects will not be affected by canvas zoom and padding.
Actually they are and targeting inside a group or with transparency inside a group is very complicated.
Also bounding box of object is affected by zoomlevel, while it should not.

**Comment by samael205** [comment] 2016-10-26 13:27
Yes. I have this problem (Also bounding box of object is affected by zoomlevel, while it should not.) when i select programatically all object, and i try to fit all objects in the canvas with zoomToPoint, calculating the bounding box.

**Comment by ahmetcetin** [comment] 2016-11-21 14:07
@farfromrefug: could you install fabric finally? I'm trying to dockerize my app running on node with fabric, no chance so far. When I tried fabric2 branch, it gives the same error as in #3342 (Cannot read property 'devicePixelRatio' of undefined). When I use v1.7.0, simply contextify doesn't compile (running on node 6.9.1, tested on Ubuntu 16.04, debian wheezy, and node docker image). I also tried to deploy on aws elasticbeanstalk, it fails as well. It works locally on my mac, but I try to deploy on server, just crashes thanks to contextify. @asturur any idea?

**Comment by asturur** [comment] 2016-11-21 15:05
to make it work on the travis build we have:

```env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgif-dev libpng-dev libjpeg8-dev libpango1.0-dev libcairo2-dev```

does it help?
if travis on ubutu can run it, you can run it.

**Comment by ahmetcetin** [comment] 2016-11-21 16:19
Thank you @asturur, it was kinda helpful to compile contextify, the version of g++ and node version was important (with node 6.5, it compiles successfully, but with node 6.9.1 fails) , i don't get any more errors during npm install, and it looks both npm-canvas and contextify compiles without an error, but later I still get "/usr/src/app/node_modules/contextify/build/Release/contextify.node: invalid ELF header" error. Error stack is below:

`/usr/src/app/node_modules/bindings/bindings.js:83
         throw e
         ^
 
 Error: /usr/src/app/node_modules/contextify/build/Release/contextify.node: invalid ELF header
     at Error (native)
     at Object.Module._extensions..node (module.js:583:18)
     at Module.load (module.js:473:32)
     at tryModuleLoad (module.js:432:12)
     at Function.Module._load (module.js:424:3)
     at Module.require (module.js:483:17)
     at require (internal/module.js:20:19)
     at bindings (/usr/src/app/node_modules/bindings/bindings.js:76:44)
     at Object.<anonymous> (/usr/src/app/node_modules/contextify/lib/contextify.js:1:96)
     at Module._compile (module.js:556:32)
`

**Comment by asturur** [comment] 2016-11-21 16:38
invalid ELF header no idea.
Can it be a x86 vs x64 thing?
Our travis run on node 6.9.1

**Comment by ahmetcetin** [comment] 2016-11-22 17:09
ok, it works, indeed, compiling contextify with node 6.9.1 fails, but as it's already part of node, jsdom, therefore fabricjs, doesn't require it anyways. apparently i had problem with dockerfile, i fixed and it works like a charm. thank you guys for such a great work. 

btw, about supporting node version before 4, node foundation already dropped support for 0.10, and they are dropping support for 0.12 end of december'16 (https://github.com/nodejs/LTS). JM2C, i think it's proper to follow footsteps of the foundation when considering the support of node versions.
