### ISSUE TITLE
custom build not working

### ISSUE THREAD

**Issue by JamesWPritchett** [kangax/fabric.js#3558] opened 2016-12-20 22:21 UTC
## Version
1.7.2

## Steps to reproduce
Download Custom build including only Interaction

## Expected Behavior
Page should load
## Actual Behavior
Site fails to load and the following error is in the console:
Chrome: Uncaught TypeError: Cannot read property 'object' of undefined
Firefox: TypeError: fabric.util is undefined
IE/Edge: Unable to get property 'object' of undefined or null reference

The reported line is "var extend = fabric.util.object.extend".  I tested and fabric.util is not defined before attempting to create the StaticCanvas class.  Note that this works if you don't include Interaction, leading me to believe that the error is that fabric.Canvas is being defined BEFORE fabric.StaticCanvas has been created.

I included the output from the custom build download.

[fabric.zip](https://github.com/kangax/fabric.js/files/664903/fabric.zip)

**Comment by asturur** [comment] 2016-12-20 23:42
i may have inserted the file in the wrong order. i have another email about that also. I will check asap.

**Comment by JamesWPritchett** [comment] 2016-12-21 01:16
Is there a way of getting the previous version's full build?  It looks like the Custom Build page only supports the latest.  (I know I can install node.js and build from source, but I'd rather not)

**Comment by asturur** [comment] 2016-12-21 08:49
no there is no way from website. You can download from cdn the full build.

**Comment by ingridmarleen** [comment] 2016-12-21 13:49
Even if you just say 
`var myCanvas = new fabric.Canvas('canvasVascular', {
						isDrawingMode : true
			});`
you get the fabric.util is undefined on 1106:2 and 1116:9

**Comment by asturur** [comment] 2016-12-22 08:31
Hello.
I did not have time to try it, but i saw the files where in the wrong order. i swapped to what i think is the correct one, and is already online. Would you give it a shot and in case close the issue?

**Comment by newtriks** [comment] 2016-12-22 10:11
I'm adding to this issue incase they are due to the same root cause, but I am happy to open another issue if this is not the case.

If I use the custom build page to download a dev (or minified) build selecting all options I get the following errors:

```
fabric.min.js:4816 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at fabric.min.js:4816
    at fabric.min.js:5057
```

```
bundle.app.js:3002 Uncaught TypeError: _fabric2.default.Canvas is not a constructor
    at Canvas.inititialiseCanvas (bundle.app.js:3002)
    at Canvas.inititialiseCanvas (bundle.app.js:11113)
    at Canvas.componentDidMount (bundle.app.js:2911)
```

If I download the source and manually build it works fine.

**Comment by asturur** [comment] 2016-12-22 10:49
ok i have to inspect file by file.
I just copied pasted the build script, i guess it needs more attention.
Sorry guys

**Comment by asturur** [comment] 2016-12-22 10:50
anyway the build.js is the script in the repository, and the custom build page if you look at source you see the file order.
If someone wants to give a stab before me there is what you need to look at

**Comment by newtriks** [comment] 2016-12-22 11:15
@asturur no worries and no need to apologise. Thank you.

**Comment by JamesWPritchett** [comment] 2016-12-22 19:05
Thanks for your attention, asturur.  No need for apologies; we're all programmers and we all screw up from time to time.

**Comment by ingridmarleen** [comment] 2016-12-23 08:43
@asturur no need for apologies, it's already great you answer this fast!

**Comment by asturur** [comment] 2016-12-27 08:26
Again i tried it very briefly. I mirrored the normal file order in building.
Broken for broken i just commited it out, i m short in time.
Someone wants to give it a shot?

[fabric.js.zip](https://github.com/kangax/fabric.js/files/673778/fabric.js.zip)

That is the output of a full custom build with gestures

**Comment by asturur** [comment] 2016-12-30 17:12
i compared the outputs and while the web builder add some empty lines, the rest look the same.

**Closed by asturur** 2016-12-30 17:12 UTC
Labels: needs_confirmation

**Comment by JamesWPritchett** [comment] 2016-12-31 02:15
Thank you for your attention.  I'm on vacation, but I'll confirm on Tuesday.

**Comment by websmyths** [comment] 2017-07-30 17:19
I am having this same issue. All I did was create a custom build from the website to add touch events. When I tried to load my site, I got this error in the console: 

fabric.js?ver=4.8:3178 Uncaught TypeError: Cannot read property 'extend' of undefined
    at fabric.js?ver=4.8:3178
    at fabric.js?ver=4.8:3179

The error occurs here: 

 3178:  fabric.util.object.extend(fabric.util, fabric.Observable);

**Comment by websmyths** [comment] 2017-07-30 17:21
If I go back to the original version I had loaded, the error goes away.

**Comment by asturur** [comment] 2017-07-31 08:30
i think i messed up moving a line from an optional file to a fixed one. checking it...

**Comment by websmyths** [comment] 2017-07-31 14:08
Thank you. Let me know when I should check it again.

**Comment by websmyths** [comment] 2017-08-01 18:29
asturur, I just tried the custom build again and I'm still getting the error. Were you able to look at it, or is there something I could look at myself? Thanks.

**Comment by asturur** [comment] 2017-08-01 18:33
https://github.com/kangax/fabric.js/commit/f86370582c5561b6546fa1c625061ee127948d6b

this is the breaking commit.

There is a line i moved from one file to another. that line must me moved in a file where fabric.util.object.clone is already defined.

at the end of fabric/util/lang_object for example.
if you feel like open a PR

**Comment by websmyths** [comment] 2017-08-01 19:17
I opened a PR, it says: 

This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.
Conflicting files
CHANGELOG.md

I tried the fix on a custom build I downloaded and it works. No errors. Touch gestures work.

**Comment by asturur** [comment] 2017-08-01 19:23
you made some mistake.

Either clone the repo from scratch, modify just the file you want to modify ( 2 of them ) commit the changes. Then build, try what you want to try, do not commit and stash changes. push up and open PR.

Or try the modify button from github.com, that will let you modify one file and will create an open PR and a branch for you. After that you can modify the second file.

**Comment by websmyths** [comment] 2017-08-01 19:59
Ok, got it. I'll do that. Thx.

**Comment by vousk** [comment] 2017-08-03 19:06
Trying to create a custom build. Even if I ckeck everything, I got `TypeError: fabric.util.object is undefined` when loading the script in a web page.
Is it something your on ?

**Comment by vousk** [comment] 2017-08-03 19:19
For people who wants to create custom build, I managed to make it working by manually changing the generated file.

### How to create custom DEV build:
- choose the options you need
- generate the DEV build
- move the line `fabric.util.object.extend(fabric.util, fabric.Observable)` just after the fabric.util.object declaration block:
``` 
     fabric.util.object = {
        extend: extend,
        clone: clone
     };
```

**Comment by vousk** [comment] 2017-08-03 19:24
### How to create custom MIN build:

- find and delete `,fabric.util.object.extend(fabric.util,fabric.Observable)`
- paste `;fabric.util.object.extend(fabric.util,fabric.Observable)` right after `fabric.util.object={extend:e,clone:t}`

**Comment by vousk** [comment] 2017-08-04 11:11
Thanks it works now !

**Comment by websmyths** [comment] 2017-08-04 15:08
Thank you.

**Comment by ahmadlatif1084** [comment] 2018-06-28 06:48
i have added an image as a sendBackwards(img) but on selection it gives me an error:"
**abric.min.js:1 Uncaught TypeError: Cannot read property 'tl' of null "**

**Comment by asturur** [comment] 2018-06-29 10:14
@ahmadlatif1084 how this relate with original issue?

**Comment by HustleTrader** [comment] 2021-07-02 20:21
Still dealing with this issue. Have the latest repo, have built with my desired includes: Text, iText, Animations, Gestures, Interaction, Serialization and this seems to be the result no matter I try unless I include=ALL. If ALL is included, it works fine. 

fabric.min.js:1 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at fabric.min.js:1
    at fabric.min.js:1

**Comment by asturur** [comment] 2021-07-03 13:52
Can you copy the exact build command you use?

**Comment by HustleTrader** [comment] 2021-07-06 18:42
Here's the exact build command i've been using: @asturur 

`node build.js modules=text,itext,interactions,gestures,animations,textbox,serialization no-svg-export no-svg-import`

**Comment by asturur** [comment] 2021-07-21 22:11
Sorry for being late, i need to check this and if a combination is not possible we have to document it
