### ISSUE TITLE
Cannot enter symbols needing Alt Gr (Alt+Ctrl) into IText in Chrome

### ISSUE THREAD

**Issue by J0s3f** [kangax/fabric.js#2211] opened 2015-05-19 14:02 UTC
In Chrome and Internet Explorer (most likely more browsers, will do some testing) symbols which are entered using Alt Gr + Key don't work. In Firefox they work.
This is very problematic for German keyboards, because the @ sign is Alt Gr + q here...
I will do some more tests which browsers show that problem and report.
Probably this is related to the problem with the accents, but I am not sure. The key* events get code 17, 18 and then the letter pressed, so this should be possible to catch?

**Comment by asturur** [comment] 2015-05-19 14:08
duplicate of #2051

**Closed** 2015-05-19 14:08 UTC

**Comment by J0s3f** [comment] 2015-05-19 14:19
Are you sure this is a duplicate?
This isn't a dead key, because you have to hold down Alt Gr, press q, then release Alt Gr.

Also, I never get the code 229 in the keydown event! It correctly returns 17 + 18 + 81

![image](https://cloud.githubusercontent.com/assets/604089/7705144/ce384a96-fe42-11e4-80f5-9a295377d1ba.png)

**Comment by asturur** [comment] 2015-05-19 15:31
is not a dead key problem, is double keys that we should listen on the oninput event and not on the keypress.
there was an ongoing work for that that i deleted accidentally.

in a few weeks we are going on it again.
