### ISSUE TITLE
IText bugs in rtl languages and mobile devices

### ISSUE THREAD

**Issue by matanasa** [kangax/fabric.js#3122] opened 2016-07-24 07:56 UTC
## Version
1.6.3

## Test Case
http://memes.mako.co.il/always/home/memem_image_gallery/697
The canvas is located at the left bottom of the page. you could see a blue text (Hebrew).

## Expected Behavior
Proper behavior of an IText in mobile devices and while using RTL languages.

## Actual Behavior
- Initially in mobile devices the backspace isn't working properly and when it works it doesn't delete the first word.

- Moreover using Hebrew (and I guess any other rtl language) inside an IText is pretty broken because the text selection (blue background), typing and deleting behavior is LTR while Hebrew is a RTL language.
For an example when you delete in English you delete from the left to the right, but in Hebrew the text is written from the right to the left and when trying to delete you fight with the LTR deleting in order to achieve your desired text.

- In the Test Case, we've managed to select all the text inside an IText when entering editing using textObject.selectAll(). And as you might see when you double click an IText it is selecting all the text but unfortunatly the blue background isn't displayed. I've come to find that in mobile devices this feature workes properly.

- Furthermore sometimes when you type/delete text in mobile devices inside an IText the changing text is scrambling in a weird way, lets say as if the IText is just not behaving properly.

All of the issues written above has been tested on the following devices:
Galaxy S4 (GT-I9500) Android 5.0.1 with Chrome 51.0.2704.81
NEXUS 6P Android 7.0.x with Chrome ^*
iPhone 6 iOS 9.2 with Safari

**Comment by asturur** [comment] 2016-08-07 20:08
duplicate of #2374

**Closed by asturur** 2016-08-07 20:08 UTC

**Comment by YaakovHatam** [comment] 2020-05-17 14:55
@w3nda  please look at the issue #2374 i am developing a RTL version please test it
