### ISSUE TITLE
fabric.js cannot recognize font-* property in tspan element.

### ISSUE THREAD

**Issue by mori-dev** [kangax/fabric.js#2116] opened 2015-04-16 08:19 UTC
In NodeJS, fabric.js v1.5.0 can recognize font-* property in text element.
fabric.js v1.5.0 cannot recognize font-* property in tspan element.

This is sample code by coffeescript.

```.coffeescript
fabric = require('fabric').fabric

svgString = """
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="600" height="600">
  <text x="0" y="90" font-family="serif"  font-size="30px">OK: aaaa</text>
  <text>
    <tspan x="0" y="40" font-family="serif"  font-size="20px">NG... bbbb</tspan>
    <tspan x="0" y="60" font-family=""  font-size="20px">NG... cccc</tspan>
  </text>
</svg>
"""

fabric.loadSVGFromString svgString, (objects, options) =>
  options.top = 0
  options.left = 0
  svgGroups = fabric.util.groupSVGElements objects, options
  canvas = fabric.createCanvasForNode(600, 600)
  canvas.add(svgGroups).renderAll()
  stream = canvas.createPNGStream()
  response.writeHead 200, 'Content-Type': 'image/png'
  stream.on 'data', (chunk) =>
    response.write chunk
  stream.on 'end', =>
    response.end()
  stream.on 'error', (error) =>
    response.end()
```

**Comment by christopherney** [comment] 2015-04-19 16:46
I have the same problem.

**Comment by asturur** [comment] 2015-04-19 16:50
TSPAN are not yet supported.
duplicate of #420.

**Closed** 2015-05-06 10:06 UTC
