### ISSUE TITLE
Change path of object and wrong bounding rectangles

### ISSUE THREAD

**Issue by livemirsi** [kangax/fabric.js#4653] opened 2018-01-29 16:08 UTC
Hello. 
https://jsfiddle.net/pngsa4gw/
When i move circle there is a change path of line. After change path of line i see wrong bounding rectangles.
How i can fix that?
I can just remove line and create again, but mybe there is an easier way.

**Comment by asturur** [comment] 2018-02-04 08:11
duplicate of #1025

**Closed by asturur** 2018-02-04 08:11 UTC
