### ISSUE TITLE
I want to clipping once again on the clipping result.

### ISSUE THREAD

**Issue by leesc81** [kangax/fabric.js#4559] opened 2017-12-13 16:22 UTC
I want to clipping the clipping result again.
The svg clippath does this, but the fabric is not imported svg clippath.
And clipTo function does not seem to be applied more than once.

Are you planning to support this feature?

If you can do the clipping again, it will be very useful for many people.
I am embarrassed because I can not implement the function because of this problem.

SVG Clippath(support)
![svg clippath](https://user-images.githubusercontent.com/16448526/33949612-75301e6e-e06d-11e7-9d52-6ff3f6dda744.png)

Fabricjs clippath import(not support)
![fabricjs](https://user-images.githubusercontent.com/16448526/33949536-396f90da-e06d-11e7-9ae9-5620f1005b5c.png)

**Comment by asturur** [comment] 2017-12-13 22:05
Yes this is exactly what we want to work on as soon as 2.0 is released.

duplicate of #1454

**Closed by asturur** 2017-12-13 22:05 UTC
