### ISSUE TITLE
Caret disappear on remove select text

### ISSUE THREAD

**Issue by mbaudry** [kangax/fabric.js#3531] opened 2016-12-15 10:56 UTC
Hello ! 

I have an issue with IText in the canvas.

## Version
1.6.6

## Test Case
http://jsfiddle.net/zjuoc3r9/100/

## Steps to reproduce
add an IText to the canvas with lot of words. Select a part of the text and remove it.

## Expected Behavior
We can see the selected text before we remove it and we see the new position of the caret after the text is removed

## Actual Behavior
we can't see the selected text and the caret disappear and we do not know its new position in the IText after the removing

**Comment by asturur** [comment] 2016-12-15 11:35
duplicate of #3505

**Closed by asturur** 2016-12-15 11:35 UTC
