### ISSUE TITLE
In a textbox with text-align justify, the last line should be left alone

### ISSUE THREAD

**Issue by sunu** [kangax/fabric.js#3725] opened 2017-02-20 12:02 UTC
## Version
1.7.6

## Test Case
https://jsfiddle.net/r51m61sh/1/

## Steps to reproduce
Create a Textbox with some text and set textAlign to justify.

## Expected Behavior
The last line should not be justified. See https://developer.mozilla.org/en/docs/Web/CSS/text-align

## Actual Behavior
The last line is justified.

**Comment by asturur** [comment] 2017-02-21 01:35
duplicate of #3444

**Closed by asturur** 2017-02-21 01:35 UTC
