### ISSUE TITLE
[Feature request] Add a zoom event or attribute to not scale on zoom

### ISSUE THREAD

**Issue by virror** [kangax/fabric.js#3099] opened 2016-07-11 12:38 UTC
I'm drawing some "meta" objects for every object on the canvas and I like those to not get scaled when zooming. So either I can rescale them myself using a zoom event or if I could set some flag to not scale them when zooming. The last would be preferred I guess.

**Comment by asturur** [comment] 2016-07-11 15:18
duplicate of #2781

**Closed by asturur** 2016-07-11 15:18 UTC
