### ISSUE TITLE
Text box is clipping the text

### ISSUE THREAD

**Issue by JugnuPathak** [kangax/fabric.js#3493] opened 2016-12-05 06:47 UTC
## Version
1.7.0 & 1.71

## Steps to reproduce
I'm using font family "Beautiful ES". You can see clipping effect in  this fiddle http://jsfiddle.net/jugnu_pathak/vPzPj/10/

## Actual Behavior
![font cliping fabric](https://cloud.githubusercontent.com/assets/12165539/20875971/bab3c152-bae4-11e6-9dd8-8d4640d52702.png)

**Comment by asturur** [comment] 2016-12-05 09:14
http://fabricjs.com/fabric-object-caching

Please have a read to this intro.
objectCaching is sizing a canvas for the object inside bounding box.
Either disable objectCaching or override the canvas caching function to leave some more space on around the text.
For all the rest is a duplicate of #1108 custom fonts dimensions not correct.

**Closed by asturur** 2016-12-05 09:14 UTC
