### ISSUE TITLE
SVGs without Width and Height display at '0' size

### ISSUE THREAD

**Issue by justrhysism** [kangax/fabric.js#1874] opened 2014-12-02 23:20 UTC
To provide the most consistent behaviour between browsers, sometimes SVGs as images need to omit the `width` and `height` attributes. [See http://www.boogdesign.com/examples/svg/svg-as-image.html in Chrome and IE]

However there is inconsistent behaviour between browsers when adding such SVGs as Fabric Images to the Canvas. In Chrome, the SVGs appear to have a `naturalWidth` of `300` and `naturalHeight` of `150`. However in IE and FF, these values are `0`, and as such, when added to the canvas, aren't visible (however can be "found" by group selecting over the canvas.

http://jsbin.com/viluca/8/edit 

This isn't necessarily a _bug_ in the respective browsers or Fabric, however it would be _nice_ if Fabric handled it nicely.

**Comment by asturur** [comment] 2015-04-01 15:50
sort of duplicate of #2069 @justrhysism, follow that topic to see updates.

**Closed by asturur** 2015-04-01 15:50 UTC
