### ISSUE TITLE
Issue with objectCaching & perPixelTargetFind

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4702] opened 2018-02-10 08:08 UTC
## Version
2.0.0

## Test Case
http://jsfiddle.net/0jmdecj9/9/

## Steps to reproduce
Click load svg, then ungroup svg.
Try select and resize the circle, it become a bit crazy because of the perPixelTargetFind.

## Expected Behavior
http://jsfiddle.net/0jmdecj9/10/
If I disable the cache, it's working. 

## Actual Behavior
https://cl.ly/3L400X0a3F3D

Any idea why? Am I missing something?

**Comment by blobinabottle** [comment] 2018-02-10 10:39
Oh in fact it's all objects with PerPixelTargetFind that has this issue. Not related to activeSelection

**Comment by asturur** [comment] 2018-02-10 10:49
I think that perPixelTargetFind needs to be updated to properly support caching.

**Comment by blobinabottle** [comment] 2018-02-10 10:52
What's weird is that in Safari it's working. And (I can't test it yet) but I think in previous chrome it was ok...

**Comment by asturur** [comment] 2018-02-10 10:53
oh.... i think is the chrome 64 bug. please try firefox / edge/ ie11 and they should work. We are waiting for a chrome 64 fix they are not doing, chrome 64 just does not work with canvas as of now.

**Comment by blobinabottle** [comment] 2018-02-10 10:56
Okay you're right, in 63, FFox it's ok!

**Comment by blobinabottle** [comment] 2018-02-10 10:59
https://bugs.chromium.org/p/chromium/issues/detail?id=807636&q=component%3ABlink%3ECanvas&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified they seems to say they'll patch 64? finger crossed

**Comment by asturur** [comment] 2018-02-10 11:51
duplicate of #4659

**Closed by asturur** 2018-02-10 11:51 UTC
Labels: bug, possible_feature
