### ISSUE TITLE
[feature request] Elliptical Radial Gradient

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4276] opened 2017-08-31 23:17 UTC
Do you think it's possible to add a feature to do an elleptical radial gradient ?
For the moment the radial is only circular.

PS : I tried to use the scaleX or scaleY function but without success.

Thank you.

**Comment by asturur** [comment] 2017-09-01 06:48
the onl way to get it is using a gradientTransform property on the gradient that will scale one direction.

```gradientTransform = [1, 0, 0, 2, 0, 0]``` for example

**Comment by ncou** [comment] 2017-09-01 09:39
Thank you.
I encounter a strange behaviors => I could make the gradientTransform work when i set the gradiant using "setGradient()" on a rect, but i create a new object calling directly the gradient object, i could not make it work.
I checked in the constructor (initialize function) and it should take my matrix.

Here is my fiddle :
http://jsfiddle.net/tmchz9h0/17/
TEST 1 is ok (if you uncomment the line 61, the rect with the transformed radial is applied).
TEST 2 is ko if i use a setbackgroundcolor with the new fabric.Gradient object created.

I even tried something like : `grad.gradientTransform = fabric.parseTransformAttribute([1,0,0,2,1,1]);` after creating my Gradient object. but without success.

**Comment by asturur** [comment] 2017-09-01 18:21
This fits with the other issue, the one that the gradients do not have a support for canvas.

**Comment by asturur** [comment] 2017-09-01 18:22
duplicate of #4232

**Closed by asturur** 2017-09-01 18:22 UTC
