### ISSUE TITLE
[Textbox] Very slow pasting

### ISSUE THREAD

**Issue by baubbelayponge** [kangax/fabric.js#2388] opened 2015-08-05 15:16 UTC
I'm trying out the new textbox feature in the 1.6.0-rc.1 version.
Unfortunately, we can't use it in production yet as it is extremely slow when pasting more than one line at a time.

See here :
http://jsfiddle.net/xmfw65qg/

Try editing the textbox and pasting :
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor blandit mattis. Morbi eu euismod nibh, a auctor sem. Maecenas faucibus dolor eget neque pulvinar lacinia. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed iaculis, neque id pharetra placerat, enim lacus ornare neque, vitae rutrum massa neque vitae massa. Cras quis egestas arcu. Nam nec dolor lacus. Phasellus pretium ac magna eget pharetra."

Using an older version I found floating on another fiddle, I can see it used to be much faster.
Please try here :
http://jsfiddle.net/xmfw65qg/1/

Any ideas?
Thanks!

**Comment by asturur** [comment] 2015-08-06 04:42
I think the problem is that i changed the paste text from block pasting to character pasting, also for textbox we need to recalculate style map and line split every character.
1) or the process is so slow 
2) or there is some bug in the code that make useless calculation.

Before it was not  working properly, style pasting was never working as expected.

**Comment by asturur** [comment] 2015-08-06 04:48
![image](https://cloud.githubusercontent.com/assets/1194048/9104076/21ff4cb8-3c07-11e5-8486-8c99ea941fba.png)

added some profiling.
anyway something to be solved.

**Comment by asturur** [comment] 2015-08-06 06:57
This is test case with iText, not slow as textbox but a bit slow anyway.

i do not feel like making a switch "if there is no style, paste a the text all in single operation", because style object get very ruined after pasting with multiple newlines and i do not know what happens on inserting style later.

iText profiling 
![image](https://cloud.githubusercontent.com/assets/1194048/9105457/42b9c954-3c18-11e5-9e98-5fe43fd25a08.png)

**Comment by asturur** [comment] 2015-08-06 07:08
```diff
    insertChar: function(_char, skipUpdate, styleObject) {
      var isEndOfLine = this.text[this.selectionStart] === '\n';
      this.text = this.text.slice(0, this.selectionStart) +
        _char + this.text.slice(this.selectionEnd);
      this._textLines = this._splitTextIntoLines();
      this.insertStyleObjects(_char, isEndOfLine, styleObject);
-     this.setSelectionStart(this.selectionStart + 1);
-     this.setSelectionEnd(this.selectionStart);
+     this.selectionStart += 1;
+     this.selectionEnd = this.selectionStart;
      if (skipUpdate) {
        return;
      }
+     this._updateTextarea();
      this.canvas && this.canvas.renderAll();
      this.setCoords();
      this.fire('changed');
      this.canvas && this.canvas.fire('text:changed', { target: this });
    },
```

making this changes brings back the iText performance to very fast, not textBox while lot of time is spent measuring text.
Unfortunately for correct style rendering, splitting text into lines and so measuring it, is a necessary operation.

**Comment by asturur** [comment] 2015-08-06 07:30
@kangax what do you think of this proposed half fix?

**Comment by asturur** [comment] 2015-08-18 10:23
http://jsfiddle.net/xmfw65qg/3/

Please check the updated fiddle with my latest changes, situation improved a lot.
Not yet lightning fast, but at least 10x faster now.

**Comment by baubbelayponge** [comment] 2015-08-18 12:37
Much faster than before yes, thanks :)

**Comment by asturur** [comment] 2016-11-16 11:19
duplicate of #3405

**Closed by asturur** 2016-11-16 11:19 UTC
Labels: itext
