### ISSUE TITLE
[2.0] Node - Image filters not working

### ISSUE THREAD

**Issue by jfizz** [kangax/fabric.js#4231] opened 2017-08-20 21:53 UTC
## Version
Fabric 2.0.0-beta.6
Node v6.9.5

## Test Case
```
var fabric = require('fabric').fabric;
var fs = require('fs');
var path = require('path');

fabric.Image.fromURL('http://fabricjs.com/assets/pug.jpg', function(image) {
  image.scaleToWidth(300);
  image.filters = [new fabric.Image.filters.Sepia()];
  image.applyFilters();

  var canvas = fabric.createCanvasForNode(300, 300, {backgroundColor: '#ffffff'});
  canvas.add(image);
  canvas.renderAll();

  let outputPath = path.join(__dirname, 'out.jpg');
  let file = fs.createWriteStream(outputPath);
  file.on('error', function(err) {
    console.log(err);
    process.exit(1);
  });
  file.on('finish', function() {
    console.log('wrote to', outputPath);
    process.exit();
  });

  canvas.createJPEGStream().pipe(file);
});
```

```
/Users/jFizz/Web/node-fabric/node_modules/fabric/dist/fabric.js:18811
      elementToDraw && ctx.drawImage(elementToDraw,
                           ^

TypeError: Image or Canvas expected
    at TypeError (native)
    at klass._render (/Users/jFizz/Web/node-fabric/node_modules/fabric/dist/fabric.js:18811:28)
    at klass.drawObject (/Users/jFizz/Web/node-fabric/node_modules/fabric/dist/fabric.js:12675:12)
    at klass.render (/Users/jFizz/Web/node-fabric/node_modules/fabric/dist/fabric.js:12623:14)
    at klass._renderObjects (/Users/jFizz/Web/node-fabric/node_modules/fabric/dist/fabric.js:7082:34)
    at klass.renderCanvas (/Users/jFizz/Web/node-fabric/node_modules/fabric/dist/fabric.js:7059:12)
    at klass.renderAll (/Users/jFizz/Web/node-fabric/node_modules/fabric/dist/fabric.js:8994:12)
    at /Users/jFizz/Web/node-fabric/index.js:12:10
    at /Users/jFizz/Web/node-fabric/node_modules/fabric/dist/fabric.js:18990:19
    at createImageAndCallBack (/Users/jFizz/Web/node-fabric/node_modules/fabric/dist/fabric.js:27554:30)
```

When filters are not applied, it works as expected. I attempted to create a cloud9 but I am not sure how to build fabric for their environment. If you have an existing workspace, I could try to use that.

**Comment by asturur** [comment] 2017-08-31 20:56
Just to say i did not let this behind.
I m currently trying to understand why jsdom does not behave how it should, but my low expertise with fabric+node and jsdom makes everything harder.

So i'm trying to remove all specific node code since jsdom should handle the job quite well. The problem is that sometimes the canvas that is drawing is a pure node-canvas canvas, sometimes is JSDOM wrapped canvas.

and this thing makes it break.

**Comment by jfizz** [comment] 2017-09-27 23:10
@asturur Just wanted to provide an update on this one: I tried it with the latest release (2.0.0-beta.7) but experienced the same result.

**Comment by CombatCode** [comment] 2017-11-01 12:26
It's killing me, anything new in this topic??

**Comment by asturur** [comment] 2017-11-01 13:08
is hard for me too. in our case jsdom is not transparent with our filtering operation.
Almost all node specific code can be removed in 2.0 but filters fails because at some point we pass to drawImage a node canvas wrapped in jsdom and that makes it fails.

i ll try again and open an help request on jsdom and link it here.

**Comment by CombatCode** [comment] 2017-11-01 13:13
@asturur thank you for the reply, can you say more what dirty hack have you used here https://github.com/kangax/fabric.js/issues/4257 to make it working ? I'm considering to fork JSDOM and place some temporary hack to fix this issue, but newest JSDOM is not supported by fabricjs... right now I feel like a blind child in the [Bieszczady](https://en.wikipedia.org/wiki/Bieszczady_Mountains) trying to fix that

**Comment by asturur** [comment] 2017-11-01 13:22
i did not manage to fix filters. jsdom 9.x is way batter than the old 3.x
i would remove node 4 support and switch to jsdom 11.x if it would change something.

so jsdom is detecting node canvas support and is providing fabricjs with fake canvas elements that should just work.

and they work for everything except filters.

now i m out, i ll redo that branch and share it to give it a try.

**Comment by CombatCode** [comment] 2017-11-01 18:50
jsdom in version 11.3.0 and node-canvas 2.0 alpha is not resolving this issue

**Comment by URSTYLE** [comment] 2017-11-08 09:10
Any news here? or it's just to hard topic and we should back to 1.x version with our code

**Comment by asturur** [comment] 2017-11-08 11:34
I'm sorry no news, i did not have time to handle this.

**Comment by asturur** [comment] 2017-11-19 15:27
finally starting to investigate this.

**Comment by asturur** [comment] 2017-11-19 22:22
Latest build fix filters in nodejs.

![out](https://user-images.githubusercontent.com/1194048/32996234-837ad11c-cd80-11e7-9912-1518fa9646c3.png)

![out2](https://user-images.githubusercontent.com/1194048/32996228-761fe480-cd80-11e7-8bde-83dc07a84bb7.png)

**Closed** 2017-11-19 22:23 UTC

**Comment by qynAUGMN** [comment] 2017-11-24 02:33
@asturur when use the 2.0-rc.1, canvas.createJPEGStream is undefined.What's your way to initiate a new fabric.Canvas?

**Comment by asturur** [comment] 2017-11-24 06:11
i think you need to install libjpeg when you build node canvas

**Comment by qynAUGMN** [comment] 2017-11-24 10:11
alreay installed,use 2.0.0-beta.7 is ok.

**Comment by asturur** [comment] 2017-11-24 10:19
the error was called differently before because now is jsdom that is probably surfacing it.
Is a JSDOM or a node-canvas issue, nothing i can fix. i have the same error when i run tests

**Comment by qynAUGMN** [comment] 2017-11-27 03:26
when updated 2.0.0-rc.3,i found canvas.createJPEGStream is a function,but no stream response
