### ISSUE TITLE
Serialize canvas with filtered images to SVG broken

### ISSUE THREAD

**Issue by goodcode** [kangax/fabric.js#3298] opened 2016-09-30 04:54 UTC
## Version
1.6.4

## Test Case
http://jsfiddle.net/Da7SP/188/

## Steps to reproduce
Run the fiddle and open the console. You will see the output of the toSVG canvas function.
In the test case there is one image loaded from URL with filter applied. Then toSVG method is called and logged in the console.

## Expected Behavior
When there are images with filters applied, toSVG canvas function should serialize their source and output it in xlink:href attribute as data (base64). 

## Actual Behavior
With latest release the xlink:href attribute is set to their initial URL.

**Comment by asturur** [comment] 2016-10-01 07:35
i close this issue as duplicate of:
https://github.com/kangax/fabric.js/issues/1577
there was some code somewhere to have the image data url in the exported svg.
We could merge that if the image has filters. Just the svg would be very big.

**Closed by asturur** 2016-10-01 07:35 UTC

**Comment by goodcode** [comment] 2016-10-01 19:31
This is NOT the same problem (dated 2 years ago). This bug is a regression in 1.6.4 for something that worked just fine before that. The SVG used to be "very big" but that wasn't an issue, for us at least. The main thing was it was working. We don't need additional information about the filters applied (like the person in #1577 wanted), we need the image with applied filters in it, sent as data.
If there is an option to turn the old behaviour on, please share how to set it up. Otherwise this should be considered as a regression.

**Comment by asturur** [comment] 2016-10-02 06:41
yes i realized i was wrong. i think somehow i m pulling src from originalelement and not from element. probably when i "fixed" getSrc function.
to object we need originalElement and toSvg element. gonna check it.

**Comment by asturur** [comment] 2016-10-02 07:32
give a look at PR should solve the issue. writing tests and merging today.

**Comment by goodcode** [comment] 2016-10-04 20:19
Yes, it solves the issue. Thank you!
