### ISSUE TITLE
Controls in wrong position after export toSVG and loadSVGFromString

### ISSUE THREAD

**Issue by pugmas** [kangax/fabric.js#2208] opened 2015-05-19 07:55 UTC
I'm not able to get controls in correct position:
https://jsfiddle.net/nvo34hyh/4/

```javascript
var canvas = new fabric.Canvas('c');
var canvas2 = new fabric.Canvas('c2');
var canvas3 = new fabric.Canvas('c3');
var svgString = "";

var rect = new fabric.Rect({
    width: 100,
    height: 100,
    fill: 'red',
    stroke: 'blue',
    strokeWidth: 1,
});
canvas.add(rect);
canvas.calcOffset();
canvas.renderAll();

svgString = canvas.toSVG();
console.log(svgString);

fabric.loadSVGFromString(svgString, function (objs, options) {
    var group = fabric.util.groupSVGElements(objs, options);
    canvas2.add(group);
    canvas2.calcOffset();
    canvas2.renderAll();
});

fabric.loadSVGFromString(svgString, function (objs, options) {
    canvas3.add(objs[0]);
    canvas3.calcOffset();
    canvas3.renderAll();
});
```

![1](https://cloud.githubusercontent.com/assets/12508931/7697905/3de7f7ba-fe0c-11e4-853e-056031e9894b.jpg)

**Comment by asturur** [comment] 2015-05-19 08:16
first screen is ok because you are importing SVG
second screen is a known bug, because the rect contains a transformMatrix (#1520)

So i close it as a duplicate of #1520 that with a bit of patience is gonna be fixed.

**Closed by asturur** 2015-05-19 08:16 UTC
