### ISSUE TITLE
Multi-select border rendering issue

### ISSUE THREAD

**Issue by Alexcouter** [kangax/fabric.js#2327] opened 2015-07-08 10:06 UTC
I just noticed a rendering issue when you select multiple objects : 
http://fabricjs.com/bounding-rectangle/
![giveatry](https://cloud.githubusercontent.com/assets/7658026/8567840/ca8d8864-2568-11e5-982f-ffead9df0d98.jpg)

The border is at a fixed position only when multiple objects are selected.
In my case I can select about 30 objects at the same time, so it's really annoying to see 30 borders hidding my background.

**Comment by asturur** [comment] 2015-07-08 10:39
duplicate of #1941 currently being worked on as a milestone to release 1.5.1

**Closed by asturur** 2015-07-08 10:39 UTC
