### ISSUE TITLE
Latest release scales canvas incorrectly, and odd issues with toDataURLWithMultiplier

### ISSUE THREAD

**Issue by devonmather** [kangax/fabric.js#2592] opened 2015-10-28 15:47 UTC
Hey,

I've downloaded the latest release from a few days ago and it now appears the canvas is scaled down, maybe for retina screens, and it's causing some odd issues on a retina MBP in Chrome.

https://jsfiddle.net/devonmather/xtcmo8u3/2/

Example image of issue http://i.imgur.com/cOO2bCB.png

Advice appreciated :)
Devon Mather

**Comment by asturur** [comment] 2015-10-28 15:59
Please download this:

https://www.deltalink.it/andreab/fabric/fabric.js

is latest compiled.
If this fixes, please close the issue.

**Comment by devonmather** [comment] 2015-10-28 16:36
Thanks asturur! That latest release does seem to fix the scaling issue.

However the following line of code seems to un-retina the canvas. Not sure why?
`canvas.toDataURLWithMultiplier('png', 3);`

Thanks again :)

**Comment by j3rem1e** [comment] 2015-10-29 08:33
I don't know if it's related or not, but in the latest release, canvas.toDataURL with multiplier don't work. The canvas dimensien are scaled, but not the objects inside. I can't test with the link in deltalink.it because of my corporate firewall..

A jsfiddle (adapter from another one) : http://jsfiddle.net/ktW3z/12/

**Comment by oscar-g** [comment] 2015-10-29 20:48
Running into this issue, as well.

The canvas scales, but not the objects inside of it.

**Comment by asturur** [comment] 2015-10-29 22:01
the issue is already fixed by the current code in github.
canvas.toDataUrlWithMultiplier unretina the canvas because the canvas get dimensions change. This reset the transform changes.
I blame apple for this retina concept.

**Comment by oscar-g** [comment] 2015-10-30 01:21
@asturur thanks, I'll try on the latest commit and report back.

**Comment by oscar-g** [comment] 2015-10-30 17:35
Hmm, it didn't work with the current dist files. Maybe I'll have to build from the src in master....on another note, I can't get the library installed on Ubuntu :(

**Comment by oscar-g** [comment] 2015-10-30 19:28
I was finally able to rebuild with the src files in the current [master](https://github.com/kangax/fabric.js/commit/86bb0c773d9912e64e4f60cd3c0ce1b53fa439fe) and the multiplier works!

**Closed** 2015-11-01 18:53 UTC
