### ISSUE TITLE
Optimization: Use separate canvas for transform

### ISSUE THREAD

**Issue by boomyjee** [kangax/fabric.js#1169] opened 2014-02-15 03:39 UTC
If using separate canvas for transform and transform it via css (without redrawing) it's much faster than redrawing canvas.
For example just moving IText with two different fonts leads to very noticable lags ( canvas is 900x600 ).

So steps could look like this:
1) Draw transformed object on separate canvas ( named middle and placed between upper and lower)
2) Redraw lower canvas without transformed object or group
3) During transform alter middle canvas css (rotation, translation, scale)
4) On transform end hide middle canvas and redraw lower canvas with transformed objects

What do you think? Is this optimization needed?
I can try to implement this but it covers some core functionality so it would nice if you can point me in the right direction.

**Comment by sumoxyz** [comment] 2015-01-13 16:06
@GordoRank could you please send me the turbo code to thepoohfriends AT gmail DOT com
Thanks..

**Comment by scottmilward** [comment] 2015-08-31 19:55
@GordoRank Also would be interested to try out your version of fabric with turbo please.
smstl1416 AT yahoo dot com

**Comment by n0rb** [comment] 2015-10-23 13:02
any news on this? a online demo would be great! does anyone still have the sources from @GordoRank ?

**Comment by tudoragaf** [comment] 2016-01-29 05:05
@GordoRank Could you please send me a copy of the turbo code ? 

agaf.tudor AT gmail dot com

**Comment by jwmao** [comment] 2016-03-07 16:51
Could you please send me a copy of the turbo code? I'm having performance issues with objects rendering on big canvas. (3600 x 3600), I'm wondering with turbo, the performance can be improved. My email address: jwmao@yahoo.com

**Comment by BxB00T** [comment] 2016-04-11 03:46
I have same problem as @jwmao please someone send me the turbo code.. Boutin103 at gmail dot come

**Comment by BxB00T** [comment] 2016-04-11 20:43
Someone please send me the turbo code I have same problem as @jwmao.. boutin103 at gmail dot com

**Comment by asturur** [comment] 2016-04-28 23:56
duplicate of #814

**Closed by asturur** 2016-04-28 23:56 UTC
Labels: possible_feature

**Comment by billensley** [comment] 2016-09-21 19:45
You guys still looking for outline draw without full canvas repaint?  I have it, let me know and I can send you the updates.  It's not ready yet to submit but it's only about 7 lines of code to implement.

**Comment by sumoxyz** [comment] 2016-09-21 20:41
We went through some design changes in between but really would like to
have see the updates..

Thank you

**Comment by jwmao** [comment] 2016-09-22 10:18
I would love to see the updates too. Wei Mao 

    On Wednesday, September 21, 2016 3:41 PM, sumoxyz <notifications@github.com> wrote:
 

 We went through some design changes in between but really would like to
have see the updates..

Thank you

**Comment by billensley** [comment] 2016-09-22 17:35
OK, here goes.  There are 2 locations to update, both small.  What is happening is that we create an image of the entire canvas, paint it into the cacheContext, then paint that along with the object being dragged.  I'm not yet setup to fork and submit here with this project so here you go:

Usage: canvas.outlineDrag = true;

The first in the Objects _onMouseDown method

/**
     * Method that defines the actions when mouse is clic ked on canvas.
     * The method inits the currentTransform parameters and renders all the
     * canvas so the current image can be placed on the top canvas and the rest
     * in on the container one.
     * @private
     * @param {Event} e Event object fired on mousedown
     */
    __onMouseDown: function (e) {

      // accept only left clicks
      var isLeftClick  = 'which' in e ? e.which === 1 : e.button === 0;
      if (!isLeftClick && !fabric.isTouchSupported) {
        return;
      }

      if (this.isDrawingMode) {
        this._onMouseDownInDrawingMode(e);
        return;
      }

      // ignore if some object is being transformed at this moment
      if (this._currentTransform) {
        return;
      }

      var target = this.findTarget(e),
          pointer = this.getPointer(e, true);

      // save pointer for check in __onMouseUp event
      this._previousPointer = pointer;

      var shouldRender = this._shouldRender(target, pointer),
          shouldGroup = this._shouldGroup(e, target);

      if (this._shouldClearSelection(e, target)) {
        this._clearSelection(e, target, pointer);
      }
      else if (shouldGroup) {
        this._handleGrouping(e, target);
        target = this.getActiveGroup();
      }

      if (target) {
        if (target.selectable && (target.__corner || !shouldGroup)) {
          this._beforeTransform(e, target);
          this._setupCurrentTransform(e, target);
        }

        if (target !== this.getActiveGroup() && target !== this.getActiveObject()) {
          this.deactivateAll();
          target.selectable && this.setActiveObject(target, e);
        }
      }
      this._handleEvent(e, 'down', target ? target : null);
      // we must renderAll so that active image is placed on the top canvas
      shouldRender && this.renderAll();
      
      **//cache the screen for use in dragging
      this.clearContext(this.contextCache);
      this.contextCache.drawImage(this.contextContainer.canvas, 0, 0);**
    },

The second is in Objects _transformObject method

      /**
     * @private
     * @param {Event} e Event fired on mousemove
     */
    _transformObject: function(e) {
      var pointer = this.getPointer(e),
          transform = this._currentTransform;
     
      transform.reset = false,
      transform.target.isMoving = true;

      this._beforeScaleTransform(e, transform);
      this._performTransformAction(e, transform, pointer);
      
      **if(canvas.outlineDrag){
        // dragging object
        this.clearContext(this.contextContainer);
        this.contextContainer.drawImage(this.contextCache.canvas, 0, 0);
	  
        if (!this.controlsAboveOverlay && this.interactive) {
          this.drawControls(this.contextContainer);
        }
      }
      else{
        transform.actionPerformed && this.renderAll();
     }**
    },

**Comment by billensley** [comment] 2016-09-22 17:38
OK, here goes.  There are 2 locations to update, both small.  What is happening is that we create an image of the entire canvas, paint it into the cacheContext, then paint that along with the object being dragged.  I'm not yet setup to fork and submit here with this project so here you go:

Usage: canvas.outlineDrag = true;

The first in the Objects _onMouseDown method


    __onMouseDown: function (e) {

      // accept only left clicks
      var isLeftClick  = 'which' in e ? e.which === 1 : e.button === 0;
      if (!isLeftClick && !fabric.isTouchSupported) {
        return;
      }

      if (this.isDrawingMode) {
        this._onMouseDownInDrawingMode(e);
        return;
      }

      // ignore if some object is being transformed at this moment
      if (this._currentTransform) {
        return;
      }

      var target = this.findTarget(e),
          pointer = this.getPointer(e, true);

      // save pointer for check in __onMouseUp event
      this._previousPointer = pointer;

      var shouldRender = this._shouldRender(target, pointer),
          shouldGroup = this._shouldGroup(e, target);

      if (this._shouldClearSelection(e, target)) {
        this._clearSelection(e, target, pointer);
      }
      else if (shouldGroup) {
        this._handleGrouping(e, target);
        target = this.getActiveGroup();
      }

      if (target) {
        if (target.selectable && (target.__corner || !shouldGroup)) {
          this._beforeTransform(e, target);
          this._setupCurrentTransform(e, target);
        }

        if (target !== this.getActiveGroup() && target !== this.getActiveObject()) {
          this.deactivateAll();
          target.selectable && this.setActiveObject(target, e);
        }
      }
      this._handleEvent(e, 'down', target ? target : null);
      // we must renderAll so that active image is placed on the top canvas
      shouldRender && this.renderAll();
      
       **//cache the screen for use in dragging
      this.clearContext(this.contextCache);
      this.contextCache.drawImage(this.contextContainer.canvas, 0, 0);**
    },

The second is in Objects _transformObject method

    _transformObject: function(e) {
      var pointer = this.getPointer(e),
          transform = this._currentTransform;
     
      transform.reset = false,
      transform.target.isMoving = true;

      this._beforeScaleTransform(e, transform);
      this._performTransformAction(e, transform, pointer);
      
      **if(canvas.outlineDrag){
        // dragging object
        this.clearContext(this.contextContainer);
        this.contextContainer.drawImage(this.contextCache.canvas, 0, 0);
	  
        if (!this.controlsAboveOverlay && this.interactive) {
          this.drawControls(this.contextContainer);
        }
      }
      else{
        transform.actionPerformed && this.renderAll();
     }**
    },

**Comment by karthickvkumar** [comment] 2017-04-10 13:46
@GordoRank  I would like to use your turbo-code, kindly send to this email id karthickvelraj@live.in

Thanks in advance

**Comment by krzysiek3d** [comment] 2017-05-18 12:39
https://github.com/gordorank Please sen me Youre Turbo-code to this email krzysiek3d AT gmail DOT com
Many Thanks..

**Comment by tnguyen94** [comment] 2017-07-10 17:42
@GordoRank Could please you send me the turbo code? nguyen DOT trevin AT gmail DOT com

**Comment by pnguyen59** [comment] 2018-04-03 03:32
@GordoRank  could you please send me your turbo code? my email is : thienphucnguyenchau@gmail.com
