### ISSUE TITLE
Cursor position is incorrect when some capital letters at the line beginning

### ISSUE THREAD

**Issue by nglinh24** [kangax/fabric.js#3790] opened 2017-03-20 05:35 UTC
## Version
1.7.8

## Test Case
http://c2n.me/3ID1URA (at http://fabricjs.com/test/misc/itext.html)

## Steps to reproduce
Entering a capital letter such as T, F, Y.. at the beginning of text line, the cursor position is incorrect.
In the screenshot, the cursor position "belong" to w letter. Also if move the cursor back on letter i, the cursor will on i letter and we can't see i letter anymore.

## Expected Behavior
Cursor position should in correct position (outside of each letter in the paragraph)

## Actual Behavior
Cursor position overlaps letters

**Comment by asturur** [comment] 2017-03-20 06:43
duplicate of #3680

**Closed by asturur** 2017-03-20 06:43 UTC
