### ISSUE TITLE
.clone(...) method of some Objects doesn't call the callback 

### ISSUE THREAD

**Issue by pugmas** [kangax/fabric.js#2209] opened 2015-05-19 09:58 UTC
The .clone method should invoke its callback as discribed here:
http://fabricjs.com/docs/fabric.Rect.html#clone

But for some specialisations of Object, it does not. Because .fromObject(...) doesn't:
http://fabricjs.com/docs/fabric.js.html#line11611
vs.
http://fabricjs.com/docs/fabric.js.html#line14793

Is this just a doc issue or should we unify .fromObject( ... ) methods?

https://jsfiddle.net/7zzfufpz/ :

```javascript
var canvas = new fabric.Canvas('c');
var rect = new fabric.Rect({
    width: 100,
    height: 100,
    fill: 'red'
});
var returnVal = rect.clone(function(clone){
    alert("This method is not invoked, so you can't see this", clone);
});
```

**Comment by kangax** [comment] 2015-05-19 16:29
Documentation issue, but really we need to fix it in the next back-incompatible version. What happens now is that fromObject returns an object on instances that are NOT synchronous and invokes callback on instances that ARE synchronous. But this is certainly confusing and is a bad API, which is why I'd like to fix it at some point.

**Comment by sapics** [comment] 2015-05-26 06:10
I have a same problem now.
I wish to make a PR as a temporary fix, if you are agree with below fix at https://github.com/kangax/fabric.js/blob/master/src/shapes/object.class.js#L1154.

```diff
if (this.constructor.fromObject) {
-  return this.constructor.fromObject(this.toObject(propertiesToInclude), callback);
+  var object = this.toObject(propertiesToInclude);
+  if (this.constructor.async) {
+    return this.constructor.fromObject(object, callback);
+  }
+  object = this.constructor.fromObject(object);
+  callback && callback(object);
+  return object;
}
```
By this fix, I guess that callback function is always invoke.
But, this fix is still return `undefined` for `Image` and `Group` and so on.

**Comment by kangax** [comment] 2015-05-26 17:20
This is an API-breaking change so we can't release it just as a "no big deal". We'll need to bump major version, which means Fabric 2.0. For 2.0, I would want to collect few back-incompatible changes, to avoid bumping version too much.

**Comment by kangax** [comment] 2015-05-26 17:21
Duplicate of #2010

**Closed by kangax** 2015-05-26 17:21 UTC
Labels: feature
