### ISSUE TITLE
Fabric.js / AngularJS project in Electron: no quit, no reload, no force reload

### ISSUE THREAD

**Issue by sandor** [kangax/fabric.js#4045] opened 2017-06-29 08:47 UTC
Not sure if this is a Fabric.js bug or something in my code, or even electron related – so take my apologies if I am posting this in the wrong place. I have posted this also on stackoverflow but I think that the problem is too complex. Anyhow: I am experiencin this problems in electron only when I am using Fabric.js...

I am new to electron and fabric.js and making my first steps (also not an experienced developer). 

For my project I am using the angularJS implementation of michael calkins (link on the bottom).

Have a strange thing with my project. I am using the fabric.js library and AngularJS. Everything is running fine till I invoke a Fabric.js function (ie. create a rectangle in the canvas). After doing this, my app is still running as before, all functions are there but I am no more able to quit my app (cmdQ) or to reload or even to force reload the app. My only way to quit the app is the "quit immediately..." function of OSX. I am also not getting relevant errors in my console, beside a lot of "render cycle" console logs (you can see this logs also in the codepen example). 

I know it is hard to tell something without seeing the project, but maybe one of you guys experiences something similar...

I am still working with the electron development version and running my project with "electron ." or by drag-dropping it on the electron prebuilt app.

I have my top-bar menu defined with the usual funtions like reload / force reload / show devtools etc. Actually the project is based on one of the starter boilerplates. The menu functions are there and usable either with the mouse or via the shortcuts. Most of the evem after invoking Fabric.js...

I don't think that I am capturing the mouse events via canvas - I can reach the menu with the mouse even after I create a Fabric.js object on the canvas, and I can select the respective functions inside the menu.

Funnily most of the menu functions are working (mouse and shortcut). ie. I can make my app fullscreen, open/close devtools, minimise/maximise the window etc. The only functions are gone: Quit the App / Reload the App / Force reload the app... Even the OSX close button (x) in the top right corner of the window stops working – while the minimize / maximize buttons still working fine...

I am lost somehow ;-)

I am working with this git repository: https://github.com/michaeljcalkins/angular-fabric

Link to a demo version (on codepen):

http://codepen.io/clouddueling/full/Imupw

Any help is highly appreciated – and sorry again if I am posting on the inappropiate plac...

**Comment by ozooner** [comment] 2017-06-30 09:46
I doub't that any of the maintainers will set up electron project to try out your issue, however I can suspect that the keypress event gets caught by fabric (maybe you subscribe to it?). So my bet would be to try catching the key presses in javascript code and then call appropriate functions via electron remote.
e.g `require('electron').remote.getCurrentWindow().reload();`

**Comment by asturur** [comment] 2017-07-01 11:09
So fabric does not eat keypresses unless you are editing some text. In that case yes, but they are bound to a textarea that should disappear after editing.

I m really not expert in this field no idea how to help.

**Comment by asturur** [comment] 2017-07-01 11:10
unless you can provide the packaged thing i can get an eye over it, more as a curiosity than fabric bug.

**Comment by asturur** [comment] 2017-07-03 13:20
Gonna close this issue, please if you have a stackOverflow question opened post here the link.

**Closed by asturur** 2017-07-03 13:20 UTC

**Comment by sandor** [comment] 2017-07-04 07:46
@asturur Thanks Andrea, I understand that you are closing the topic. However (even only for curiosity) here is a link to the public repo – needs at least electron 1.7.x beta to see all the icons in their glory and the newest chrome if you want to run it without electron in local server: 

https://github.com/sandor/floido

The project is more than messy, but it is not intended as something productive – should be only a prototype for my frontend and some testings (and learning lessons) with fabric.js and electron... 

The index.html is my main file. A more reduced version (same bug ang_index.html is the file from michaeljcalkins, who created the angular-fabricj.js implementation (link above). You can rename this to index.html to run it in electron...

Would be great if you could spend a few minutes – but anyhow thank you for the time you took already!

Here is also the link to the StackOverflow post:

https://stackoverflow.com/questions/44812419/fabric-js-project-in-electron-no-quit-no-reload-no-force-reload

@ozooner Thanks Sandler! Sorry if I was not clear enough – I don't think that keypress is the real issue, since evrything else is working fine– ie. you can activate all the menu points with the mouse, but some of them as describded above, simply won't work... Als the bug appears as soon as I invoke ANY fabric.js realted function – ie. create a rectangle or resize the canvas...

**Comment by asturur** [comment] 2017-07-04 10:01
![image](https://user-images.githubusercontent.com/1194048/27825645-7dc95712-60b0-11e7-97e3-bfa8f9e5de93.png)

Fabric 1.4.8? could you please work on latest?

**Comment by sandor** [comment] 2017-07-04 10:24
@asturur you are referencing ang_index.html – this is from the original project:

https://github.com/michaeljcalkins/angular-fabric

My project (index.html) is using the latest fabric.js release (js/fabric.min.js). I even changed this to the new 2.0 beta btw. :-)

But anyhow even changing the reference in the ang_index.html to:

<script src='https://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.7.15/fabric.min.js'></script>

won't make any differnce in the electron app...

**Comment by sandor** [comment] 2017-07-04 10:56
@asturur Andrea, it is anyhow right that this topic is closed. It is definitely NOT a fabric.js bug. Built an "pure" and simple fabric.js example without angularJS (just a bit of JQuery) and everything is working as should. So it is definitely something related with the angularJS implementation of - michaeljcalkins - but till now I am not able to figure out what it is :-) It is a shame, he done there a lot of good work that would be worth to take it as a starting point for my project...

For curiosity – this gist as index.html is working fine in the electron project:

https://gist.github.com/sandor/cb2477eeaa751db64f29b74ac55c3f37

**Comment by asturur** [comment] 2017-07-04 11:00
i m sure is not a fabricjs issue, that is why i closed it.
Closed does not mean not helping.

I need to manage this issue tracker almost alone, 200 issues are really overwhelming, so when i know i something that does not need a fix i close it.

People do not come here to help, is not stackoveflow. So having closed or open will not change that much.

**Comment by sandor** [comment] 2017-07-04 11:11
As I started this here :-)

> Not sure if this is a Fabric.js bug or something in my code, or even electron related – so take my apologies if I am posting this in the wrong place. I have posted this also on stackoverflow but I think that the problem is too complex.

Andrea, thank you again for your help and also for the huge efforts you (and your team) are doing here by building an maintaning fabric.js. As you are saying – this is not the right place for discussions – it is an issue tracker and it is probably very hard to maintan the issues only!

Beside this all I think fabric.js would need (and deserve) a community forum for user talk/help etc. – I know about about the google.group but it is not so active and attractive. StackOverflow is a possibility but not a real alternative for discussions.

Hope that my project will get legs in the near future and that we will be using fabric.js so that we can also contribute something in the future...

**Comment by asturur** [comment] 2017-07-04 11:14
Sure would help.
The problem is that since 2 years is a one man band project. me.

**Comment by sandor** [comment] 2017-07-04 11:20
wow! well this is a LOT of work mate! Huge kudos! May I ask you if you would like to participate in my/our project (since huge part will/could rely on fabric.js) – if so, could we discuss this somewhere in an appropiate place?
