### ISSUE TITLE
IText can not input chinese bug.

### ISSUE THREAD

**Issue by yanzhou-share** [kangax/fabric.js#3069] opened 2016-06-28 07:18 UTC
Hi, kangax:
First of all, this plugin is very good but I find IText can not input chinese.

@kangax 

thanks

**Comment by FeaRCODE** [comment] 2016-06-28 19:57
@yanzhou-share For bug reports, could you provide a test case on Jsfiddle?

**Comment by 526878729** [comment] 2016-07-18 09:04
It is a same problem

**Comment by evolutionjay** [comment] 2016-07-22 05:52
Input problem more difficult to use Jsfiddle reflected, it is recommended to put YouTube video recording

**Comment by asturur** [comment] 2016-08-07 21:04
Need to know:
Operating system
browser
input method used.

**Comment by evolutionjay** [comment] 2016-08-08 01:46
macOS 10.11.6 (15G31)
All Browser。
the system base Chinese input method
fabric version 1.6.3

**Comment by gengshenghong** [comment] 2016-08-10 08:57
Same issue here. Tested with Chrome on both windows, Ubuntu..using fabric version 1.6.3

**Comment by neopheus** [comment] 2016-08-10 11:49
jsfiddle that demonstrate the problem.

**Comment by gengshenghong** [comment] 2016-08-11 04:45
I tested with the official itext demos, input method is Sogou input method (popular input method for Chinese):
http://fabricjs.com/test/misc/itext.html

**Comment by evolutionjay** [comment] 2016-08-11 05:45
![image](https://cloud.githubusercontent.com/assets/4468540/17579586/ba7566f8-5fc9-11e6-88b7-26af92ac0b86.png)


![image](https://cloud.githubusercontent.com/assets/4468540/17579598/cf5de39c-5fc9-11e6-8fb7-6b58066e3f62.png)


The system default input method on macOS／Chrome 52

**Comment by gengshenghong** [comment] 2016-08-14 07:07
I found it works on my Ubuntu 16.04 (Ubuntu Kylin, which is the official Chinese version of Ubuntu, with built-in Sogou IME). Tried both Chromium v51.0.2704.79 Ubuntu 16.04 (64-bit), and default Firefox in it.

Last time (not work) I was testing using Chrome (not Chromium) on Ubuntu 14.04 and win7 machines....

It seems like some compatible issues with Chrome. I need more testing around to isolate who is the criminal (OS? Browser? IME?)

**Comment by gengshenghong** [comment] 2016-08-15 03:20
I've debugged the code and the issue is clear now, the onCompositionUpdate and onCompositionEnd event compatible issue between browsers. **In firefox, the "data" will be updated on both the last "composition update" and "composition end" event, but in chrome, it will only be updated on "composition end"**. Below updated code (move all code from compositionupdate to compositionend) works for me on both Chrome and Firefox (on same machine with Ubuntu 14.04 and same IME):

@kangax could you please help to review whether the code is ok and no impact on other code? You may merge it to your code if no issues.

`/**
   * Composition end
   */
  onCompositionEnd: function(e) {
    console.log("onCompositionEnd");
    console.log(e);
    var data = e.data;
    this.selectionStart = this.compositionStart;
    this.selectionEnd = this.selectionEnd === this.selectionStart ?
    this.compositionStart + this.prevCompositionLength : this.selectionEnd;
    this.insertChars(data, false);
    this.prevCompositionLength = data.length;

    this.inCompositionMode = false;
  },

  /**
   * Composition update
   */
  onCompositionUpdate: function(e) {
    console.log("compositionupdate");
    console.log(e);
    /*
    var data = e.data;
    this.selectionStart = this.compositionStart;
    this.selectionEnd = this.selectionEnd === this.selectionStart ?
      this.compositionStart + this.prevCompositionLength : this.selectionEnd;
    this.insertChars(data, false);
    this.prevCompositionLength = data.length;
    */
  },`

**Comment by gengshenghong** [comment] 2016-08-15 03:44
Update: need to have the code in both composition update and composition end, if need to simulate the typing process better. Without "composition update" code, the entered English characters will not show during typing.

**Comment by raffareis** [comment] 2016-08-15 04:06
i believe this relates to [#2352](https://github.com/kangax/fabric.js/pull/2352)

**Comment by asturur** [comment] 2016-08-15 05:34
Guys keyboard event is very different from browser to browsers. is something on wich i will work on but i do not think it will be an easy patch..other than composition event there are different ime. if i long press 'e' on mac to get list of e with accents then nothing happens... there is some work to do.

**Comment by onassar** [comment] 2016-12-20 01:46
@asturur were you able to make any progress here?

**Comment by asturur** [comment] 2016-12-26 20:48
i managed to fix the long press on mac. i submitted a bug on chromium because up to chrome 48 this thing was working enough well, while lately on chrome is completely broken.

**Comment by onassar** [comment] 2016-12-26 22:49
Do you have the hash / commit where you made the change?

**Comment by asturur** [comment] 2016-12-27 06:55
did not commot yet, looks like the fix does not work with firefox. the keyup and keydown event swallow the event and do not let the cursor run over the popup to choose. other than that number selection does not give any hint in what has been selected. text need to be reversed and make oninput event the unique source of truth of the text. i guess how many things i break if i do so.

**Comment by yanzhou-share** [comment] 2017-04-05 07:17
@asturur 
Windows XP
Chrome 51
sogou input method

http://fabricjs.com/kitchensink version:1.6.2  

i-text can not input chinese

**Comment by asturur** [comment] 2017-04-23 09:50
this is fixed on latest master. onInput event is better support and allow for various IME to work.
you can test the code in action here: www.shutterstock.com/editor and try it.

**Closed by asturur** 2017-04-23 09:50 UTC
