### ISSUE TITLE
Patterns and Node.js rendering -  cannot get to work, has anyone been able to?

### ISSUE THREAD

**Issue by samdoidge** [kangax/fabric.js#1728] opened 2014-10-04 14:13 UTC
Patterns and Node.js rendering - cannot get this to work, has anyone been able to?

I encounter one of two issues, depending what fixes I attempt - a black box #1726, or a 'ReferenceError' #1707 . 

A third workaround gives a JSON circular error..

**Comment by asturur** [comment] 2016-05-01 01:54
duplicate of #1707

**Closed by asturur** 2016-05-01 01:54 UTC
Labels: needs_confirmation
