### ISSUE TITLE
Incorrect handling element after insert svg (offset)

### ISSUE THREAD

**Issue by rekzi** [kangax/fabric.js#1443] opened 2014-06-30 22:00 UTC
I create simple figure:
```javascript    
var rect = new fabric.Rect({
   left: 300,
   top: 400,
   fill: 'red',
   width: 20,
   height: 20
});
canvas.add(rect);
```
Generate svg and save to the file. Then I insert it using:
```javascript   
canvas.add.apply(canvas, objects);
canvas.renderAll();
```
I get offset to the left of mouse handle elements.

**Comment by asturur** [comment] 2015-06-18 13:01
as of now is just duplicate of #1520

**Closed by asturur** 2015-06-18 13:01 UTC
Labels: bug
