### ISSUE TITLE
text selection in RTL leng is incorrect 

### ISSUE THREAD

**Issue by Yosi-Azulay** [kangax/fabric.js#3061] opened 2016-06-25 15:27 UTC
hi 

We uses fabric to ruder text and we have text in Hebrew.
the rendering of the text is OK but when we select a text we get the copy (ctrl + C) wrong and the word selection is wrong.

ex: IText.text = "ניסיון לכתוב בעיברית"
Ctrl+C on the first word on the right (RTL) will copy the first word on the left.

we will be glad for a fix or sum giddiness and we will fix it.

tnx

**Comment by asturur** [comment] 2016-08-07 20:07
duplicate of #2374

**Closed by asturur** 2016-08-07 20:07 UTC

**Comment by YaakovHatam** [comment] 2020-05-17 14:54
@Yosi-Azulay  please look at the issue #2374 i am developing a RTL version please test it
