### ISSUE TITLE
Wrong cursor overwriting Textbox's _wrapLine function

### ISSUE THREAD

**Issue by 907796658** [kangax/fabric.js#4769] opened 2018-02-27 08:47 UTC
I was trying to rewrite _wrapLine to achieve at least one character per line instead of a single word, but the cursor was a problem typing text.

https://jsfiddle.net/gyfaLaxv/12/

**Comment by asturur** [comment] 2018-02-27 09:00
To me looks fine. what is the problem?

**Comment by 907796658** [comment] 2018-02-27 09:07
Please enter the text in a different location, the location of the text appear deviation. @asturur

**Comment by up9cloud** [comment] 2018-02-28 02:32
@asturur the ctrl + a(select all) highlight area is buggy. the cursor can't focus at latest character, and then input characters won't show on right position.
see https://jsfiddle.net/nfe3cvfe/135/

**Comment by asturur** [comment] 2018-02-28 23:04
Cannot really dig in custom code. I thin is because fabricJS assumes that if there is a break line, a space has been removed.
But in your case this is not true.

**Comment by asturur** [comment] 2018-02-28 23:08
https://github.com/kangax/fabric.js/issues/2376

Take a read at this old discussion, there was a working prototype for 1.7, we did not want to merge it, but was working

**Comment by asturur** [comment] 2018-02-28 23:08
duplicate of #2376

**Closed by asturur** 2018-02-28 23:08 UTC
