### ISSUE TITLE
Polyline bounding box does not get updated when strockWidth is changed

### ISSUE THREAD

**Issue by Exlord** [kangax/fabric.js#3944] opened 2017-05-18 09:17 UTC
## Version
1.7.11

## Test Case
https://jsfiddle.net/Exlord/f42frk7m/

## Steps to reproduce
Run the Test case and use the selectbox to increase strockewidth.

## Expected Behavior
The shape to get bigger and the bounding box to resize accordingly

## Actual Behavior
The shape grows but the corners of the arrow falls out of the bounding box and they don't get rendered.

Tried `object.setCoords`, had no effect.

**Comment by asturur** [comment] 2017-05-18 20:52
this issue is duplicate of this:
https://github.com/kangax/fabric.js/issues/580

we do not have the math in place to calculate the exact extension of bboxes with acute angles and big stroke widths.

a nice workaround is to use strokeLineCap: round

**Closed by asturur** 2017-05-18 20:52 UTC
