### ISSUE TITLE
'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated.

### ISSUE THREAD

**Issue by litao10422** [kangax/fabric.js#2774] opened 2016-02-06 23:43 UTC
I ran fabric.js and got a warning message:

'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead.<-fabric.js:5996

So I changed 'webkitImageSmoothingEnabled' to 'imageSmoothingEnabled' and confirmed it works well.
I am a newbie of GitHub and have no experience to modify the original codes.
Hope someone modify it and I'll learn it later.
thanks!

//-     ctx.webkitImageSmoothingEnabled   = this.imageSmoothingEnabled;
//+    ctx.imageSmoothingEnabled         = this.imageSmoothingEnabled;

Note: "fabric.js": "fabric#^1.5.0"

**Comment by asturur** [comment] 2016-02-26 10:06
duplicate of #2577. thanks for reporting.

**Closed by asturur** 2016-02-26 10:06 UTC
