### ISSUE TITLE
SVG Curve Clipping

### ISSUE THREAD

**Issue by mariotacke** [kangax/fabric.js#3647] opened 2017-01-25 18:58 UTC
## Version
1.7.0 through 1.7.3 (latest)

## Steps to reproduce (file: [bezier.zip](https://github.com/kangax/fabric.js/files/730678/bezier.zip))
- Import `bezier.svg` to canvas.
- Select bezier curve. 

## Expected Behavior
Bounding box / selection box should not clip path going outside of the rectangle like it did in 1.6.7.

![normal](https://cloud.githubusercontent.com/assets/4942019/22304504/8effe006-e2ec-11e6-8219-1ca4f8a19e12.png)
![normal_with_bounding-rect](https://cloud.githubusercontent.com/assets/4942019/22304507/918e6824-e2ec-11e6-88a5-c073fa7c17f2.png)

## Actual Behavior
1.7.0 and forward clip SVG path going outside of bounding box.

![abnormal](https://cloud.githubusercontent.com/assets/4942019/22304512/94e204d6-e2ec-11e6-87be-182d22c104b2.png)
![abnormal_with_bounding-rect](https://cloud.githubusercontent.com/assets/4942019/22304516/96c1cfde-e2ec-11e6-9da4-4dacda488a75.png)

Is there a way to disable clipping?

**Comment by asturur** [comment] 2017-01-25 19:17
duplicate of #3446

for disable clipping please read here:
fabricjs.com/fabric-object-caching

**Closed by asturur** 2017-01-25 19:17 UTC
