### ISSUE TITLE
Wrong path position in free drawing mode

### ISSUE THREAD

**Issue by daoenpan** [kangax/fabric.js#4215] opened 2017-08-17 12:15 UTC
## Version
2.0.0-beta.6

## Test Case
http://fabricjs.com/freedrawing

## Steps to reproduce
draw something in free draw mode

## Expected Behavior
after mouse up event the path should be the same as drawed

## Actual Behavior
The path is shifted up and left, not the same. 

The reason may be that the new path is set as 'originX: center' and 'originY: center'

**Comment by av01d** [comment] 2017-08-17 12:18
Duplicate of #4201

**Closed** 2017-08-17 12:25 UTC
