### ISSUE TITLE
Minimum scaling limit

### ISSUE THREAD

**Issue by ozooner** [kangax/fabric.js#2373] opened 2015-07-29 20:52 UTC
Hi,

I have come across an issue where object that is scaled below 10% gets re-scaled to 10% of (either scaleX or scaleY or both) only if it's loaded from JSON the first time (the scaling would stick on consecutive load within the same DOM). Anyway, playing around with the code I discovered that setting the value on [this](https://github.com/kangax/fabric.js/blob/master/src/shapes/object.class.js#L917) line to 0.01 instead would fix the issue. I am uncertain if the 0.1 there is for a reason or not, therefore not creating a pull request.

**Comment by asturur** [comment] 2015-07-29 21:58
duplicate of #2329

**Closed by asturur** 2015-07-29 21:58 UTC
