### ISSUE TITLE
Weird SVG with mask filter doesn't load correctly

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4263] opened 2017-08-30 21:00 UTC
## Version
From 1.7.6 to 2.0.0

## Test Case
http://jsfiddle.net/526wC/162/

## Steps to reproduce
Click to load the first SVG of the dropdown.
Change the SVG in the dropdown to second one. It's the same SVG but without <mask> weird nodes. 
This SVG come from NounProject. 

## Expected Behavior
SVG should look like this:
<img width="313" alt="screen shot 2017-08-30 at 22 58 49" src="https://user-images.githubusercontent.com/8090162/29894759-d3a38ccc-8dd6-11e7-84c1-fcd3b7533f63.png">

## Actual Behavior
Actually it looks like this:
<img width="158" alt="screen shot 2017-08-30 at 22 59 21" src="https://user-images.githubusercontent.com/8090162/29894774-e2bd194e-8dd6-11e7-960f-6e973b9e2361.png">
And if you remove the mask node in the SVG, Fabric can load it like this:
<img width="152" alt="screen shot 2017-08-30 at 22 59 50" src="https://user-images.githubusercontent.com/8090162/29894783-f1b5737e-8dd6-11e7-98ae-3de83ce7d31b.png">

**Comment by asturur** [comment] 2017-08-30 21:08
mask not supported yet from fabricjs.
duplicate of #1360 

Adding mask support should not be super hard nor impossible.
Just requires some time.

Could you post the SVG file here in code brackets?

```
```xml
// your svg
` ``
```

**Closed by asturur** 2017-08-30 21:08 UTC

**Comment by blobinabottle** [comment] 2017-08-31 22:27
```<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" viewBox="0 0 100 100" style="enable-background:new 0 0 100 100;" xml:space="preserve"><style type="text/css">
	.st0{filter:url(#b);}
	.st1{filter:url(#Adobe_OpacityMaskFilter_1_);}
	.st2{mask:url(#a);fill:#FFFFFF;}
	.st3{fill:#FFFFFF;}
	.st4{filter:url(#Adobe_OpacityMaskFilter_2_);}
	.st5{fill:#FFFFFF;stroke:#000000;stroke-width:0.9758;stroke-miterlimit:10;}
	.st6{mask:url(#SVGID_2_);}
	.st7{filter:url(#Adobe_OpacityMaskFilter_3_);}
	.st8{mask:url(#SVGID_3_);}
	.st9{filter:url(#Adobe_OpacityMaskFilter_4_);}
	.st10{mask:url(#SVGID_4_);}
	.st11{filter:url(#Adobe_OpacityMaskFilter_5_);}
	.st12{mask:url(#SVGID_5_);}
	.st13{filter:url(#Adobe_OpacityMaskFilter_6_);}
	.st14{fill:none;stroke:#FFFFFF;stroke-miterlimit:10;}
	.st15{fill:none;stroke:#FFFFFF;stroke-width:1.1381;stroke-miterlimit:10;}
	.st16{mask:url(#SVGID_6_);}
	.st17{filter:url(#Adobe_OpacityMaskFilter_7_);}
	.st18{fill:none;stroke:#000000;stroke-width:2.4607;stroke-miterlimit:10;}
	.st19{mask:url(#SVGID_7_);}
	.st20{filter:url(#Adobe_OpacityMaskFilter_8_);}
	.st21{fill:none;stroke:#FFFFFF;stroke-width:7.8671;stroke-miterlimit:10;}
	.st22{fill-rule:evenodd;clip-rule:evenodd;fill:#FFFFFF;}
	.st23{mask:url(#SVGID_8_);}
	.st24{filter:url(#Adobe_OpacityMaskFilter_9_);}
	.st25{mask:url(#SVGID_9_);}
	.st26{display:none;}
	.st27{display:inline;}
	.st28{fill:none;stroke:#000000;stroke-miterlimit:10;}
</style><g><defs><filter id="b" filterUnits="userSpaceOnUse" x="4.3" y="5.2" width="90" height="90"><feColorMatrix type="matrix" values="-1 0 0 0 1  0 -1 0 0 1  0 0 -1 0 1  0 0 0 1 0" color-interpolation-filters="sRGB" result="source"/><feFlood style="flood-color:white;flood-opacity:1;" result="back"/><feBlend in="source" in2="back" mode="normal"/></filter></defs><mask maskUnits="userSpaceOnUse" x="4.3" y="5.2" width="90" height="90" id="a"><g class="st0"><g><path class="st3" d="M49.2,58.3L49.2,58.3c1.5,0,3,0.2,4.4,0.5c5.3,1.3,8.9,4.9,8.9,8.7s-3.7,7.4-8.9,8.7      c-1.4,0.3-2.9,0.5-4.4,0.5c-6.3,0-13.1-3.2-13.1-9.2C36.1,61.5,42.9,58.3,49.2,58.3 M49.2,57.3c-7.2,0-14.1,3.8-14.1,10.2      c0,6.4,6.9,10.2,14.1,10.2c1.6,0,3.1-0.2,4.7-0.5c6-1.4,9.7-5.6,9.7-9.7c0-4.1-3.7-8.2-9.7-9.7C52.3,57.4,50.7,57.3,49.2,57.3      L49.2,57.3z"/></g><g><path class="st3" d="M48.9,64.1c-0.8-1-19.8-24-14.4-35.7c2-4.2,6.9-6.4,14.8-6.4s12.8,2.1,14.8,6.4      c5.4,11.6-13.6,34.7-14.4,35.7l-0.4,0.5L48.9,64.1z"/><path d="M49.3,22.6c34.3,0,0,41.2,0,41.2S15,22.6,49.3,22.6 M49.3,21.6c-8,0-13.1,2.2-15.2,6.7c-5.6,11.9,13.6,35.2,14.4,36.2      l0.8,0.9l0.8-0.9c0.8-1,20-24.3,14.4-36.2C62.5,23.8,57.3,21.6,49.3,21.6L49.3,21.6z"/></g><g><path d="M49.3,28.3c4.5,0,8.2,3.7,8.2,8.2s-3.7,8.2-8.2,8.2s-8.2-3.7-8.2-8.2S44.8,28.3,49.3,28.3 M49.3,27.3      c-5.1,0-9.2,4.1-9.2,9.2s4.1,9.2,9.2,9.2s9.2-4.1,9.2-9.2S54.4,27.3,49.3,27.3L49.3,27.3z"/></g></g></mask><circle style="mask:url(#a);" cx="49.3" cy="50.2" r="45"/></g></svg>
```
This is the svg as it is from noun project.
