### ISSUE TITLE
Issue with triangles and borders, bounding box clipped corners.

### ISSUE THREAD

**Issue by antucg** [kangax/fabric.js#3524] opened 2016-12-12 10:30 UTC
Version 1.7.1

Hi guys, there is a problem in how bounding box is calculated. When I render a triangle, and I set strokeWidth to any value, corners are clipped. You can see it in next fiddle.

https://jsfiddle.net/pwrmwgku/

Fabric should take into consideration that corners are slightly bigger, so bounding box will adapt to it.

**Comment by asturur** [comment] 2016-12-13 08:14
duplicate of #580
Also give a read to this:
http://fabricjs.com/fabric-object-caching
The final section.
I should add object with sharp angles and big strokewidth.

**Closed** 2016-12-13 08:16 UTC
