### ISSUE TITLE
Fabricjs transform letters

### ISSUE THREAD

**Issue by dangyoungworld** [kangax/fabric.js#3428] opened 2016-11-18 04:05 UTC
## Version
1.6.5
## Actual Behavior
Thank FabricJS,
How using fabricJS for transform letters? 
View EX http://imgur.com/a/Mh5VD

**Comment by asturur** [comment] 2016-11-19 07:12
duplicate of https://github.com/kangax/fabric.js/issues/729

You can copy some code from there or ask help on stackoverflow. The feature is not supported yet

**Closed by asturur** 2016-11-19 07:12 UTC
