### ISSUE TITLE
text alignment issue while using export and import as svg

### ISSUE THREAD

**Issue by Cod1ngNinja** [kangax/fabric.js#2584] opened 2015-10-27 06:47 UTC
Text added on the canvas once exported as SVG and imported to canvas, is not aligning the same way as it's original

http://jsbin.com/ruluko/edit?html,js,output

using fabric js v1.6.0-rc.1

**Comment by asturur** [comment] 2015-10-27 06:55
duplicate of #1280

**Closed** 2015-10-27 06:55 UTC
