### ISSUE TITLE
free draw mode doesn't work on phone

### ISSUE THREAD

**Issue by wilson-weng** [kangax/fabric.js#4024] opened 2017-06-21 07:21 UTC
I can use the demo to free draw on web, but when I switch chrome simulator to mobile device, I can no longer draw a line. 
Please help how can I enable free draw on phone h5 page

**Comment by Tsunami2069** [comment] 2017-06-22 11:15
I'm pretty sure that is some issue with the demo page itself running on the chrome simulated mobile device.

We have recently developed a project for a client of ours that would manage all their assistance requests and help desk stuff. Whenever he would go to one of his clients to fix something, etc, he would ask the client to fill a little form on a mobile device about the provided assistance. That form had to have a signature section for the client to sign the form and we used a small little canvas with free drawing mode for the signature part.

It worked like a charm.

**Comment by asturur** [comment] 2017-06-22 11:16
i got a touch device today, still to pick it up.
I hope lot of touch issues can be checked now.

**Comment by asturur** [comment] 2017-07-03 23:06
duplicate of #3869

**Closed by asturur** 2017-07-03 23:06 UTC

**Comment by majidalimughal** [comment] 2019-09-25 07:32
When I try to draw line using fabric js free drawing tool attached below
http://fabricjs.com/freedrawing
I can draw the line
but when I release the mouse line suddenly disappears
