### ISSUE TITLE
is freeDraw with multiple fingers possible?

### ISSUE THREAD

**Issue by lethanhquang** [kangax/fabric.js#2303] opened 2015-06-23 08:58 UTC
Hello Guys,

I'm new in fabric, in my project, I would like to use freeDraw function to serve for multiple people in the same time.

Is this possible with fabric? And how can I do that? I can't find any direction on docs.

Thanks,

**Comment by kangax** [comment] 2015-06-23 18:51
I don't think it works now, although we do support gestures (through optional gestures module) for rotating/resizing object with 2 fingers. It should be possible to make free drawing work too. Pull request is super welcome, as always!

**Comment by asturur** [comment] 2015-08-10 07:16
duplicate of #992.

**Closed by asturur** 2015-08-10 07:16 UTC
Labels: possible_feature
