### ISSUE TITLE
Feature request - Object caching

### ISSUE THREAD

**Issue by gordyr** [kangax/fabric.js#814] opened 2013-08-29 16:53 UTC
Fabric.js is in my opinion very well written with excellent overall performance.

However there are occasions where the performance is drastically reduced due to performance limitations of the html5 canvas API and not down to fabric itself.

Two of these occasions are:

- When manipulating a text object using a very complex font or with a textShadow applied
- When manipulating objects with shadows turned on (particularly with a large blur radius)

Having gotten quite familiar with the source code over the last few weeks I can see a very clear way of rectifying these performance issues while dramatically increasing overall manipulation performance across the board.

My proposal is to cache objects (on demand, not continuously) as off screen canvas's so that during manipulations (moving, rotating etc) the object is drawn to the canvas using drawImage() rather then being completely redrawn.

The flow as I see it would go as follows:

- when mousedown occurs on an object an offscreen canvas is temporarily created

- the temporary canvas is set to the size and width of the object and the object is rendered to this canvas instead of the main lower one

- during manipulations the the _render() is halted and drawImage(), using the temporary canvas as the source element, is called instead.

- on mouseup the temporary canvas is nulled to avoid creating excessive in memory canvases.

I have been hacking away at the fabric source code and have implemented this myself.  For text objects that use extremely complex fonts or ones with text shadows etc, the performance increase is from about 10fps up to 60fps.  The same goes for image objects with shadows set.  The visual result is identical to rendering the objects each frame, just much faster.

Everything works beautifully for moving and rotating however my implementation currently leaves an issue with scaling.  Since we are dealing with a canvas element the quality changes as you scale, then on mouseup is re-rendered correctly.  This is mostly only an issue when scaling up, but for text it is also heavily noticable when scaling down.

In order to get around this some sort of throttle or timer could be used to rebuild the cached canvas at the new size in the background.  Hopefully leaving the visual difference almost imperceptible.  So far I haven't managed to get around to attacking this yet.

Implementing the above is actually relatively simple, but with my lack of knowledge of Fabric's inner workings (particularly around the scaling/rendering) means that my code is perhaps more complex than it needs to be, hence my leaving it as a feature request rather than making a pull request.

Also... Another huge benefit of using the above method mean it solves a large bug in Chrome on Windows....

Currently in Chrome on windows when rotating a text object the letter jiggle continuously.  I assume this is down to Chrome not properly implementing sub-pixel rendering on canvas text objects.  Using the above caching method this jiggling completely disappears.

I would be interested to hear your thoughts Kangax.

**Comment by asturur** [comment] 2016-05-23 09:40
duplicate of #318

**Closed by asturur** 2016-05-23 09:40 UTC
Labels: feature
