### ISSUE TITLE
iPad Pro Pencil: Draws lines in canvas when tapping outside the canvas

### ISSUE THREAD

**Issue by homerlex** [kangax/fabric.js#3946] opened 2017-05-18 19:29 UTC
FabricJS Version: 1.7.9
Apple iPad Pro iOS: 10.2

We have an app with a free drawing canvas.  Along the outside of the canvas we have various buttons for changing pen size, color etc.  When the user has an apple pencil the will usually have their palm inside the canvas and touch the various button with the pencil.  From time to time (doesn't happen every time but its pretty easy to duplicate) when the touch the pencil to a button a line is drawn across the canvas from the user's palm location to the edge of the canvas inline with where they touched the pencil.

I am able to duplicate the in Safari and Chrome on the iPad using the freedrawing demo page: http://fabricjs.com/freedrawing

Here is an image that shows where my palm was, where the pencil touched and where the line was drawn:
![image](https://cloud.githubusercontent.com/assets/296630/26219730/0711f5bc-3bde-11e7-9271-ada4e4728c6c.png)

Is this a known issue or does anyone have and idea what might be causing this and how to possibly fix it?

**Comment by asturur** [comment] 2017-05-18 20:06
what events the pencil fires?

**Comment by homerlex** [comment] 2017-05-19 13:20
@asturur - I put some debugs in to see which events are being fired.

When the palm touches one of 3 things can occur:

- No events are fired.  In this case the problem doesn't happen.
- Two events are fired:  _onMouseDown ["touchstart"] and _onMouseUp ["touchend"].  Again, no problem when this occurs.
- One event is fired: _onMouseDown ["touchstart"].  In this scenario we have the problem.  I can even lift my palm off the screen at this point (and no other events are fired) and touch the pen outside the canvas to draw the line.

Here are all the events when duplicating the problem:

- Palm touches the canvas: _onMouseDown ["touchstart"] 
- Pen touches outside the canvas: _onMouseMove ["touchmove"] (might get a few of these) and _onMouseUp ["touchend"]

Instead of trying to deal with the inconsistent events (probably due to some iOS palm rejection thingy) would it be easy to detect that the touchmove is outside the canvas and not draw?

-

**Comment by asturur** [comment] 2017-05-19 13:26
i have to see what happen, why an event out of canvas still trigger something on canvas. maybe is the mouseOut logic.

**Comment by homerlex** [comment] 2017-05-19 13:43
Could it have to do with the fact that there is no "mouseout" fired on mobile devices?

**Comment by asturur** [comment] 2017-07-03 23:05
duplicate of #3869

**Closed by asturur** 2017-07-03 23:05 UTC
