### ISSUE TITLE
text space and strokeWidth problem

### ISSUE THREAD

**Issue by M3TRIKX** [kangax/fabric.js#4208] opened 2017-08-16 11:24 UTC
Hi, I have 2 problems with Fabric.js iText.

I have a problem with text in Fabric.js. I want to use handwriting font "Alex Brush" in my app. The text is starting a bit out of box. At the end of the text is the same problem - text ends out of the box.
Second problem appears, if strokeWidth is too high, it becomes ugly, as you can see on picture (link below).

Thanks for any help or solution.

PS: Please, copy link and paste in new tab. Image is from outside, so after clicking, github will show an error.

[https://i.stack.imgur.com/78V8M.png](url)

**Comment by asturur** [comment] 2017-08-16 11:44
For the stroke problem there are just 2 solutions
1) use strokeLineCap: round for your objects
2) contact font author and make him/her fix the spikes.

For the out of bounds solutions this issue is a duplicate of #1108

**Closed by asturur** 2017-08-16 11:44 UTC
