### ISSUE TITLE
Custom build and .npmignore

### ISSUE THREAD

**Issue by daer-ru** [kangax/fabric.js#3429] opened 2016-11-18 09:28 UTC
## Version
1.6.3

Hi.
I install fabric with npm and i want to create custom build but i can't because i need /lib folder, HEADER.js etc.
How can i create custom build without cloning repo?

**Comment by asturur** [comment] 2016-11-18 11:35
you can not as of now. It has been asked some time, we are thinkgin if pushing source in the npm package.

**Comment by asturur** [comment] 2016-11-18 11:35
duplicate of #3419

**Closed by asturur** 2016-11-18 11:35 UTC
