### ISSUE TITLE
Canvas.toSVG() globalcompositeoperation not working

### ISSUE THREAD

**Issue by basilinjoe** [kangax/fabric.js#3763] opened 2017-03-05 13:28 UTC
## Version
1.7.6

## Test Case
https://jsfiddle.net/basilin/1u5wa44s/

## Steps to reproduce

- load a svg
- load an image with `globalCompositeOperation = 'source-atop'`  
- get svg out using `canvas.toSVG()` methood

## Expected Behavior

- svg looks as same as rendered canvas

## Actual Behavior

- `globalCompositeOperation ` has no effect

**Comment by asturur** [comment] 2017-03-05 14:46
global.composite operation is supported as per canvas just on internet explorer.

browser like chrome and firefox decided to do not implement it.

try on w3c the global.composite svg example and it does not render on browsers.

**Comment by asturur** [comment] 2017-03-05 14:52
duplicate of #1883

**Closed by asturur** 2017-03-05 14:52 UTC

**Comment by neopheus** [comment] 2017-03-06 23:59
hi asturur,

Are you sure ?
I have already worked on firefox with global composite

Source : https://developer.mozilla.org/fr/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation
Example : https://jsfiddle.net/api/mdn/

And i try with Chrome it's ok

**Comment by neopheus** [comment] 2017-03-07 00:00
hi asturur,

Are you sure ?
I have already worked on firefox with global composite

Source : https://developer.mozilla.org/fr/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation
Example : https://jsfiddle.net/api/mdn/

And i try with Chrome it's ok

**Comment by asturur** [comment] 2017-03-07 08:51
we are talking of toSVG output
