### ISSUE TITLE
obj.center() does not center object on canvas when the canvas has viewportTransform set.

### ISSUE THREAD

**Issue by teewuane** [kangax/fabric.js#1641] opened 2014-09-05 09:38 UTC
Create an object and add it to a canvas that has viewportTransform defined. Then try to center that object. The object is not centered. (close, but not quite) If you set the canvas zoom back to it's default value of 1 it will zoom in and the rectangle is then centered but it's now zoomed back in. `canvas.setZoom(1);` 

See example here: http://jsfiddle.net/teewuane/c16rjtj7/1/

**Comment by asturur** [comment] 2015-04-01 15:52
please follow #2021 for update of this old question.

**Comment by kangax** [comment] 2015-04-06 11:02
Duplicate of #2021

**Closed by kangax** 2015-04-06 11:02 UTC
