### ISSUE TITLE
Strange behaviour of textbox resizing

### ISSUE THREAD

**Issue by daoenpan** [kangax/fabric.js#4481] opened 2017-11-21 00:25 UTC
## Version
2.0.0-rc.1

## Test Case
http://model.future-models.com/bug/fabric-bug.htm

## Steps to reproduce

1. select the textbox, 
2. increase the width of textbox with dragging of right border

The left border starts to jumping.

3. if you drag to right more quickly, the textbox will increase to left, 
then it will be unselectable on the left side.

## Expected Behavior

This bug does not exists in version 2.0.0-beta.7

**Comment by daoenpan** [comment] 2017-11-21 00:32
if the texbox is set with originX: 'center' and originY: 'center', there will be no jumping.

**Comment by blobinabottle** [comment] 2017-11-21 13:07
I think it's duplicate with https://github.com/kangax/fabric.js/issues/4461

**Comment by asturur** [comment] 2017-11-23 16:46
Duplicate of #4461

**Closed by asturur** 2017-11-23 16:46 UTC
