### ISSUE TITLE
Newline removed after load svg from url

### ISSUE THREAD

**Issue by morfius246** [kangax/fabric.js#2751] opened 2016-01-22 18:21 UTC
Hi
I'm trying to load svg from url to canvas.
Original svg
![image](https://cloud.githubusercontent.com/assets/8141926/12519036/f5d893b0-c144-11e5-8dd6-7e91d4913654.png)
After load svg to canvas
![image](https://cloud.githubusercontent.com/assets/8141926/12519075/3cffe89c-c145-11e5-87bc-de6b72d55a79.png)
Seem like parser delete all newline.
Code I use:
>fabric.loadSVGFromURL(path, function (objects, options) {
           var obj = fabric.util.groupSVGElements(objects, options);
           self._canvas.add(obj).renderAll();
        });

Thanks in advance.
Best Regards

**Comment by asturur** [comment] 2016-01-22 18:53
There is no newline in svg text.
There is just missing support  for tspans.
Can i have this svg for testing?

**Comment by morfius246** [comment] 2016-01-22 21:46
http://my-files.ru/Save/sorqy9/file.svg

**Comment by morfius246** [comment] 2016-01-25 13:21
Have something new about this issue?

**Comment by asturur** [comment] 2016-01-25 14:51
no is a long task that i will take over after event in group is completed.

**Comment by morfius246** [comment] 2016-01-27 10:30
Can I replace tspan for something in my svg?

**Comment by asturur** [comment] 2016-01-27 10:38
You can do all separate text elements. Check tspans for x,y,dx and dy
attributes and add those values to the x and y of the text. dx and dy must
be addded, while x and y of tspan change the one of the text.

example:
<text x=2 y=2><tspan dx=0 dy=10 >a</tspan><tspan x=4 y=5>b</tspan></text>

equals (should...):
<text x=2 y=12>a</text><text x=4 y=5>b</text>

if no x and y are present on tspan is more difficult to understand the flow.



2016-01-27 11:30 GMT+01:00 Alexander <notifications@github.com>:

**Comment by morfius246** [comment] 2016-01-27 10:43
Thank you, I'll try

**Comment by morfius246** [comment] 2016-01-27 10:46
This is example of tspans in my document
https://d1ro8r1rbfn3jf.cloudfront.net/ms_89741/eiEMM7ACu6o5NxX3DclrTAQVFO90LK/C__Users_%25D0%2593%25D1%2580%25D0%25B5%25D0%25B1%25D0%25B5%25D0%25BD%25D1%258E%25D0%25BA_Downloads_sample-plans.1.svg%2B-%2BInternet%2BExplorer%2B2016-01-27%2B12.24.22.png?Expires=1453977927&Signature=mh6j~lHndp7oSvAVIe8DCuIIDzRHevTCxB2AwnX3ag51Yi3nyG0SFBpVuPf4GO6lqDav3O5Haebu0dj~TYJmEbg6CZH79BuRBZGLhLzufwh3AxkQHC~T6BWilLz4oAvUy9Gp1gM8BjhvYkC~4ebaKni3GOjj2Hxyiql3VU1YnbDQ~FYwDQSHF8U-iXGqo00sMoiD3IT7CB4CaZ~iUstUxydL2a-n9-w5as-xlheZ7kAgaDc1ArY2iVD5I8bNQdA-JcgeeaYcdr-OpOV0pHHV0~Tn6CTky0WoA4DczJS11pb3T871nDgAJXEktYi5hR01S-Xeyv1XmlPlHpJY6vnBcQ__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA

**Comment by morfius246** [comment] 2016-01-27 10:48
This is example of tspans in my document
![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_89741/eiEMM7ACu6o5NxX3DclrTAQVFO90LK/C__Users_%25D0%2593%25D1%2580%25D0%25B5%25D0%25B1%25D0%25B5%25D0%25BD%25D1%258E%25D0%25BA_Downloads_sample-plans.1.svg%2B-%2BInternet%2BExplorer%2B2016-01-27%2B12.24.22.png?Expires=1453977927&Signature=mh6j~lHndp7oSvAVIe8DCuIIDzRHevTCxB2AwnX3ag51Yi3nyG0SFBpVuPf4GO6lqDav3O5Haebu0dj~TYJmEbg6CZH79BuRBZGLhLzufwh3AxkQHC~T6BWilLz4oAvUy9Gp1gM8BjhvYkC~4ebaKni3GOjj2Hxyiql3VU1YnbDQ~FYwDQSHF8U-iXGqo00sMoiD3IT7CB4CaZ~iUstUxydL2a-n9-w5as-xlheZ7kAgaDc1ArY2iVD5I8bNQdA-JcgeeaYcdr-OpOV0pHHV0~Tn6CTky0WoA4DczJS11pb3T871nDgAJXEktYi5hR01S-Xeyv1XmlPlHpJY6vnBcQ__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by morfius246** [comment] 2016-01-27 11:03
Should I copy transform and style attributes to all of text elements?

**Comment by asturur** [comment] 2016-01-27 11:17
For transform and style make a <g> that envelops text and put them there.
I do not know this strange x="value1 value2 value3" attribute. i cannot really help.

Try to replace <tspan> with <text> and <text> with <g>, make a simple try i cannot help further, it changes from doc to doc.

**Comment by asturur** [comment] 2016-02-26 16:30
duplicate of #1280

**Closed by asturur** 2016-02-26 16:30 UTC
