### ISSUE TITLE
canvas textbox outputing inconsistent JSON/svg

### ISSUE THREAD

**Issue by jj-dev** [kangax/fabric.js#3375] opened 2016-10-25 11:22 UTC
## Version
1.6.2

## Steps to reproduce
JSON.stringify(canvas);
canvas.toSVG();

## Expected Behavior
Consistent output in the JSON string/svg code.

## Actual Behavior

Have found that calling JSON.stringify and .toSVG(); on the canvas produced inconsistent output with textboxes.

The JSON.stringify resulted in an empty styles property on one of the textbox objects out of four.

`

         "styles":{

         },

`

The SVG content had the text as one complete string 

`<tspan x="-723.91" y="-31" fill="#000000">Thank you for always being there</tspan>`

whilst the others with styles had individual x/y for each letter.
`

         "styles":{
            "0":{
               "0":{

               },
               "1":{

               },

`

`<tspan x="-723.91" y="-31" style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(0,0,0); fill-rule: ; opacity: 1;">T</tspan>`

The work around for those affected is to set a value for the styles object (it doesn't need one for each letter just the parent 0 key). When you load it back in and then export the svg it produces the correct output where each letter is a separate tspan.

`

        "styles":{
            "0":{}
         },

`

Here's what I've had to do:

`

        var json = JSON.stringify(canvas);

        var json = json.replace('"styles":{}', '"styles":{"0":{}}');

        canvas.clear();
        canvas.loadFromJSON(json, function(){
          canvas.renderAll();
        });
        var svg = canvas.toSVG();
`

Files attached.
[example.zip](https://github.com/kangax/fabric.js/files/550436/example.zip)

**Comment by asturur** [comment] 2016-10-25 15:57
are they visually inconsistent?

**Comment by jj-dev** [comment] 2016-10-25 16:28
Very close but not identical.

![output-overlayed](https://cloud.githubusercontent.com/assets/23052663/19694501/77246860-9ad7-11e6-95fb-8a95cf8862e8.png)

The way the bug was found was using the outputted svg with FPDI / TCPDF and using the $pdf->ImageSVG method to add the vector layer to a pdf.

The difference is significant.

![before](https://cloud.githubusercontent.com/assets/23052663/19694678/39b08e0e-9ad8-11e6-95ee-fb94db811e82.png)

![after](https://cloud.githubusercontent.com/assets/23052663/19694684/3eb076d0-9ad8-11e6-943e-87f55517d771.png)

**Comment by asturur** [comment] 2016-10-26 08:52
duplicate of #3377 
if rendered span by span the font kerning is not respected. Nor by canvas nor by svg because we manually space the next char for the full width of the character. I cannot do anything about it for now, unless some font metric api expose the kerning information.
What i can do is ensure that empty styles get detected and eliminated.

**Closed by asturur** 2016-10-26 08:52 UTC
