### ISSUE TITLE
fabric.js : 5995 warning 

### ISSUE THREAD

**Issue by soojinkim22** [kangax/fabric.js#2114] opened 2015-04-16 01:23 UTC
![warning](https://cloud.githubusercontent.com/assets/5974821/7172330/c721a842-e420-11e4-8d39-85d5a86a24c7.png)

hello :) it just warning.
today i was updated fabric.js version 1.4.8 to 1.5.0 and found this warning.
so i removed this line, solved it.
thank you

**Comment by kangax** [comment] 2015-04-16 11:37
Duplicate of #2047

**Closed by kangax** 2015-04-16 11:37 UTC
