### ISSUE TITLE
JS Error when calling discardActiveObject()

### ISSUE THREAD

**Issue by yerfinojul** [kangax/fabric.js#3320] opened 2016-10-03 13:16 UTC
## Version
1.6.5

## Test Case
http://jsfiddle.net/ftxjwfh9/2/

## Steps to reproduce
Simple add an iText to canvas, remove it, add a new one and then call discardActiveObject()
This started happening after update to 1.6.5, works fine with 1.6.4

## Expected Behavior

No JS Error

## Actual Behavior

JS Error on the console
```
VM1140 fabric.js:23496 Uncaught TypeError: Cannot read property '_iTextInstances' of undefined
```

I believe it's not deregistering to events correctly when removed

**Comment by asturur** [comment] 2016-10-04 07:03
i added removal of canvas reference on onObjectRemoved, it looks like this is happening before the 'removed' event. is a bug, thanks for spotting.

**Comment by asturur** [comment] 2016-10-06 07:09
i verified on kitchensink the error does not appear.
The fabricjs fiddle posted has 3 libraries linked
on node i cannot reproduce the issue
I m gonna close it for now unless we  found a clean way to reproduce it.

**Closed** 2016-10-06 07:18 UTC
Labels: bug

**Comment by yerfinojul** [comment] 2016-10-06 13:09
You are right about the 3 libraries linked @asturur but I updated the fiddle and it's still happening https://jsfiddle.net/uecqhron/3/

If i don't call discardActiveObject() but rather click on the text I observe the same js error.

**Comment by ziomio** [comment] 2016-10-07 06:49
This error happens even without calling discardActiveObject();
Just add/remove IText and then make an empty area selection.
http://jsfiddle.net/qcvjcx8m/

**Comment by asturur** [comment] 2016-10-07 07:24
Still the fiddle is with 3 fabricjs.
Did you try if on kitchensink it fails?

www.fabricjs.com/kitchensink

**Comment by ziomio** [comment] 2016-10-07 07:48
@asturur I've updated fiddle with 1 fabricjs.
Error is still here https://jsfiddle.net/vb8x2ecu/

**Comment by asturur** [comment] 2016-10-07 20:49
ok now it makes sense.
This is a long standing bug that was not coming out because canvas reference was still in the object.
Gonna fix this

**Comment by samael205** [comment] 2016-10-07 20:55
Today I received three times this type of error. When I created a text type, and when trying to select, I continually jump.

**Comment by asturur** [comment] 2016-10-07 21:06
you have to remove it to get the error.
Otherways should be fine

**Comment by asturur** [comment] 2016-10-09 06:48
https://github.com/kangax/fabric.js/pull/3332

please give it a shot when it get merged. you have to build the library by yourself or wait for a quick 1.6.6 release
