### ISSUE TITLE
Is that possible to load a complicated SVG object?

### ISSUE THREAD

**Issue by neilliang** [kangax/fabric.js#4047] opened 2017-06-30 08:37 UTC
I have searched many issues about fabricjs drawing complicate svg object. Actually I'm still not really sure what kind of situation might cause the problem. I have made a mask svg object with illustrator. I got the result in fabric js as bellow.

![image](https://user-images.githubusercontent.com/1026331/27727670-0346f450-5db2-11e7-8798-1f5932554683.png)

Actually it should look like this in illustrator.

![image](https://user-images.githubusercontent.com/1026331/27727679-1244afce-5db2-11e7-92c6-3fc0a9cc41f4.png)

SVG code
---------------------------------------------------------------------------

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 469.89 352.41">
	<defs>
		<clipPath id="a">
			<polygon points="351.95 334.48 245.14 276.38 136.71 331.43 158.97 211.88 73.11 125.78 193.68 110 249.04 1.73 301.3 111.53 421.37 130.72 333.1 214.35 351.95 334.48" style="fill:none"/>
		</clipPath>
	</defs>
	<title>image mask</title><g style="clip-path:url(#a)">
		<image width="1600" height="1200" transform="scale(0.29)" xlink:href="https://goo.gl/UG726c"/>
		<text transform="translate(29.27 224.07)" style="font-size:121.61222839355469px;font-family:Helvetica75-Bold, Helvetica75 Bold;font-weight:700">HAP<tspan x="218.41" y="0" style="letter-spacing:-0.00898572003765631em">P</tspan>
			<tspan x="282.02" y="0" style="letter-spacing:0.000008030134081909124em">Y</tspan>
		</text>
	</g>
</svg>
```

------------------------------------------------------------------------------

If I want to create this kind of svg objects, any suggestion? Thanks.

**Comment by asturur** [comment] 2017-06-30 09:02
duplicate of #1360

**Closed by asturur** 2017-06-30 09:02 UTC
