### ISSUE TITLE
IText exitEditing, enterEditing does not work properly

### ISSUE THREAD

**Issue by kingkrausel** [kangax/fabric.js#1740] opened 2014-10-11 12:58 UTC
In the latest version of chrome (38.0.2125.101 m) the IText methods exitEditing and enterEditing do not work properly in the following scenario:

```javascript
var text = new fabric.IText('text');
canvas.add(text);
//now click on the text and change it to '123'
//keep the IText selected as it is (in editing mode)
text.exitEditing();
text.enterEditing(); //now in editing mode, cursor on correct position
//now press the keys 4,5 and 6 on your keyboard
//text changes from '123' to '12356', i.e. the first key press is not processed correctly
```

So the first new input after entering editing mode gets lost. This was working for an older version of chrome, unfortunately, I can not tell which version it was. I used fabric 1.4.11 for the test.

**Comment by LIDJungle** [comment] 2015-01-13 14:31
Thanks for the fix! This one had me too for 15 minutes.

**Comment by asturur** [comment] 2015-01-21 02:29
@kangax if this is a bug we can solve it adding this.hiddenTextare.focus() on EnterEditing().
If this is not a bug and calling the focus is left to the user, we should close this issue.

**Comment by asturur** [comment] 2015-02-04 16:44
What do you think @kangax
Should the user call the setfocus by himself, if he want to enterEditing without using the mouse, or should we put this.hiddenTextarea.focus()  inside the enterEditing method?

**Comment by kangax** [comment] 2015-02-05 10:49
I think we should definitely set focus when calling `enterEditing` since `enterEditing` is supposed to be programmatic way of entering edit state (identical to user clicking the field).

**Closed** 2015-02-05 16:08 UTC
Labels: itext
