### ISSUE TITLE
iOS/Android double cursor when editing IText

### ISSUE THREAD

**Issue by faysal-ali** [kangax/fabric.js#3376] opened 2016-10-25 17:52 UTC
Goto http://fabricjs.com/kitchensink from iOS or Android and start editing any text you will see 2 different cursors.
Does anybody know why is this happening only on mobile browsers but not on desktop or laptops?

Image: http://imgur.com/a/6s5iO

**Comment by asturur** [comment] 2016-10-26 08:18
duplicate of #3232

**Closed by asturur** 2016-10-26 08:18 UTC
