### ISSUE TITLE
Object above currently active object could not be selected

### ISSUE THREAD

**Issue by vudduu** [kangax/fabric.js#3175] opened 2016-08-19 00:07 UTC
Object above currently active object could not be selected on 1.6.3

Test:
https://jsfiddle.net/vudduu/ukez8j4w/2/

clone: #1188, #1204

**Comment by saadqbal** [comment] 2016-08-19 07:25
try this: [https://jsfiddle.net/ecvctazk/48/](https://jsfiddle.net/ecvctazk/48/)

Solution by @neopheus

**Comment by neopheus** [comment] 2016-08-19 13:16
https://github.com/kangax/fabric.js/pull/3178

**Comment by asturur** [comment] 2016-08-20 15:41
Duplicate of #3095

**Closed by asturur** 2016-08-20 15:41 UTC
