### ISSUE TITLE
Unable to rotate/move text on canvas

### ISSUE THREAD

**Issue by ashukasama** [kangax/fabric.js#2365] opened 2015-07-27 10:50 UTC
I am adding element in following order
1. Image
2. Image - Hide
3. Text - Hide
4. Text

When I try to select text content , it got selected , but I am not able to drag / move it.

Link - http://goo.gl/yuVVoV (password - opread)

Steps to reproduce
1. click on link and enter store 
2. again open this link
3. Now wait for all loading
4. click on bottom arrow in left box (http://prntscr.com/7xi9hi)
5. Now select one item as mentioned in image (http://prntscr.com/7xi9p6)
6. New popup window will be opened , http://prntscr.com/7xi9zb
7. Add text 

Now here my problem starts, I am not able to move and rotate selected text element (http://prntscr.com/7xiabu)

Now click on add/ and this popup drawing will be added to main canvas, now I double click on element it will again open popup with value filled.

Now I can move/rotate text.

**Comment by asturur** [comment] 2015-07-27 10:54
Please reproduce on jsFiddle with basic code or close the issue.
we cannot help.

The github webiste is for issues with library itself, not special application help.
For any general help use the google group.

**Comment by ashukasama** [comment] 2015-07-27 11:19
Ok let me create it.. share you guys an url....

**Comment by ashukasama** [comment] 2015-08-04 22:44
This is sample jsfiddle for this

http://jsfiddle.net/ashukasama/eeLnsfrp/1/

**Comment by asturur** [comment] 2015-08-05 06:04
this is clearly a problem with custom code.
you have a deactivateAll on text click, you cannot interact with text in this way.

**Comment by ashukasama** [comment] 2015-08-05 06:56
@asturur , I think deactivateAll is used deactivate , but we are making setActiveObject just below this line. I am trying to add text and change content live , 
It look like mouseclick event is sometime never work if we try to click on text , it select images elemnt instead of text,


I removed deactivateAll from this.

http://jsfiddle.net/ashukasama/554qgrdt/2/

if you feel it is custom code, I can remove keyup/click event etc, but still I am not able to drag and move this.

I tried bit different things also.

http://jsfiddle.net/ashukasama/gLw0a977/1/

**Comment by asturur** [comment] 2015-08-05 07:01
i ll check it better, but it clearly look like an application problem. i m not on pc now.

**Comment by ashukasama** [comment] 2015-08-05 07:09
Let me share you more code which is generic code instead of my fabric etc.

Additionally I tried to use code into kitchen sink, you will observe same thing, we are not able to select text any how

```javascript
// clear canvas
canvas.clear();

var imgurl = "http://lavender-sandbox.myshopify.com/apps/lavender/imageserver/img_55a6c78f15d9b.jpg";

fabric.Image.fromURL(imgurl, function(img) {
    var oImg = img.set({ left: 50, top: 100 }).scale(0.4);
    canvas.add(oImg).renderAll();
    canvas.centerObject(oImg);
    canvas.setActiveObject(oImg);

var fronttext = new fabric.Text( "hello", { 
        label : 'text',
        fontWeight: 'normal',
        textAlign: 'center',
        texttype : 0,
        left: 0,
        top: 0,
        width: 100,
        height: 50
    });
    
    fronttext.isBack = true;
    fronttext.lockScalingX = fronttext.lockScalingY   = false ;
    canvas.add(fronttext);
        canvas.bringToFront(fronttext);
   
    canvas.centerObject(fronttext);
    canvas.setActiveObject(fronttext);
    canvas.renderAll().calcOffset();

  });
```

I have following steps
http://i.imgur.com/D8Oa4ox.png

1. Paste above code 
2. Click execute
3. Click on text element

Now I am not able to drag/drop/move text

**Comment by ashukasama** [comment] 2015-08-05 20:01
@kangax @asturur is this really bug or not ?

**Comment by asturur** [comment] 2015-08-06 05:51
as i told you, no, it is an application problem.
In all your fiddles, you show lot of code not related to the problem, this make checking more difficult.
In all your filldles, after calling centerObject(x) you are not calling x.setCoords, so the object is still selectable, but just in its original position.

**Closed by asturur** 2015-08-06 05:51 UTC

**Comment by varunprashar5** [comment] 2015-08-12 14:52
I am also facing similar problem. When I add text and make it setActiveObject. 
But when I try to grab it to move , its  unable to grab. Actually it got focused above i.e I see the Grab cursor above the text element or below.

It may be due to dynamically change of canvas size? But I am not sure . 

Please me know how it can be solved :( .

**Comment by ashukasama** [comment] 2015-08-12 20:07
@asturur thanks buddy... yeah Its my application mistake or even I was not aware about this function...

@varunprashar5  did you used setCoords after you change text position?

**Comment by varunprashar5** [comment] 2015-08-13 12:51
It resolved my issue. setCoords was the solution. I was not aware of it. 

Thanks
