### ISSUE TITLE
Text tspan offsets not recognized when loading from SVG

### ISSUE THREAD

**Issue by paulohp** [kangax/fabric.js#420] opened 2013-02-12 14:54 UTC
Guys, I have a problem when rendering a file svg. This file has many paths and some text with formatting and position already defined. I saved this SVG and text are positioned perfectly and with all properties. But when I do loadSVGFromURL, gets all unformatted text without line break and with different size and color, and sometimes with a black background.

**Comment by kangax** [comment] 2015-07-14 14:56
Duplicate of #1280

**Closed by kangax** 2015-07-14 14:56 UTC
Labels: bug, svg_parser
