### ISSUE TITLE
iText Chinese bug

### ISSUE THREAD

**Issue by evolutionjay** [kangax/fabric.js#3515] opened 2016-12-09 05:53 UTC
## Version
1.7.1

## Test Case
https://www.youtube.com/watch?v=m_htsONTAec

just look at the video

**Comment by asturur** [comment] 2016-12-09 08:55
duplicate of #3069

i will try to take care of it, on windows i did a bit, on mac it works differently.

**Closed by asturur** 2016-12-09 08:55 UTC
