### ISSUE TITLE
loadSVGFromString (Load without grouping in kitchensink)  not working reliably

### ISSUE THREAD

**Issue by ThorsenRune** [kangax/fabric.js#2537] opened 2015-10-08 10:02 UTC
While testing the fabric.js I ran into problems of importing an SVG (Example below).
Objects are displaced and Load without grouping results in unselectable objects.
To my opinion reliable import/export is critical 
What is the problem, is it known and can it be solved?

Simple example
<svg width="300" height="500" id="svg2" style="width: 500px;">

  <desc>Created with Fabric.js 1.5.0</desc><defs></defs><circle cx="0" cy="0" r="100" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #eef; fill-rule: nonzero; opacity: 1;" transform="translate(336.27 339.22) "></circle>
	<g transform="translate(250 250)">
		<text font-family="Times New Roman" font-size="40" font-weight="normal" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;"><tspan x="-111.0938" y="-17.232" fill="rgb(0,0,0)">A long and </tspan><tspan x="-111.0938" y="35.2" fill="rgb(0,0,0)"> winding road</tspan></text>
	</g>
<circle cx="0" cy="0" r="50" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" transform="translate(434.31 69.61) "></circle>
<g transform="translate(264.25 159.57) rotate(294.3) scale(1 2.88)">
<polygon points="-7.5 7.5,0 -7.5,7.5 7.5" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0, 0, 0); fill-rule: nonzero; opacity: 1;" transform="translate(0 46) rotate(180)"></polygon><line x1="0" y1="-50" x2="0" y2="50" style="stroke: rgb(0, 0, 0); stroke-width: 5; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" transform="translate(0 -4)"></line>
</g>
</svg>

**Comment by asturur** [comment] 2015-10-08 10:10
Import and export is realiable using SVG as as single object ( pathgroup ).
To import and export a scene setup, use the JSON format.

You can see info in #1520

I worked a lot to solve this issue and we are near.
I just need to find time to sit down ad analyze shape by shape how is imported and change it.
I close it as a duplicate of #1520.

**Closed by asturur** 2015-10-08 10:10 UTC

**Comment by ThorsenRune** [comment] 2015-10-08 11:07
Thanks for the reply, while waiting I suggest that it is written somewhere in the manual or kitchensink that this feature has problems.
Rune

**Comment by kangax** [comment] 2015-10-08 15:14
Good idea. Andrea, could you mention this in the docs?
