### ISSUE TITLE
issue with _shouldClearSelection

### ISSUE THREAD

**Issue by fingerpich** [kangax/fabric.js#1925] opened 2015-01-11 16:41 UTC
i made a rectangle border behind all other object
and set selectable:false for it

then group Selection doesn't work for me
i found the problem in _shouldClearSelection
_shouldClearSelection checks !selectables but why it need activeObject ?

    (target &&
          !target.selectable &&
          activeObject &&
          activeObject !== target)
      );

**Comment by kangax** [comment] 2015-01-12 10:30
Because if there's no active (selected) object at the moment, there's no need to clear the selection

**Comment by fingerpich** [comment] 2015-01-12 14:49
return (
        !target 
        ||
        (target &&
          activeGroup &&
          !activeGroup.contains(target) &&
          activeGroup !== target &&
          !e.shiftKey)
        ||
        (target && !target.evented)
        ||
        (target &&  !target.selectable &&
          activeObject &&
          activeObject !== target)
      );
so why **line 2** doesn't check activeObject ?
i asked this because i think **!target(line 2)** is equal to **(target && !target.selectable)** on mousedown

also group selection initialize at _clearSelection       ( this._groupSelector = {...} )
and _clearSelection called when _shouldClearSelection be true
so i think _shouldClearSelection is responsible for group selection 
so its better to remove activeObject checking or what?

**Comment by asturur** [comment] 2016-04-26 01:26
duplicate of #1506

**Closed by asturur** 2016-04-26 01:26 UTC
Labels: needs_confirmation
