### ISSUE TITLE
Selection box does not get drawn if selection begins on a non selectable element

### ISSUE THREAD

**Issue by gordyr** [kangax/fabric.js#2033] opened 2015-03-11 17:02 UTC
I'm a bit unsure as to whether this is intended behaviour or not.  But it certainly doesn't seem correct to me.

If I place a large object such as a ```Rect``` onto an interactive canvas then place a smaller selectable object on top of it, I cannot select the smaller, selectable object using the selection box unless I begin the selection outside of the larger non-selectable object.

It appears that the event required to trigger the selection box does not propagate through any non-selectable objects.

This is extremely inconvenient for use cases where you need a custom background made up of non-selectable fabric objects  and intend to have selectable objects on top of this custom background.

The fix is a very simply one and appears to be a bug in the ```_shouldClearSelection``` method.

Currently this method will not return ```true``` if the mouse is down on a non selectable target.  Surely even though you are over a non selectable target your would always want to be able to initialize the drawing of a selection box in order to capture any other selectable objects.  Am I correct?

Changing one line in the function fixes the issue:

```

 _shouldClearSelection: function (e, target) {
            var activeGroup = this.getActiveGroup(),
                activeObject = this.getActiveObject();

            return (
            !target
            ||
            (target &&
            activeGroup &&
            !activeGroup.contains(target) &&
            activeGroup !== target &&
            !e.shiftKey)
            ||
            (target && !target.evented)
            ||
            (target &&
            !target.selectable) // also return true if the target is present but non selectable
            ||
            (activeObject &&
            activeObject !== target)
            );
        }

```

**EDIT:** I have just noticed that I can force events to propagate through by setting the objects ```evented``` property to false. This may mean that the behaviour is as intended.  Although it seems odd to me as surely you should be able to initialize group selection from anywhere on the canvas outside of selectable objects.

@kangax  could you confirm if this is as intended?  Thanks.

**Comment by kangax** [comment] 2015-03-25 12:23
Yes, evented was introduced specifically for obscure cases like this. But hold on... I don't really understand how you're not able to select top object? It should work. I checked on kitchensink and not seeing it. I must be misunderstanding something. Mind showing a quick fiddle?

**Comment by inssein** [comment] 2015-03-26 17:30
@kangax Selecting an object works, but multi select (via click + drag) doesn't work. 

Setting "evented" to false seems to do the trick, but opens up a lot of new issues for me. For example, if there is a background with 4 elements on top of it, selecting two elements selects the two elements, the background, and the other two elements are now behind the background.

**Comment by asturur** [comment] 2015-06-01 11:49
@inssein  the issue you are referring two is resolved enabling canvas.preserveObjectStacking property.

While for all the other unselectable problem we always suggest to use "evented" as false.
do you think we can close or there is something left unresolved?

**Comment by asturur** [comment] 2016-04-25 23:57
duplicate of #1506

**Closed by asturur** 2016-04-25 23:57 UTC
Labels: needs_confirmation
