### ISSUE TITLE
SVG Fill Blur Not Working

### ISSUE THREAD

**Issue by otterslide** [kangax/fabric.js#4057] opened 2017-07-02 19:36 UTC
## Version
1.7.4

## Test Case
http://jsfiddle.net/otterotter/77bf32py/

## Steps to reproduce
Click Load SVG at the bottom.
The bottom of this SVG has a blur, but it shows up as a hard black line in Fabric.

## Expected Behavior
Blur expected.

## Actual Behavior
No blur.

**Comment by otterslide** [comment] 2017-07-02 19:41
It should look like this:
http://picpaste.com/pics/cloud-UMxYBJE3.1499024464.png
Any way to achieve the blur effect with SVGs imported into Fabric?

**Comment by asturur** [comment] 2017-07-02 20:48
duplicate of #1577

**Comment by asturur** [comment] 2017-07-02 20:49
Filters from svg are not supported

**Closed by asturur** 2017-07-02 20:48 UTC

**Comment by otterslide** [comment] 2017-07-19 18:33
Will this ever be supported?..  I really liked the idea of SVGs in the canvas, but at minimum I need blurs to work, they are used quite often.

**Comment by asturur** [comment] 2017-07-19 20:09
i have some plan that is:

release 2.0
support clipPath
support better patterns
move filters to objects and not to images
from that point it can be supported. I m working a lot this year i have not much time for fabric
