### ISSUE TITLE
Colors of grouped objects,lost when loadFromJSON

### ISSUE THREAD

**Issue by Eseperio** [kangax/fabric.js#2162] opened 2015-04-30 16:30 UTC
If you group various objects with different colors each one, and export to JSON, then import from JSON all the objects turns black. I think that the problem is that groups has the propery "fill", then the enliver process this property as black.
![colors-1](https://cloud.githubusercontent.com/assets/5459366/7417501/c9bb9882-ef66-11e4-8a5e-18a9a1830f21.JPG)
![colors-2](https://cloud.githubusercontent.com/assets/5459366/7417502/c9bffa08-ef66-11e4-9c2c-43a9c1b6a281.JPG)

**Comment by asturur** [comment] 2015-05-04 07:38
duplicate of #2119

**Closed** 2015-05-04 07:38 UTC

**Comment by deepdoon** [comment] 2015-10-02 08:29
i am also facing same problem. I am grouping multiple objects but they are using black as value of fill property.  below is the code that i am using. 


<addr>function fnGroup() {
    var activegroup = canvas.getActiveGroup();
    var arrayProperties = ['propertyname', 'id', 'name', 'tempPreviewData', 'nutrientId', 'lockMovementX', 'lockMovementY', 'lockScalingX', 'lockScalingY', 'lockRotation','fill'];
    var objectsInGroup = activegroup.getObjects();
    activegroup.clone(function (newgroup) {
        canvas.discardActiveGroup();
        objectsInGroup.forEach(function (object) {
            canvas.remove(object);
        });
        canvas.add(newgroup);
    }, arrayProperties);
}</addr>

**Comment by sapics** [comment] 2015-10-02 08:33
Are you using latest version of fabric.js (v1.6.0-rc.1)?
I guess that we need to use latest version.

**Comment by deepdoon** [comment] 2015-10-02 08:35
@sapics  actually i am using a version in which wordwrapping is implemented. So even if i use latest it will be overwritten by the one which have word-wrapping feature.

**Comment by sapics** [comment] 2015-10-02 08:38
How about removing 'fill' from arrayProperties?

**Comment by deepdoon** [comment] 2015-10-02 08:40
it didn't worked, actually initially i didn't had this fill property in arrayProperties, but just to make sure that i am not missing anything i added this property to array. In either case it is not working.

**Comment by asturur** [comment] 2015-10-02 09:53
You have to use latest version after merge of fix from @sapics about leaking of delegate properties.
There is a wordbreak for textbox ready for latest version you can take and bring with you.

**Comment by deepdoon** [comment] 2015-10-02 10:06
@asturur  yes i checked the latest version, wordwrapping is there and group is working fine with fill property. But the thing is i am not able to decrease the width of text object to break/wrap the word.

**Comment by deepdoon** [comment] 2015-10-02 10:07
is there any overloaded method or any property to enable width decrease there? @asturur

**Comment by RWizard** [comment] 2015-10-02 10:12
In last version (1.6rc1) color in Group fixed, but find bug with custom fonts in nodejs render (in browser fine, in nodejs bug). Not worked font family and size.

**Comment by deepdoon** [comment] 2015-10-02 10:17
@RWizard  @asturur  @sapics I am looking for a way to resize the textbox object to break words. below is the code i use in Kitchensink example, in this i am not able to resize the textbox below the textbox width.

   txtb = new fabric.Textbox('testasdasdasdasd', {
        fontFamily: 'arial',
        fill:'#000000',
        fontSize: 22,
        left: 15,
        width: 150,
        height: 50,
        top: 10,
        cornerSize: 5    });

canvas.add(txtb)

**Comment by asturur** [comment] 2015-10-02 10:31
https://github.com/kangax/fabric.js/pull/2445/files  here there is word brekaing. It is working, and if you search in other issues, you find one with better code for breaking word only if needed.

**Comment by deepdoon** [comment] 2015-10-02 10:37
thankyou very much @asturur
