### ISSUE TITLE
PerPixelTargetFind doesn't select proper object once an object is already selected

### ISSUE THREAD

**Issue by otterslide** [kangax/fabric.js#3230] opened 2016-09-04 23:26 UTC
## Version
1.6.4

## Test Case
https://jsfiddle.net/otterslide/snjxLv4h/3/

## Steps to reproduce
Click on the red square. Click on the green shape. The green shape doesn't get selected.

Reload the page and try:
Click on Green shape, then click in the green shape's transparent area. The red shape is selected, so it works this way, but it's impossible to re-select the green shape now.

## Expected Behavior
Be able to select objects based on their pixel transparency, and have it work the same even if an object is selected or not selected currently.  If no object is initially selected it works fine, but if an object is already selected, then it favors that object, even if another is on top of it.

Perhaps a flag for this behavior could be used in case not everyone wants it to work this way.

**Comment by Fidel90** [comment] 2016-09-05 06:32
Probably related to/same as https://github.com/kangax/fabric.js/issues/3095

**Comment by asturur** [comment] 2016-09-05 13:33
duplicate of #3095

**Closed by asturur** 2016-09-05 13:33 UTC
