### ISSUE TITLE
Blur text on canvas

### ISSUE THREAD

**Issue by HATyCEHKA** [kangax/fabric.js#4279] opened 2017-09-01 10:32 UTC
Text is very blur on canvas  from v1.7.14 and in all versions later.
Clear text (v.1.7.0)  https://jsfiddle.net/wxvrb5a3/
Blur text (v.2.0.0) https://jsfiddle.net/cxovh28o/3/

## Version
since 1.7.14

**Comment by ncou** [comment] 2017-09-01 13:47
Hi,
I got the same result for both jsfiddle.
What is your browser ?

Perhaps you can try to disable the cache to test if there is a difference ? (objectCaching: false)

**Comment by HATyCEHKA** [comment] 2017-09-01 13:56
Google Chrome, internet explorer 11, firefox.
I already tried to clear browser cache, open in inkognito mode. Result is the same.
Chrome:
![image](https://user-images.githubusercontent.com/26141774/29972879-5a988d12-8f36-11e7-85bb-0a7aeed89e8a.png)
ie:
![image](https://user-images.githubusercontent.com/26141774/29972746-d1de35c6-8f35-11e7-82cc-90a00a2fdac4.png)
firefox:
![image](https://user-images.githubusercontent.com/26141774/29972895-6e9bc130-8f36-11e7-9b08-cea0426af1d7.png)

**Comment by ncou** [comment] 2017-09-01 14:09
For the cache, à was speaking about the internal fabric.js cache engine (this helped me in the case of the Itext component).
Here : https://jsfiddle.net/cxovh28o/4/

**Comment by asturur** [comment] 2017-09-01 14:17
speaking of screenshot that you posted, what is the blurry one and the clear one? they look pretty similar to me

**Comment by ncou** [comment] 2017-09-01 14:58
the blurry one is on the right (you see it a bit better with the firefox screenshot).
I could reproduce it under firefox (but not chrome or IE).

And disabling the cache give me back crispy result.

**Comment by HATyCEHKA** [comment] 2017-09-01 15:02
The blury is right one. You can see better if open full size image.

1 сент. 2017 г. 17:17 пользователь "Andrea Bogazzi" <
notifications@github.com> написал:

**Comment by HATyCEHKA** [comment] 2017-09-01 15:07
In chrome mobile on android text everything is ok on all versions of
fabric.js. Very strange...

**Comment by asturur** [comment] 2017-09-01 18:16
The point is that there is little to do.
On chrome mobile it looks better probably because you have an HDPI screen and you are rendering at higher resolution.

The only way to fix blurriness is to remove cache for now.

Probably is possible to get the right positioning for the text, one pixel at time to avoid blurriness most of the time, but for now i have no idea how to do it.

**Comment by asturur** [comment] 2017-09-01 18:16
duplicate of #4113

**Closed by asturur** 2017-09-01 18:16 UTC
